objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region_Number__c</fullName>
        <description>Region number
Dealership region (Actual Region)</description>
        <label>Region Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collection_List_Number_1__c</fullName>
        <label>Collection List Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_Number__c</fullName>
        <description>Region number</description>
        <label>Region Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_PaymentHistoryControllerTest.cls
@isTest
private class TFSC_PaymentHistoryControllerTest {
    
    
    
    static testmethod void testController() {
    	
    	String randomString = TFSC_TestUtils.generateRandomString(6);
    	
    	
    	Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c fAcct = setupData(acct);
    	
    	
    	PageReference pageRef = Page.TFSC_PaymentHistory;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('recordId', fAcct.Id);
        
        TFSC_PaymentHistoryController ctrl = new TFSC_PaymentHistoryController();
        
        
    	
    }
    
    
    private static Financial_Account__c setupData(Account acct) {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = randomString);
        financialAccount.Collection_List_Number_1__c = '1704'; // for FPD
        financialAccount.History_Counter_Days_Past_Due__c = '10';
        financialAccount.Region_Number__c = '01';
        insert financialAccount;
        
        
        return financialAccount;
    }
    
    
}