objects/Account.object
<CustomObject>
    <fields>
        <fullName>SGUID__c</fullName>
        <description>Unique Identifier from the Toyota and Lexus Web portal.
This will also be used as the SSO federation id.</description>
        <label>SGUID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EWS_Account__c.object
<CustomObject>
    <fields>
        <fullName>EWS_User__c</fullName>
        <label>EWS User</label>
        <referenceTo>EWS_User__c</referenceTo>
        <relationshipLabel>EWS_Accounts</relationshipLabel>
        <relationshipName>EWS_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FA_Num__c</fullName>
        <label>FA Num</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role__c</fullName>
        <label>FA Role</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGUID__c</fullName>
        <label>SGUID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EWS_Account</label>
    <nameField>
        <displayFormat>EWSA-{000000000}</displayFormat>
        <label>EWS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EWS_Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EWS_User__c.object
<CustomObject>
    <fields>
        <fullName>AcctMgmtEmail__c</fullName>
        <externalId>true</externalId>
        <label>AcctMgmtEmail</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SGUID__c</fullName>
        <externalId>true</externalId>
        <label>SGUID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <externalId>true</externalId>
        <label>User Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>EWS User</label>
    <nameField>
        <label>EWS User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EWS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_BatchMigrateEWSTest.cls
@IsTest
public class TFSC_BatchMigrateEWSTest {
	@IsTest
	public static void test () {
		Account acct = new Account(name = 'testAcct1');
        insert acct;
        
		Financial_Account__c financialAccount2 = new Financial_Account__c(Name = '123', Financial_Account_Number__c = '123');
        insert financialAccount2;
        generateAndInsertFAC(financialAccount2.Id, '0', 'Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
        generateAndInsertFAC(financialAccount2.Id, '6', 'Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
		
		EWS_User__c ewsUser = new EWS_User__c();
		ewsUser.SGUID__c = 'abc';
		ewsUser.User_Id__c = 'test';
		ewsUser.AcctMgmtEmail__c = 'test@test.com';
		insert ewsUser;
		
		List<EWS_Account__c> accountsToAdd = new List<EWS_Account__c>();
		EWS_Account__c ewsAccount = new EWS_Account__c();
		
		accountsToAdd.add(new EWS_Account__c(EWS_User__c=ewsUser.Id, FA_Num__c='123', FA_Role__c='0'));
		accountsToAdd.add(new EWS_Account__c(EWS_User__c=ewsUser.Id, FA_Num__c='123', FA_Role__c='6'));
		insert accountsToAdd;
		
		TFSC_BatchMigrateEWS batchClass = new TFSC_BatchMigrateEWS('122', 100);
		batchClass.execute(null, accountsToAdd);
	} 
	
	private static Financial_Account_Customer__c generateAndInsertFAC(Id FAId, String borrowerPosition, String openOrClosed, Id AcctId, String randString) {
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c();
        fac.Borrower_Position__c = borrowerPosition;
        fac.Financial_Account__c = FAId;
        fac.Account__c = acctId;
        fac.Home_Phone_Garage__c = '4063775090';
        fac.Mobile_Phone__c = '4063775091';
        fac.Work_Phone_Garage__c = '4063775092';
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = borrowerPosition;
        fac.FA_Role_Status__c = 'test';
        fac.Financial_Account_Customer__c = 'test' + randString;
        //fac.Finance_Account_Status__c = openOrClosed;
        insert fac;
        
        return fac;
    }
	
	
}