objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Auction</fullName>
        <active>true</active>
        <description>A service provider that assists in the disposition and sale of repossessed vehicles</description>
        <label>Auction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record Type for Dealer Account</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Auction_Agency_Zip__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction zip code at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title_Zip__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The zip code to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_TitleRequestAddressEditControllerTest.cls
@isTest
private class RL_TitleRequestAddressEditControllerTest {
	
	@isTest static void test_method_one() {
        //Setup Test Data
        Map<String, Form_Rule__c> formRuleMap = RL_GenerateTestData.insertFormRuleData();        
        Id dealerRTId = RL_GenerateTestData.getRecordType('Account', 'Dealer');
        Account dealer = RL_GenerateTestData.createTestDealer(dealerRtId);
        
        Id retailRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Retail');        
        Financial_Account__c faRetail = RL_GenerateTestData.createFARetailIL(dealer, retailRTId);

        Collateral__c collateral = new Collateral__c(Name='Test Collateral', Vehicle_Identification_Number__c='12345');
        insert collateral;
        
        faRetail.Collateral__c = collateral.Id;
        update faRetail;

        Id caseRTId = RL_GenerateTestData.getRecordType('Case', 'Rights Letter');        
        Case aCase = RL_GenerateTestData.createCase(faRetail, caseRTId);  
        aCase.Form_Rule__c = formRuleMap.get('4015MD').Id;
        aCase.RL_System_Required_Notice_Date_Time__c = DateTime.now();
        update aCase;
        
        Id auctionRTId = RL_GenerateTestData.getRecordType('Account', 'Auction');                
        Account auctionAccount = new Account(RecordTypeId=auctionRTId, Name='Test Auction Account', BillingStreet='1234 Test \n Bay street');
        insert auctionAccount;

        Repossession__c repo = RL_GenerateTestData.createRepossessionMD(aCase, faRetail);     
        repo.Title_Zip__c = '12345';
        update repo;

        //Execute Controller methods
		PageReference pageRef= Page.RL_TitleRequestAddressEdit;
        Test.setCurrentPage(pageRef);        
        ApexPages.currentPage().getParameters().put('Id', repo.Id);

        ApexPages.StandardController repoStdController = new ApexPages.StandardController(repo);
        RL_TitleRequestAddressEditController controller = new RL_TitleRequestAddressEditController(repoStdController); 
        controller.selectedAuctionAcct = auctionAccount.Id;
        controller.saveNewAccountValues();
        controller.copyVendorInformation(); //Modified by Shashank Singhal for S-311648 on 6/1/2015
        System.assertEquals(repo.Title_Zip__c, auctionAccount.BillingPostalCode);
        System.assertEquals(repo.Auction_Agency_Zip__c, repo.Title_Zip__c); //Modified by Shashank Singhal for S-311648 on 6/1/2015

        //Test for exception on repo update
        auctionAccount.BillingPostalCode = '12345678901';
        update auctionAccount;
        controller.saveNewAccountValues();
        System.debug(ApexPages.getMessages().get(0).getDetail());
        boolean errMsg = ApexPages.getMessages().get(0).getDetail().contains('max length=10') ? true : false;
        System.assert(errMsg);            
	}
	
}