objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Auction</fullName>
        <active>true</active>
        <description>A service provider that assists in the disposition and sale of repossessed vehicles</description>
        <label>Auction</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record Type for Dealer Account</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case_Skills__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Skills defined on case to support prioritization and case assignment</description>
    <label>Case Skills</label>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RL_Auction_Agency_URL__c</fullName>
        <label>Online Auction URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form__c.object
<CustomObject>
    <description>Represents a distinct form to be generated through the Adobe Forms Service.</description>
    <fields>
        <fullName>Copy_per_FAC__c</fullName>
        <defaultValue>true</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Drives behavior of form generation to produce a document request for each active FAC associated with the account.</description>
        <inlineHelpText>If checked then a separate form is generated for each active FAC with that FAC&apos;s information</inlineHelpText>
        <label>Copy per FAC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Request_Record_Type__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Determines the record type for the generated document request.</description>
        <label>Document Request Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rights Letters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice of Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Primary_FAC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Indicates if the field should always reference the primary borrower or the current FAC.</description>
        <inlineHelpText>If checked the primary borrower&apos;s record (FAC) is always used to fill in this field.</inlineHelpText>
        <label>Primary FAC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The source field from which the data should be fetched.</description>
        <label>Source Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The source object from which the data should be fetched.</description>
        <label>Source Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The target field on the document request record or line item where the data will be stored.</description>
        <label>Target Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Field_Junction__c.object
<CustomObject>
    <description>Junction object linking Forms with their Form Fields and supporting re-use of fields across forms.</description>
    <fields>
        <fullName>Form_Field__c</fullName>
        <label>Form Field</label>
        <referenceTo>Form_Field__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Fields</relationshipLabel>
        <relationshipName>Form_Field_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form-Field Junction</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Form-Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Field Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>Form__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Purely informational and identifies forms that are associated - use Form-Rule Junction to specify forms to print with rights letter generation request.</description>
        <label>Form</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Rule_Junction__c.object
<CustomObject>
    <description>Junction object linking Form Rules with Forms supporting multiple forms required for a single state’s process and many states use the same form.</description>
    <fields>
        <fullName>Form_Rule__c</fullName>
        <label>Form Rule</label>
        <referenceTo>Form_Rule__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Form_Rule_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Rules</relationshipLabel>
        <relationshipName>Form_Rule_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form-Rule Junction</label>
    <nameField>
        <displayFormat>FFR-{000000}</displayFormat>
        <label>Form-Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form-Rule Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_GenerateNoticeOfSaleControllerTest.cls
@isTest
private class RL_GenerateNoticeOfSaleControllerTest {
    
    @isTest static void test_method_one() {
        //Setup Data
      Test.startTest();
      Map<String, Form_Rule__c> formRuleMap = RL_GenerateTestData.insertFormRuleData();
      Id dealerRTId = RL_GenerateTestData.getRecordType('Account', 'Dealer');
      Account dealer = RL_GenerateTestData.createTestDealer(dealerRtId);
      
      Id retailRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Retail');        
      Financial_Account__c faRetail = RL_GenerateTestData.createFARetailIL(dealer, retailRTId);
      
      Collateral__c collateral = new Collateral__c(Name='Test Collateral');
      insert collateral;
      
      faRetail.Collateral__c = collateral.Id;
      update faRetail;
              
      Id caseRTId = RL_GenerateTestData.getRecordType('Case', 'Rights Letter');        
      Case aCase = RL_GenerateTestData.createCase(faRetail, caseRTId);  
      aCase.Form_Rule__c = formRuleMap.get('4015IL').Id;
      aCase.RL_System_Required_Notice_Date_Time__c = DateTime.now();
      update aCase;
      
      Repossession__c repo = RL_GenerateTestData.createRepossession(aCase, faRetail);     

      Form_Field__c formField = new Form_Field__c(Primary_FAC__c = FALSE, Source_Field__c='Financial_Account_Number__c', Source_Object__c='Financial_Account__c', Target_Field__c='AccountNumber__c');      
      insert formField;

      Case_Skills__c cs = RL_GenerateTestData.createCaseSkills();

      List<Form__c> formList = new Form__c[] {new Form__c(Copy_per_FAC__c = TRUE, Name='4028MD', Document_request_record_type__c=RL_Constants.DR_NOS_RT), new Form__c(Name=RL_Constants.COVER_LETTER_FORM, Document_request_record_type__c=RL_Constants.DR_RL_RT, Copy_per_FAC__c = TRUE)};
      insert formList;

      Form_Rule_Junction__c formRuleJunction2 = new Form_Rule_Junction__c(Form_Rule__c=formRuleMap.get('4028MD').Id, Form__c=formList[0].Id);
      insert formRuleJunction2;

      Form_Field_Junction__c ffJunction2 = new Form_Field_Junction__c(Form__c=formList[0].Id, Form_Field__c=formField.Id);
      insert ffJunction2;

      Id childCaseRT = RL_GenerateTestData.getRecordType('Case', 'RL Notice of Sale');  
      Case childCase = new Case(recordTypeId=childCaseRT, Financial_Account__c=faRetail.Id, ParentId=aCase.Id);
      childCase.Form_Rule__c = formRuleMap.get('4028MD').Id;
      childCase.RL_Physical_Sale_Date_1__c = Date.today() + 11;
      childCase.RL_Physical_Sale_Date_2__c = Date.today() + 12;
      childCase.RL_Online_Sale_1_From__c = Date.today() + 13;
      childCase.RL_Online_Sale_1_To__c = Date.today() + 14;
      childCase.RL_Online_Sale_2_From__c = Date.today() + 15;
      childCase.RL_Online_Sale_2_To__c = Date.today() + 16;
      childCase.RL_Physical_Sale_Time_1__c = '12:00 AM';
      childCase.RL_Physical_Sale_Time_2__c = '12:00 AM';
      childCase.RL_Auction_Agency_URL__c = 'www.iaai.com';
      insert childCase;
      System.debug('child case form rule: ' + childCase.Form_Rule__c);

      PageReference nosPageRef = Page.RL_GenerateNoticeOfSalePage;
      ApexPages.currentPage().getParameters().put('Id', childCase.Id);        
      ApexPages.StandardController caseStdController = new ApexPages.StandardController(childCase);
      RL_GenerateNoticeOfSaleController nosController = new RL_GenerateNoticeOfSaleController(caseStdController);
      Test.setCurrentPage(nosPageRef);
      nosController.generateNoticeOfSale();
      
      //Assertions
      Document_Request__c docRequest = [SELECT Id, Case__c FROM Document_Request__c WHERE Case__c =: childCase.Id];
      System.AssertEquals(docRequest.Case__c, childCase.Id);

      childCaseRT = RL_GenerateTestData.getRecordType('Case', 'RL Notice of Sale-Salvage');
      Case salvageChildCase = new Case(recordTypeId=childCaseRT, Financial_Account__c=faRetail.Id, ParentId=aCase.Id);
      salvageChildCase.Form_Rule__c = formRuleMap.get('4028MD').Id;
      salvageChildCase.RL_Salvage_Sale_Date_1__c = Date.today() + 11;
      salvageChildCase.RL_Salvage_Sale_Date_2__c = Date.today() + 12;
      salvageChildCase.RL_Salvage_Sale_Date_3__c = Date.today() + 13;
      salvageChildCase.RL_Salvage_Sale_Date_4__c = Date.today() + 14;
      salvageChildCase.RL_Salvage_Sale_Time_1__c = '12:00 AM';
      salvageChildCase.RL_Salvage_Sale_Time_2__c = '12:00 AM';
      salvageChildCase.RL_Salvage_Sale_Time_3__c = '12:00 AM';
      salvageChildCase.RL_Salvage_Sale_Time_4__c = '12:00 AM';
      insert salvageChildCase;

      ApexPages.currentPage().getParameters().put('Id', salvageChildCase.Id);        
      ApexPages.StandardController caseStdController2 = new ApexPages.StandardController(salvageChildCase);
      RL_GenerateNoticeOfSaleController nosController2 = new RL_GenerateNoticeOfSaleController(caseStdController2);
      Test.setCurrentPage(nosPageRef);
      nosController2.generateNoticeOfSale();        

      salvageChildCase.RL_Salvage_Sale_Time_1__c = null;
      salvageChildCase.RL_Salvage_Sale_Date_1__c = date.today();
      update salvageChildCase;
      nosController2.generateNoticeOfSale();  
      boolean errMsg = ApexPages.getMessages().get(0).getDetail().contains('Auction agency URL') ? true : false;
      System.assert(errMsg);            
      
      salvageChildCase.RL_Auction_Agency_URL__c = 'www.iaai.com';
      update salvageChildCase;
      nosController2.generateNoticeOfSale();  
      //errMsg = ApexPages.getMessages().get(1).getDetail().contains('Sale time fields are required') ? true : false;
      //System.assert(errMsg);

      salvageChildCase.RL_Salvage_Sale_Time_1__c = '12:00 AM';
      update salvageChildCase;
      nosController2.generateNoticeOfSale();  
      //errMsg = ApexPages.getMessages().get(2).getDetail().contains('greater than 10 days') ? true : false;
      //System.assert(errMsg);

/*      salvageChildCase.RL_Salvage_Sale_Date_1__c = null;
      update salvageChildCase;
      nosController2.generateNoticeOfSale();  
      //errMsg = ApexPages.getMessages().get(3).getDetail().contains('Sale date fields are required') ? true : false;
      //System.assert(errMsg);

      salvageChildCase.RL_Salvage_Sale_Date_1__c = date.today() + 11;
      salvageChildCase.RL_Salvage_Sale_Date_4__c = date.today() + 61;
      update salvageChildCase;
      nosController2.generateNoticeOfSale();  
      //errMsg = ApexPages.getMessages().get(4).getDetail().contains('more than 60 days') ? true : false;
      //System.assert(errMsg);

      salvageChildCase.RL_Salvage_Sale_Date_4__c = date.today() + 14;
      update salvageChildCase;    
*/
      Test.stopTest();
    }
}