objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record Type for Dealer Account</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Activity_Code__c.object
<CustomObject>
    <description>Business rules and process metadata associated with each available code applied to tasks.</description>
    <label>Activity Code</label>
    <nameField>
        <label>Activity Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ActivityEntryPanelControllerTest.cls
@isTest
private class ActivityEntryPanelControllerTest {

	@isTest static void test_method_one() {
        Id dealerRTId = RL_GenerateTestData.getRecordType('Account', 'Dealer');
        Account dealer = RL_GenerateTestData.createTestDealer(dealerRtId);
        
        Id retailRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Retail');        
        Financial_Account__c faRetail = RL_GenerateTestData.createFARetailIL(dealer, retailRTId);        
		faRetail.Financial_Account_Number__c = '7419510107';
        update faRetail;

        ActivityEntryPanelController controller = new ActivityEntryPanelController();
        controller.financialAccount = faRetail;
        List<SelectOption> aList = new List<SelectOption>();
        aList.add(new SelectOption('1', '1'));

        ActivityEntryPanelController.NoteTabWrapper wrapper = new ActivityEntryPanelController.NoteTabWrapper('None', '');
        wrapper.activityList = aList;
        controller.noteTab1Wrapper = wrapper;
        controller.firstNoteActivitiesWhereClause = 'Id != null';
        controller.saveNote1();

        System.assert(controller.pageHasErrorMessages);

        Activity_Code__c ac = new Activity_Code__c(Name='1');
        insert ac;

        wrapper.selectedActivityCode = '1';
        controller.noteTab1Wrapper = wrapper;
        controller.saveNote1();

        System.assert(controller.pageHasErrorMessages);

        Activity_Code__c ac2 = new Activity_Code__c(Name='2');
        insert ac2;

        wrapper.note = 'testing';
        controller.noteTab1Wrapper = wrapper;
        controller.saveNote1();

        System.assert(!controller.pageHasErrorMessages);

        controller.errorStringUsedForErrorMessageSetting = 'TEST';
        controller.setPageErrorMsg();

        System.assert(controller.pageHasErrorMessages);
    }
}