objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <description>Record Type for Dealer Account</description>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The earliest date by which TFS may sell a repossessed vehicle. Calculated date based upon the proposed notice date and adding days as defined in the related form rule record.</description>
        <label>Proposed Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Notice_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Calculated date to print on letter. Usually today&apos;s date, but may be advanced to next business day by code if mailing cutoff time has passed. Mailing cutoff times are specified in RL_Mail_Cutoff... custom labels.</description>
        <label>Proposed Notice Date</label>
        <type>Date</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_RepossessionTriggerTest.cls
/*****
 * Salesforce.com Success Services
 * Name: RL_RepossessionTriggerTest
 * Description: Test class for RL_RepossessionTrigger
 */

@isTest
private class RL_RepossessionTriggerTest {
    @isTest 
    static void test_method_one() {
        RL_GenerateTestData.createTimezoneIndicators();
        Map<String, Form_Rule__c> formRuleMap = RL_GenerateTestData.insertFormRuleData();
        Id dealerRTId = RL_GenerateTestData.getRecordType('Account', 'Dealer');
        Account dealer = RL_GenerateTestData.createTestDealer(dealerRTId);

        Id retailRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Retail');
        Id leaseRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Lease');
        Financial_Account__c faRetail = RL_GenerateTestData.createFARetailIL(dealer, retailRTId);
        Financial_Account__c faLease = RL_GenerateTestData.createFALeaseIL(dealer, leaseRTId);        

        // Create Case
        Id caseRTId = RL_GenerateTestData.getRecordType('Case', 'Rights Letter');        
        Case aCase = RL_GenerateTestData.createCase(faRetail, caseRTId);
        aCase.Form_Rule__c = formRuleMap.get('4015IL').Id;
        update aCase;

        // Create Repossession
        Id repoRTId = RL_GenerateTestData.getRecordType('Repossession__c', 'RL Retail-Generic');
        Repossession__c repo = RL_GenerateTestData.createRepossession(aCase, faRetail, repoRTId);
        repo = [Select Id, Proposed_Notice_Date__c, Proposed_Legal_Sale_Date__c from Repossession__c where Id = : repo.Id];

        // Assertions
        System.assertEquals(repo.Proposed_Legal_Sale_Date__c, repo.Proposed_Notice_Date__c.addDays(21));

        aCase.Form_Rule__c = formRuleMap.get('6026 (IL)').Id;
        update aCase;

        repo.Financial_Account__c = faLease.Id;
        repo.Proposed_Notice_Date__c = Date.today().addDays(-1);
        update repo;

        repo = [Select Id, Proposed_Notice_Date__c, Proposed_Legal_Sale_Date__c, Case__r.Form_Rule__r.Name from Repossession__c where Id = : repo.Id];
        Time aTime = Time.newInstance(1, 0, 0, 0);        
        Date theDate = Date.valueOf(RL_Utility.AddBusinessDays(DateTime.newInstance(repo.Proposed_Notice_Date__c, aTime), 21, RL_GenerateTestData.getBusinessHoursId()));
    //    System.assertEquals(repo.Proposed_Legal_Sale_Date__c.day(), theDate.day());
    //    System.assertEquals(repo.Proposed_Legal_Sale_Date__c.month(), theDate.month());
    //    System.assertEquals(repo.Proposed_Legal_Sale_Date__c.year(), theDate.year());
    }
}