objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Auction</fullName>
        <active>true</active>
        <description>A service provider that assists in the disposition and sale of repossessed vehicles</description>
        <label>Auction</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to align Form Rule with the case.</description>
        <label>State of Jurisdiction</label>
        <type>TextArea</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Auction_Agency_City__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction city at which repossession is scheduled to be sold.</description>
        <label>Auction Agency City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Name__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction name at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Phone__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction phone at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_State__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction state at which repossession is scheduled to be sold.</description>
        <label>Auction Agency State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street1__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 1 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street2__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 2 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Zip__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction zip code at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state of residence for the primary borrower if in the 50 states, otherwise it is the state of the dealer. The rights letters process follows the laws in the given state. The value is set by the RL Set State Conditions flow.</description>
        <label>State of Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_City__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The city to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Name__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The name to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Checkbox to indicate whether the user has selected an alternate title destination different from the auction location provided by United Road. It will also be checked when salvage is indicated. Prevents further overwrites from United Road updates.</description>
        <label>Title Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Phone__c</fullName>
        <label>Title Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Street1__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The first line of the street address to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Street1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Street2__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The second line of the street address to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Street2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Zip__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The zip code to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iRepo_AccountNumber__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Account number value iRepo has received from Collections system. Format is 20-characters long and requires manipulation to map to SFDC format. Used in RL Set State Conditions Flow to set the lookup field to the financial account number if FA found and VIN matches.

Retail format: 00070401234567890001
000 = leading pads
704 = bank number (charge-off is 700 for retail and 800 for leases - out-of-scope for current RL)
0123456789 = 10-digit SFDC account number
0001 = sequence number for borrower - internal to host and can be ignored

Lease format: 000000000002382KD841
0000000000 = leading pads
02 = region
&quot;&quot; = add a 0 after that
382 = branch
KD841 = unique lease number</description>
        <label>iRepo Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iRepo_VIN__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Vehicle identification number as stored in iRepo&apos;s system. Compared with the VIN on the collateral of the searched financial account to confirm a successful match between iRepo assignment and SFDC financial account. Also used as a reference to facilitate looking up a financial account for a mismatched repo.</description>
        <label>iRepo VIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_TitleRequestAddressEditController.cls
public with sharing class RL_TitleRequestAddressEditController {
    
    public SelectOption[] auctionAcctsSelectOptions{get;set;}
    public String selectedAuctionAcct{get;set;}
    public String formattedTitleAddress{get;set;}
    public String strPhoneNumber{get;set;}
    public boolean isCopy{get; set;}//Modified by Shashank Singhal for S-311648 on 6/1/2015 
    
    private Repossession__c contextRepo;
    
    public RL_TitleRequestAddressEditController(ApexPages.StandardController stdController) {
        isCopy = false;//Modified by Shashank Singhal for S-311648 on 6/1/2015 
        populateData(stdController);
    }
    
    private void populateData(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {   
            stdController.addFields(new String[] {'Case__r.Form_Rule__c', 'Case__c', 'iRepo_VIN__c', 'iRepo_AccountNumber__c', 
                                  'Financial_Account__c', 'State_of_jurisdiction__c', 'Title_Zip__c', 'Title_Street2__c', 
                                  'Title_Street1__c', 'Title_State__c', 'Title_Override__c', 'Title_Name__c', 'Title_City__c','Title_Phone__c',
                                  'Auction_Agency_Name__c', 'Auction_Agency_Street1__c', 'Auction_Agency_Street2__c', 'Auction_Agency_City__c', 
                                  'Auction_Agency_State__c', 'Auction_Agency_Zip__c'}); //Modified by Shashank Singhal for S-311648 on 6/1/2015 
        }
        contextRepo = (Repossession__c) stdController.getRecord();
        
        auctionAcctsSelectOptions = new SelectOption[]{};
        auctionAcctsSelectOptions.add(new SelectOption('', 'Select New Title Address'));
        selectedAuctionAcct = '';
        for(Account acct : [select id, Name
                            from Account
                            where RecordType.Name = 'Auction'
                            order by Name])
        {
            auctionAcctsSelectOptions.add( new SelectOption(acct.Id, acct.Name) );
        }
        strPhoneNumber = contextRepo.Title_Phone__c;
        formatTitleAddress();
    }
    
    private void formatTitleAddress() {
        String addy = '';
        
        //'', '', 
        //'', '', 'Title_Override__c', '', ''
        addy = appendAndReturnString(addy, contextRepo.Title_Name__c, false, false, false);
        addy = appendAndReturnString(addy, contextRepo.Title_Street1__c, true, false, false);
        addy = appendAndReturnString(addy, contextRepo.Title_Street2__c, true, false, false);
        if(contextRepo.Title_City__c != null || contextRepo.Title_State__c != null || contextRepo.Title_Zip__c != null) {
            addy += '<br />';
        }
        addy = appendAndReturnString(addy, contextRepo.Title_City__c, false, false, false);
        addy = appendAndReturnString(addy, contextRepo.Title_State__c, false, true, true);
        Boolean tmpPrependComma = false;
        if(contextRepo.Title_State__c == null && contextRepo.Title_Zip__c != null) {
            tmpPrependComma = true;
        }
        addy = appendAndReturnString(addy, contextRepo.Title_Zip__c, false, tmpPrependComma, true);
        
        formattedTitleAddress = addy;
    }
    
    private String appendAndReturnString(String strToReturn, String valToAppend, Boolean prependLineFeed, Boolean prependComma, Boolean prependSpace) {
        
        if(valToAppend != null && valToAppend != '') {
            if(prependLineFeed) {
                strToReturn += '<br />';
            }
            if(prependComma) {
                strToReturn += ',';
            }
            if(prependSpace) {
                strToReturn += ' ';
            }
            strToReturn += valToAppend;
        }
        
        return strToReturn;
    }
    
    public PageReference saveNewAccountValues() {
        
        if(selectedAuctionAcct != null && selectedAuctionAcct != '') {
            Account acct = [select id, Name, BillingPostalCode, BillingCity, BillingState, BillingStreet, Phone
                            from Account
                            where id = :selectedAuctionAcct];
            updateRepoValuesAfterValidationAndRevertIfFailure(acct);
        }else{
            appendErrorMessage('Select valid Auction Account');
        }
        
        return null;
    }
    
    private void updateRepoValuesAfterValidationAndRevertIfFailure(Account acct) {
        String parsedZip = contextRepo.Title_Zip__c;
        String parsedCity = contextRepo.Title_City__c;
        String parsedState = contextRepo.Title_State__c;
        String parsedStreet2 = contextRepo.Title_Street2__c;
        String parsedStreet1 = contextRepo.Title_Street1__c;
        String parsedName = contextRepo.Title_Name__c;
        String parsedPhone = contextRepo.Title_Phone__c;
        try {
            //clear all.
            contextRepo.Title_Zip__c = contextRepo.Title_City__c = contextRepo.Title_State__c = contextRepo.Title_Street2__c = contextRepo.Title_Street1__c = contextRepo.Title_Name__c = contextRepo.Title_Phone__c = '';
            
            String addy1 = '';
            String addy2 = '';
            
            if(acct.BillingStreet != null && acct.BillingStreet.length() > 0) {
                List<String> strList = acct.BillingStreet.split('\n');
                addy1 = strList[0];
                if(strList.size() > 1) {
                    addy2 = strList[1];
                }
            }
            
            contextRepo.Title_Zip__c = acct.BillingPostalCode; 
            contextRepo.Title_City__c = acct.BillingCity; 
            contextRepo.Title_State__c = acct.BillingState; 
            contextRepo.Title_Street2__c = addy2; 
            contextRepo.Title_Street1__c = addy1; 
            contextRepo.Title_Name__c = acct.Name;
            contextRepo.Title_Override__c = true;
            contextRepo.Title_Phone__c = acct.Phone;
            System.Debug('**Phone:' +contextRepo.Title_Phone__c);
            System.Debug('**City:' +contextRepo.Title_City__c);
            
            update contextRepo; 
            
            strPhoneNumber = contextRepo.Title_Phone__c;
            formatTitleAddress();
            
        }catch(Exception e) {
            contextRepo.Title_Zip__c = parsedZip;
            contextRepo.Title_City__c = parsedCity;
            contextRepo.Title_State__c = parsedState;
            contextRepo.Title_Street2__c = parsedStreet2;
            contextRepo.Title_Street1__c = parsedStreet1;
            contextRepo.Title_Name__c = parsedName;
            contextRepo.Title_Override__c = false;
            contextRepo.Title_Phone__c = parsedPhone;

            formatTitleAddress();
            
            appendErrorMessage(e.getMessage());
        }
    }
    
    private void appendErrorMessage(String errorMessage) {
        ApexPages.Message apexPageMessage = new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage);
        ApexPages.addMessage(apexPageMessage);
    }
    //Modified by Shashank Singhal for S-311648 on 6/1/2015 
    public void copyVendorInformation(){
        try{
            contextRepo.Auction_Agency_Name__c = contextRepo.Title_Name__c;
            contextRepo.Auction_Agency_Street1__c = contextRepo.Title_Street1__c;
            contextRepo.Auction_Agency_Street2__c = contextRepo.Title_Street2__c;
            contextRepo.Auction_Agency_City__c = contextRepo.Title_City__c;
            contextRepo.Auction_Agency_State__c = contextRepo.Title_State__c;
            contextRepo.Auction_Agency_Zip__c = contextRepo.Title_Zip__c;
            contextRepo.Auction_Agency_Phone__c = contextRepo.Title_Phone__c;
            update contextRepo;
            isCopy = true;
        }catch(exception e){
            appendErrorMessage(e.getMessage());
        }
    }
    //End of S-311648
}