objects/Account.object
<CustomObject>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Tax Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code_Garage__c</fullName>
        <description>Zip Code</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Make__c</formula>
        <label>(IVR) Make</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Name__c</formula>
        <label>(IVR) Model Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Model_Year__c</formula>
        <label>(IVR) Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_Security_Number__c</fullName>
        <formula>Account__r.Social_Security_Number__pc</formula>
        <label>(IVR) Social Security Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Identification_Number__c</fullName>
        <formula>Account__r.Tax_Identification_Number__c</formula>
        <label>(IVR) Tax Identification Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number_Last_8_Ch__c</fullName>
        <formula>TRIM(RIGHT(Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c, 8))</formula>
        <label>(IVR) Vehicle Identification Num Last8Ch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <formula>Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c</formula>
        <label>(IVR) Vehicle Identification Number</label>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_SearchControllerTemp.cls
/**    
    * @author  Amanjot Purewal
        * @date 8/25/2015    
        * @description This class handles Custom Search Parameters and methods
     */ 

public with Sharing class TFSC_SearchControllerTemp{
        public String fANumber{get;set;}
        public String sSN{get;set;}
        public String tIN{get;set;}
        public String fName{get;set;}
        public String lName{get;set;}
        public String busiName{get;set;}
        public String garZip{get;set;}
        public String vINFull{get;set;}
        public String vIN8{get;set;}
        public Integer noOfFAC;
    public Integer getnoOfFAC(){
        return noOfFAC;
    }
    public Id oneFAId;
    public Id getoneFAId(){
        return oneFAId;
    }
    public String oneFANo;
    public String getoneFANo(){
        return oneFANo;
    }
    private String queryFilter='';
    private Integer resultLimit1 = 10;
    private Integer resultLimit2 = 50;
    public list<Financial_Account_Customer__c> searchedFACs{get;set;} 
    

    public void TFSC_SearchControllerTemp(){
        }
    public void reset(){   
        System.debug('**********searchedFACs '+searchedFACs);
        searchedFACs = null;
    }

// create the dynamic query based on the User input parameters 
public void searchFAC(){
    noOfFAC = -1;
    oneFAId =null;
    oneFANo ='';
    System.debug('**********INSIDE CONTROLLER searchedFACs'+searchedFACs);
    String queryFilter = '';
    String selectFields = 'SELECT Id, Account__r.FirstName, Account__r.LastName, Account__r.Name, Name, Account__r.IsPersonAccount, Vehicle_Identification_Number__c,Financial_Account__r.Collateral__r.Vehicle_Identification_Number_Last_8_Ch__c,Model_Year__c,Make__c,Model_Name__c,Mailing_Postal_Code_Garage__c,Financial_Account_Number__c,Social_Security_Number__c,Tax_Identification_Number__c,Financial_Account__r.Id,Financial_Account__r.Finance_Account_Status__c FROM Financial_Account_Customer__c';
    String queryOrder = 'Account__r.Name , Mailing_Postal_Code_Garage__c,Financial_Account_Number__c '; // Order By fields
    String queryLimit = '51';//Put the max number of records limit here  
    
    if(TFSC_Utils.isNotNullAndNotEmpty(fANumber)){
    if(fANumber.length() == 10 || fANumber.length() == 11 ){
            queryFilter = queryFilter + ' Financial_Account__r.Financial_Account_Number__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
    }else if(fANumber.length() == 20 ){  
    if(fANumber.startsWith('000704') && fANumber.endsWith('0001') )
        {
        fANumber = fANumber.substring(6,16);
        }else if(fANumber.startsWith('0000000000')){            
        fANumber = fANumber.substring(10,12)+'0'+fANumber.substring(12,20);
        }
            queryFilter = queryFilter + ' Financial_Account__r.Financial_Account_Number__c =\''+String.escapeSingleQuotes(fANumber)+'\' AND';
    }
    }    
    if(TFSC_Utils.isNotNullAndNotEmpty(sSN)){
            queryFilter = queryFilter +' Social_Security_Number__c =\''+String.escapeSingleQuotes(sSN)+'\' AND' ;
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(tIN)){
           queryFilter = queryFilter + ' Tax_Identification_Number__c =\''+String.escapeSingleQuotes(tIN)+'\' AND' ;
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(lName)){
        queryFilter = queryFilter + ' Account__r.LastName =\''+String.escapeSingleQuotes(lName)+'\' AND';
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(fName)) {
                queryFilter = queryFilter + ' Account__r.FirstName LIKE \''+String.escapeSingleQuotes(fName)+'%\' AND';
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(garZip)){
            queryFilter = queryFilter + ' Mailing_Postal_Code_Garage__c =\''+String.escapeSingleQuotes(garZip)+'\' AND' ;
    }    
    if(TFSC_Utils.isNotNullAndNotEmpty(busiName)){
            queryFilter = queryFilter + ' Account__r.Name LIKE \''+String.escapeSingleQuotes(busiName)+'%\' AND';       
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(vINFull)){
            queryFilter = queryFilter + ' Vehicle_Identification_Number__c =\''+String.escapeSingleQuotes(vINFull)+'\' AND' ;
    }
    if(TFSC_Utils.isNotNullAndNotEmpty(vIN8)){
            queryFilter = queryFilter +' Financial_Account__r.Collateral__r.Vehicle_Identification_Number_Last_8_Ch__c =\''+String.escapeSingleQuotes(vIN8)+'\' AND' ;
    }    
    if(queryFilter.endsWith('AND')){    
        queryFilter = queryFilter.Substring(0,queryFilter.length()-4);//Remove the last "AND" from query String
    }
    String query = selectFields+' WHERE '+queryFilter+' ORDER BY '+queryOrder+' LIMIT '+queryLimit ; 
    System.debug('**********query'+query);

try{
    searchedFACs = (List<Financial_Account_Customer__c>)Database.Query(query);
    System.debug('**********searchedFACs'+searchedFACs);
    if(searchedFACs != null){ 
        noOfFAC = searchedFACs.size();
     }
    System.debug('**********noOfFAC'+noOfFAC);

    if(noOfFAC == 1 ){
    oneFAId = searchedFACs.get(0).Financial_Account__r.Id;
    oneFANo = searchedFACs.get(0).Financial_Account_Number__c;
    }
    System.debug('**********oneFAId'+oneFAId);
    System.debug('**********oneFANo'+oneFANo);
    System.debug('**********searchedFACs'+searchedFACs);
    if(noOfFAC == 0 ){
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'No Records found for this search Criteria')); 
    }else if(noOfFAC > resultLimit2 ){
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Your search returned more than 50 results. Not all results are displayed below. Enter additional criteria to refine your search.'));
    }else if(noOfFAC >= resultLimit1 ){
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter additional criteria to refine your search.'));
    }
}catch(QueryException se){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,se.getMessage()));
}
    
} 

}