objects/Account.object
<CustomObject>
    <fields>
        <fullName>SGUID__c</fullName>
        <description>Unique Identifier from the Toyota and Lexus Web portal.
This will also be used as the SSO federation id.</description>
        <label>SGUID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseOutCome__c.object
<CustomObject>
    <fields>
        <fullName>CaseSubject__c</fullName>
        <description>Field to match against Case subject</description>
        <label>CaseSubject</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OutComeId__c</fullName>
        <externalId>true</externalId>
        <label>OutComeId</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutCome__c</fullName>
        <externalId>true</externalId>
        <label>OutCome</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CaseOutCome</label>
    <nameField>
        <displayFormat>COC-{000}</displayFormat>
        <label>CaseOutCome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseOutComes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SGUID__c</fullName>
        <description>Unique federation identifier provided by TFSWeb IDP</description>
        <externalId>true</externalId>
        <label>SGUID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Weblogin</fullName>
        <active>true</active>
        <description>Record type for customer community web login for TFS or LFS</description>
        <label>Weblogin</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weblogin_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Weblogin Contact stores the contact id of the weblogin register to this FinAcctCustomer Record.
Null if no Weblogin Contact is register.

Customer Community will allow weblogin customer to read this record</description>
        <label>Weblogin Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>WebLogin</fullName>
        <active>true</active>
        <description>PersonAccount to Enable Multiple Web Logins for a customer.  Will be used to enable Customer Community user</description>
        <label>Web Login</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_TestUtility.cls
@isTest(SeeAllData=false)
public class TFSC_TestUtility {

	public Financial_Account__c finAcct {get;private set;}
	public Financial_Account_Customer__c finAcctCust {get;private set;}
	public Account person {get;private set;}
	public Contact personContact {get;private set;}
	public User testAdmin {get;private set;}
	public User communityUser {get;private set;}
	public List<CaseOutCome__c> caseOutcomes {get;private set;}
	public List<Case> cases {get;private set;}
	public FeedItem feedItem {get;private set;}
	public CaseComment caseComment {get;private set;}

	public TFSC_TestUtility() {

		Profile tmccCustomerProfile = [select Id from Profile where Name = 'TMCC Customer Community Login User'];
		Profile sysAdminProfile = [select Id from Profile where Name = 'System Administrator'];
		UserRole sysAdminRole = [select Id from UserRole where Name = 'System Administration'];

		String SGUID = randomness().substring(0,10);

		//create a test admin, so that we can perform the next set of dml statements with it
		insert (this.testAdmin = newUser(sysAdminProfile.Id, sysAdminRole.Id));

		System.runAs(this.testAdmin) {
			//insert FA
			insert (this.finAcct = new Financial_Account__c(
				Financial_Account_Number__c = TFSC_TestUtils.generateRandomString(8)
			));
			
			//insert personAccount
			insert (this.person = new Account(
				RecordTypeId = Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer').getRecordTypeId(),
				SGUID__c = TFSC_TestUtils.generateRandomString(10),
				FirstName = 'Test',
				LastName = 'Person',
				Web_CompanyName__pc = 'Company Name',
				Web_UserId__pc = 'WebUserId',
				PersonEmail = 'email@example.test'
			));

			TFSC_CommunityAccountUtil autil = new TFSC_CommunityAccountUtil();

			//need to pull the associated contact that the system created
			//this.personContact = [
			//	select Id 
			//	from Contact 
			//	where Id in (
			//		select PersonContactId 
			//		from Account 
			//		where Id = :this.person.Id
			//	)
			//];
			insert (this.personContact = new Contact(
				LastName = 'Test',
				AccountId = autil.acctId,
				Email = 'test@abc.com',
				RecordTypeId = Contact.SObjectType.getDescribe().getRecordTypeInfosByName().get('Weblogin').getRecordtypeId(),
				SGUID__c = SGUID
			));

			insert (this.finAcctCust = new Financial_Account_Customer__c(
				Financial_Account__c = this.finAcct.Id,
				Account__c = this.person.Id,
				Name = 'FinAcctCust',
				Borrower_Status__c = 'TEST',
				Weblogin_Contact__c = this.personContact.Id
			));

			insert (this.caseOutcomes = new List<CaseOutCome__c> {
				newCaseOutcome('Subject'),
				newCaseOutcome('Default') 
			});

			//sample cases, one support request, one due date change request
			insert (this.cases = new List<Case>{
				newSupportRequest(this.finAcctCust.Id, this.person.Id),
				newDueDateChageRequest(this.finAcctCust.Id, this.person.Id)
			});

			insert (this.caseComment = new CaseComment (
				ParentId = this.cases[0].Id,
				CommentBody = 'CommentBody',
				IsPublished = true
			));

			insert (this.feedItem = new FeedItem(
				ParentId = this.cases[0].Id,
				ContentFileName = 'FeedItem',
				ContentData = Blob.valueOf('ContentData'),
				Body = 'Body'
			));

		}

		//build a community user 
		insert (this.communityUser = newUser(tmccCustomerProfile.Id, null, this.personContact.Id, SGUID));

	}

	private CaseOutCome__c newCaseOutcome(String subject) {
		return new CaseOutCome__c(
			CaseSubject__c = subject,
			OutCome__c = randomness().substring(0,10),
			OutComeId__c = randomness().substring(0,6)
		);
	}

	private User newUser(Id profileName, Id roleId) {
		return newUser(profileName, roleId, null, null);
	}

	private User newUser(String profileId, Id roleId, Id pcId, String fedId) {
		User newUser = new User(
			Alias = 'stst123', 
            Email='usr123@toyotaDevish.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = profileId, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='usr' + randomness().substring(0,5) + '@toyotaDevish.com',
            UserRoleId = roleId,
            ContactId = pcId,
            FederationIdentifier = fedId
        );

		return newUser;
	}

	private Case newSupportRequest(Id finAcctCustId, Id acctId) {
		return newCase(finAcctCustId, acctId, Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Support Request').getRecordTypeId());
	}

	private Case newDueDateChageRequest(Id finAcctCustId, Id acctId) {
		Case retCase = newCase(finAcctCustId, acctId, Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Due Date Change Request').getRecordTypeId());
		retCase.Subject = 'Due Date Change Request';
		retCase.Requested_Due_Date_Day_of_Month__c = '15';
		retCase.I_Agree_to_Terms_and_Conditions__c = true;
		return retCase;
	}

	private Case newCase(Id finAcctCustId, Id acctId, Id recTypeId) {
		return new Case(
			AccountId = acctId,
			RecordTypeId = recTypeId,
			Financial_Account_Customer__c = finAcctCustId,
			Status = 'New',
			Subject = 'Subject',
			Description = 'Description'
		);
	}

	private String randomness() {
		return EncodingUtil.convertToHex(Crypto.generateAesKey(128));
	}

}