objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>External ID:
Dealer: Dealership number
Branch: City State Zip</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region_Number__c</fullName>
        <description>Region number
Dealership region (Actual Region)</description>
        <label>Region Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>Record Type for Branch Account</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Accounts (Branch)</relationshipLabel>
        <relationshipName>Financial_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region_Number__c</fullName>
        <description>Region number</description>
        <label>Region Number</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_PaymentHistoryController.cls
public with sharing class TFSC_PaymentHistoryController {
    
    public Financial_Account__c contextFinancialAccount{get;set;}
    public List<TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_ResponseRecord> historyList{get;set;}
    
    
    public TFSC_PaymentHistoryController() {
        
        if(recordId != null) {
        	try {
                this.contextFinancialAccount = [ select id, Region_Number__c, Branch__r.Account_Number__c, RecordType.Name, Financial_Account_Number__c
                                                    from Financial_Account__c
                                                    where id = :recordId];
	        }
	        catch (Exception e) { }
        }
        if(this.contextFinancialAccount != null) {
        	getData();
        }
    }
    
    private String recordId {
    	get{
    		return ApexPages.currentPage().getParameters().get('recordId');
    	}
    }
    
    
    private void getData() {
    	 getAccountData();
    }
    
    private void getAccountData() {
    	//request = AccountNumber; AccountType; Branch; NoOfRecords; Region;
    	
    	String acctType = '';
    	if( !TFSC_Utils.isNullOrEmpty(contextFinancialAccount.RecordType.Name) ) {
    		acctType = contextFinancialAccount.RecordType.Name;
    		acctType = acctType.substring(0,1);
    	}
    	
    	String errorString = '';
    	//if( TFSC_Utils.isNullOrEmpty(acctType) ) {
    	//	errorString = 'Account Type is requred.';
    	//	return;
    	//}
    	
    	//AccountNumber = Financial_Account__c.Financial_Account_Number__c
		//AccountType = Financial_Account__c.RecordType.Name (first character)
		//Branch = Financial_Account__c.Branch__r.Account_Number__c
		//Region = Financial_Account__c.Region_Number__c
		if(errorString.length() == 0) {
	    	TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_RequestParams request;
	    	request = new TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_RequestParams();
	    	try {
		        request.AccountNumber = contextFinancialAccount.Financial_Account_Number__c;
		        request.AccountType = acctType;
		        request.Branch = '';
		        request.Region = '';
		        request.NoOfRecords = 30;
		        
		        errorString = executeWSFromRequestAndReturnError(request);
		        
	        }
	        catch (Exception e) {
	        	errorString = getErrorStringFromRequestAndException(e, request);
	        }
			
		}
		
		
        if(errorString.length() > 0) {
        	ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.ERROR, errorString); 
            ApexPages.addMessage(pageMsg);
        }
    }
    
    
    //wrapped in a try-catch already
    private String executeWSFromRequestAndReturnError(TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_RequestParams request) {
    	String strToReturn = '';
    	
    	TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_ResponseParams response;
        response = TFSC_WS_GetPaymentTransactionHistory.getPaymentTransactionHistory(request);
        
        if(response.ResponseRecordList != null) {
            historyList = response.ResponseRecordList;
        }
        
        if(response.StatusParams != null && response.StatusParams.Status.toUpperCase() == 'FAIL') {
            if(response.StatusParams.Error != null) {
            	strToReturn = response.StatusParams.Error;
            }else{
            	
            	strToReturn = 'Webservice Error.'; 
            }
        }
        
        return strToReturn;
    }
    
    
    //wrapped in a try-catch already
    private String getErrorStringFromRequestAndException(Exception e, TFSC_WS_GetPaymentTransactionHistory.PaymentTransactionHistory_RequestParams request) {
    	String errorString = e.getMessage();
        
        /*
        String tempBranch = 'null';
        if(request.Branch != null) {
            tempBranch = request.Branch;
        }
        String tempRegion = 'null';
        if(request.Region != null) {
            tempRegion = request.Region;
        }
        
        errorString += ';  request.AccountNumber = ' + request.AccountNumber;
        errorString += '; request.AccountType = ' + request.AccountType;
        errorString += '; request.Branch = ' + tempBranch;
        errorString += '; request.Region = ' + tempRegion;
        */
        
        return errorString;
    }
    
    
}