objects/Activity_Code__c.object
<CustomObject>
    <description>Business rules and process metadata associated with each available code applied to tasks.</description>
    <fields>
        <fullName>Flag_Quick__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Flag Quick</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_RPC__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Flag RPC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Skip__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Flag Skip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sort_Order_Quick__c</fullName>
        <description>Used to set the sort order for &quot;Quick&quot; activity codes</description>
        <label>Sort Order - Quick</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order_RPC__c</fullName>
        <description>Used to set the sort order for &quot;RPC&quot; activity codes</description>
        <label>Sort Order - RPC</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order_Skip__c</fullName>
        <description>Used to set the sort order for &quot;Skip&quot; activity codes</description>
        <label>Sort Order - Skip</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Activity Code</label>
    <nameField>
        <label>Activity Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ActivityCodeWrapper.cls
global class ActivityCodeWrapper implements Comparable {

	public Activity_Code__c activityCode;
    public String flagType;
    
    // Constructor
    public ActivityCodeWrapper(Activity_Code__c ac, String fType) {
        activityCode = ac;
        flagType = fType;
        
        System.debug('************** activity code: ' + activityCode + ' ~ flagType: ' + flagType);
    }
    
    // Compare code options based on the sort order.
    global Integer compareTo(Object compareTo) {
        // Cast argument to ActivityCodeWrapper
        ActivityCodeWrapper compareToActivityCode = (ActivityCodeWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if(flagType == 'Quick'){
           System.debug('************** Quick Activity Code sorting ~ Quick flag: ' + activityCode.Flag_Quick__c  + ' Sort order: ' + activityCode.Sort_Order_Quick__c);
           if (activityCode.Sort_Order_Quick__c > compareToActivityCode.activityCode.Sort_Order_Quick__c) {
                // Set return value to a positive value.
                returnValue = 1;
        	} else if (activityCode.Sort_Order_Quick__c < compareToActivityCode.activityCode.Sort_Order_Quick__c) {
                // Set return value to a negative value.
                returnValue = -1;
        	} 
    	}
        
        if(flagType == 'RPC'){
           System.debug('************** RPC Activity Code sorting ~ RPC flag: ' + activityCode.Flag_RPC__c + ' Sort order: ' + activityCode.Sort_Order_RPC__c);
           if (activityCode.Sort_Order_RPC__c > compareToActivityCode.activityCode.Sort_Order_RPC__c) {
                // Set return value to a positive value.
                returnValue = 1;
        	} else if (activityCode.Sort_Order_RPC__c < compareToActivityCode.activityCode.Sort_Order_RPC__c) {
                // Set return value to a negative value.
                returnValue = -1;
        	} 
    	}
        
        if(flagType == 'Skip'){
           System.debug('************** Skip Activity Code sorting ~ Skip flag: ' + activityCode.Flag_Skip__c  + ' Sort order: ' + activityCode.Sort_Order_Skip__c);
           if (activityCode.Sort_Order_Skip__c > compareToActivityCode.activityCode.Sort_Order_Skip__c) {
                // Set return value to a positive value.
                returnValue = 1;
        	} else if (activityCode.Sort_Order_Skip__c < compareToActivityCode.activityCode.Sort_Order_Skip__c) {
                // Set return value to a negative value.
                returnValue = -1;
        	} 
    	}
        
        System.debug('***************** returnValue:' + returnValue);
        return returnValue;       
    }    
    
}