objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Collection_Activity_Code__c</fullName>
        <label>Collection Activity Code</label>
        <picklist>
            <picklistValues>
                <fullName>Collection Activity Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CURE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Activity_Code__c.object
<CustomObject>
    <description>Business rules and process metadata associated with each available code applied to tasks.</description>
    <fields>
        <fullName>Collection_Activity_Code__c</fullName>
        <label>Collection Activity Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Activity Code</label>
    <nameField>
        <label>Activity Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Election_Overall_Consent__c</fullName>
        <label>Overall Consent</label>
        <picklist>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Election_Payment_Reminder_Day__c</fullName>
        <label>Payment Reminder Day</label>
        <picklist>
            <controllingField>Election_Overall_Consent__c</controllingField>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flag_Bankruptcy__c</fullName>
        <description>Bankruptcy Code</description>
        <label>Flag Bankruptcy</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_Invalid_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invalid Home Phone Number</description>
        <label>Home Phone Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_Invalid_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invalid Home Phone Number</description>
        <label>Home Phone Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Mobile_Phone_DNC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Mobile_Phone_Invalid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Phone Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_Invalid_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invalid Work Phone Number</description>
        <label>Work Phone Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_Invalid_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Invalid Work Phone Number</description>
        <label>Work Phone Invalid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Phone_No_Call_Reason_Code_BillTo__c</fullName>
        <label>Home Phone No-Call Reason Code BillTo</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_BillTo__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone_No_Call_Reason_Code__c</fullName>
        <label>Mobile Phone No-Call Reason Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone_No_Call_Reason_Code_Bill_To__c</fullName>
        <label>Work Phone No Call Reason Code Bill To</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FlowUtil.cls
/**
* @author       Mohan Chinnappan     
* @date         05/22/2014
* @description  
*   
*    Util class for Visual Flow - C&D
*/
public with sharing class FlowUtil {
    
     /**
     *  
     * @description:
     *      DNC and consent values for the given financialAccountNumber and borrowerPosition
       example: getDNCConsentData('UF6324', 'Primary')
     */

  public static Map<String,Boolean>  getDNCConsentData(String financialAccountNumber, String borrowerPosition )  {
    
      Map<String,Boolean> valueDNCMap = null;
      
      List<String> faIds = getFinancialAccountIds(financialAccountNumber);
      for (String faId : faIds) {
        List <Financial_Account_Customer__c>  facs = getFinancialAccountCustomers (faId);
        for (Financial_Account_Customer__c fac : facs) {
            if (fac.Borrower_Position__c != borrowerPosition)  continue;
            valueDNCMap = new Map<String,Boolean>();
            
            valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', false);
            valueDNCMap.put('Flag_Home_Phone_DNC_BillTo__c', false);
            valueDNCMap.put('Flag_Work_Phone_DNC_Garage__c', false);
            valueDNCMap.put('Flag_Work_Phone_DNC_BillTo__c', false);
            valueDNCMap.put('Flag_Mobile_Phone_DNC__c', false);
            valueDNCMap.put('Election_Overall_Consent__c', false);
            
            
            valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', fac.Flag_Home_Phone_DNC_Garage__c  == null ? false : fac.Flag_Home_Phone_DNC_Garage__c );
            valueDNCMap.put('Flag_Home_Phone_DNC_BillTo__c', fac.Flag_Home_Phone_DNC_BillTo__c == null  ? false : fac.Flag_Home_Phone_DNC_BillTo__c );
            valueDNCMap.put('Flag_Work_Phone_DNC_Garage__c', fac.Flag_Work_Phone_DNC_Garage__c == null  ? false : fac.Flag_Work_Phone_DNC_Garage__c);
            valueDNCMap.put('Flag_Work_Phone_DNC_BillTo__c', fac.Flag_Work_Phone_DNC_BillTo__c == null  ? false : fac.Flag_Work_Phone_DNC_BillTo__c );
            valueDNCMap.put('Flag_Mobile_Phone_DNC__c', fac.Flag_Mobile_Phone_DNC__c == null ? false : fac.Flag_Mobile_Phone_DNC__c );
            valueDNCMap.put('Election_Overall_Consent__c', fac.Election_Overall_Consent__c == null ? false : Boolean.valueOf(fac.Election_Overall_Consent__c) );
            
             
        }   
                
     }
     return valueDNCMap;
  }
   
     /**
     *  
     * @description:
     *      Get list of FinancialAccountIds for the given FinancialAccountNumber
       example: getFinancialAccountIds('UF6324')
     */
   
   public static List<String> getFinancialAccountIds (String financialAccountNumber ) {
    
        List<Financial_Account__c> fas =  [
            SELECT id, Financial_Account_Number__c
              FROM 
                Financial_Account__c
              WHERE
                 Financial_Account_Number__c = :financialAccountNumber
        ];
        
        List<String> ids = new List<String>();
        for (Financial_Account__c fa: fas) {
            ids.add(fa.id);
        }
        
        return ids;
 
   }
   
   
    /**
     *  
     * @description:
     *      the first FinancialAccountId for the given FinancialAccountNumber
       example: getFinancialAccountId('UF6324')
     */
   
   public static String getFinancialAccountId(String financialAccountNumber) {
        Financial_Account__c fa =  [
            SELECT id, Financial_Account_Number__c
              FROM 
                Financial_Account__c
              WHERE
                 Financial_Account_Number__c = :financialAccountNumber
              LIMIT 1
        ];
        
        return fa.Id;
   }
   
   
     /**
     *  
     * @description:
     *      Get list of FinancialAccountCustomers for the given FinancialAccountId
     */
   
   
   public static List <Financial_Account_Customer__c>  getFinancialAccountCustomers (String financialAccountId ) {
 
    List <Financial_Account_Customer__c> facs  = [
        SELECT 
               id
               ,Financial_Account_Customer__c 
               ,Borrower_Position__c
               ,Financial_Account__c
               ,Financial_Account__r.RecordType.Name
               ,Mailing_State_BillTo__c

               ,Work_Phone_No_Call_Reason_Code_Bill_To__c
               ,Home_Phone_No_Call_Reason_Code_BillTo__c
               ,Mobile_Phone_No_Call_Reason_Code__c

               ,Election_Overall_Consent__c
               ,Election_Payment_Reminder_Day__c

               ,Flag_Home_Phone_DNC_Garage__c
               ,Flag_Home_Phone_Invalid_Garage__c
               ,Flag_Home_Phone_DNC_BillTo__c
               ,Flag_Home_Phone_Invalid_BillTo__c

               ,Flag_Work_Phone_DNC_Garage__c
               ,Flag_Work_Phone_Invalid_Garage__c
               ,Flag_Work_Phone_DNC_BillTo__c
               ,Flag_Work_Phone_Invalid_BillTo__c

               ,Flag_Mobile_Phone_DNC__c
               ,Flag_Mobile_Phone_Invalid__c

               ,Flag_Bankruptcy__c
           FROM
             Financial_Account_Customer__c

           WHERE
             Financial_Account__c = :financialAccountId AND 
             Borrower_Position__c IN ('Primary','Co-X') AND 
             Borrower_Status__c = 'Active'
    ];
    
    return facs;
   }
   
   
   /**
     *  
     * @description:
     *      getFlagBankruptcy for : Primary or Co-X )
     *      setting valueConsent null (instead of 'No' or 'Yes' will skip updating for  Election_Overall_Consent__c
       Example:
         getFlagBankruptcy('UF6324','Primary')
            
     */
   
   public static String getFlagBankruptcy(String financialAccountId,String borrowerPosition) {                                       
        List <Financial_Account_Customer__c>  facs = getFinancialAccountCustomers (financialAccountId);
        if (facs != null) {
            for (Financial_Account_Customer__c fac : facs) {
                if (fac.Borrower_Position__c != borrowerPosition)  continue;
                return fac.Flag_Bankruptcy__c;
            }
        }

     return null;
     
   }
   /**
     *  
     * @description:
     *      updateFlagBankruptcy for : Primary or Co-X )
     *       
   */
            
   
   
    public static void updateFlagBankruptcy(String financialAccountNumber,String borrowerPosition, String bkValue) {                                       
     List<String> faIds = getFinancialAccountIds(financialAccountNumber);
     for (String faId : faIds) {
        List <Financial_Account_Customer__c>  facs = getFinancialAccountCustomers (faId);
        for (Financial_Account_Customer__c fac : facs) {
            if (fac.Borrower_Position__c == borrowerPosition) {
                fac.Flag_Bankruptcy__c = bkValue;
                update fac;
            }
        }
     }
     
     
   }
   
     /**
     *  
     * @description:
     *     Send email to given emailAddress with subject and body
       example: sendEmail('mchinnappan@salesforce.com', 'SUBJECT', 'BODY of the email');
     */
   
   public static void sendEmail(String emailAddress, String subject, String body)  {
         
      System.Debug('test');
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();  
       
      mail.setToAddresses(new String[] {emailAddress});  
      mail.setSubject(subject);  
      mail.setPlainTextBody(body);  
        
      Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });  
   }  
   
   
   
   
    /**
     *  
     * @description:
     *      get description for the given activity code
        Example: getActivityCodeDesc('DNC1');
        
             
     */
   
   
    public static String getActivityCodeDesc(String activityCode) {
        String description = null;
        
        List<Activity_Code__c> acs = [
          SELECT Name , Description__c 
           FROM 
                Activity_Code__c
          WHERE 
               Name =:activityCode       
        
        ];
        
        
        
         for (Activity_Code__c ac: acs) {
           description =+ ac.Name + ' - ' + ac.Description__c;
         }
         return description;
    }


   /**
     *  
     * @description:
     *      gets the caseId for the given financialAccountId
     *       
        Example: getCaseId('a03S00000030rb5IAA');
        
             
     */

public static String getCaseId(String financialAccountId) {

    List<Case> caseRec = [
    
       SELECT Id, isClosed , Financial_Account__c, RecordType.Name
         FROM 
         case
        WHERE
           RecordType.Name = 'Collection'  
             AND
           Financial_Account__c = :financialAccountId
             AND
           IsClosed = false
            
          LIMIT 1
    ];
    
    if (caseRec.size() == 1) return caseRec[0].Id;
    else  return null; //TODO: CHECK THIS
    

}


 /**
     *  
     * @description:
     *     prepares DNC Map for the given input String
        
     */  
   
   public static  Map<String, Boolean> getDNCMap(String input) {
      List<String> recs = input.split(',');
      
        // {!Home_PhoneB},{!Work_PhoneB},{!Mobile_PhoneB},{!Home_Phone_BBilling},{!Work_Phone_BBilling} :
        // {!Home_PhoneCOB},{!Work_PhoneCOB}{!Mobile_PhoneCOB},{!Home_phone_COB_Billing},{!Work_Phone_COB_Billing}
        Map<String,Boolean> valueDNCMap = new Map<String, Boolean>();
        valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', false);
        valueDNCMap.put('Flag_Home_Phone_DNC_BillTo__c', false);
        valueDNCMap.put('Flag_Work_Phone_DNC_Garage__c', false);
        valueDNCMap.put('Flag_Work_Phone_DNC_BillTo__c', false);
        valueDNCMap.put('Flag_Mobile_Phone_DNC__c', false);
        
      Integer loc = 0;
      for (String rec: recs) {
        if (0 == loc && null != rec && 'true' == rec) {
            valueDNCMap.put('Flag_Home_Phone_DNC_Garage__c', true);
        }
        if (1 == loc && null != rec && 'true' == rec) {
            valueDNCMap.put('Flag_Work_Phone_DNC_Garage__c', true);
        }
        if (2 == loc && null != rec && 'true' == rec) {
            valueDNCMap.put('Flag_Mobile_Phone_DNC__c', true);
        }
        if (3 == loc && null != rec && 'true' == rec) {
            valueDNCMap.put('Flag_Home_Phone_DNC_BillTo__c', true);
        }
        if (4 == loc && null != rec && 'true' == rec) {
            valueDNCMap.put('Flag_Work_Phone_DNC_BillTo__c', true);
        }
        loc++;
      }
      
      return valueDNCMap;
   }

   /**
     *  
     * @description:
     *     returns the DNC String for Task.Description update
     *       
        
        
             
     */




public static String getDNCStr(String vDNCActionDetails ) {
    
        Map<String,Boolean> valueDNCMapB = null;
        Map<String,Boolean> valueDNCMapCOB = null;
         
        List<String> vDNCActionDetailsRecs = vDNCActionDetails.split(':');
        Integer loc = 0;
        for (String crec : vDNCActionDetailsRecs) {
            if (0 == loc && null != crec) valueDNCMapB = getDNCMap(crec);
            if (1 == loc && null != crec) valueDNCMapCOB =  getDNCMap(crec);
            
            loc++;
        }
        
        String dncStr = '';
        if ( valueDNCMapB.get('Flag_Home_Phone_DNC_Garage__c') ) dncStr += 'CS-G-Home, ';
        if ( valueDNCMapB.get('Flag_Work_Phone_DNC_Garage__c') ) dncStr += 'CS-G-Work, ';
        if ( valueDNCMapB.get('Flag_Mobile_Phone_DNC__c') ) dncStr += 'CS-G-Cell, ';
        if ( valueDNCMapB.get('Flag_Home_Phone_DNC_BillTo__c') ) dncStr += 'CS-B-Home, ';
        if ( valueDNCMapB.get('Flag_Work_Phone_DNC_BillTo__c') ) dncStr += 'CS-B-Work, ';
        
        
        if ( valueDNCMapCOB.get('Flag_Home_Phone_DNC_Garage__c') ) dncStr += 'CX-G-Home,' ;
        if ( valueDNCMapCOB.get('Flag_Work_Phone_DNC_Garage__c') ) dncStr += 'CX-G-Work, ';
        if ( valueDNCMapCOB.get('Flag_Mobile_Phone_DNC__c') ) dncStr += 'CX-G-Cell, ';
        if ( valueDNCMapCOB.get('Flag_Home_Phone_DNC_BillTo__c') ) dncStr += 'CX-B-Home, ';
        if ( valueDNCMapCOB.get('Flag_Work_Phone_DNC_BillTo__c') ) dncStr += 'CX-B-Work, ';
        
        return dncStr;
}


   
   /**
     *  
     * @description:
     *      inserts the given activityCode   for the given FinancialAccountNumber
     *      setting valueConsent null will skip updating for  Election_Overall_Consent__c
        Example: 
        
             
     */
   public static void insertActivityCodeInTask(String financialAccountNumber, String financialAccountId,
               String activityCode, String codeDescription, String whatId,
               String statusStr, String taskDesc) {
    
    
    /*
    Task.Subject = CODE - Code Description (from Activity_Code__c.Name & " - " & Activity_Code__c.Description__c)
    Task.WhatId = Id from Case where RecordType.Name = 'Collection' and Financial_Account__c = current FA Id and IsClosed = False limit 1
    Task.Collection_Activity_Code__c = selected Activity Code
    Task.Financial_Account__c = current FA Id
    Task.Financial_Account_Number__c = current FA #
    Task.Status = 'Completed'
    Task.ActivityDate = current date
    
    
    Result:
    
    2:55.344 (344344099)|USER_DEBUG|[11]|DEBUG|Task:
     {
       Status=Completed, 
       Financial_Account_Number__c=UF6324, 
       WhatId=500S0000004LUKWIA4, 
       Subject=PBNK - PENDING BANKRUPTCY,
       Id=00TS000000Od46WMAR, 
       Collection_Activity_Code__c=PBNK, 
       Financial_Account__c=a03S00000030rb5IAA, 
       ActivityDate=2014-05-26 00:00:00
      }
      
      

   */ 
   
   if (null == whatId) {
    Task newTask = new Task(
                  //Subject = activityCode + ' - '  + codeDescription,
                  Subject =  codeDescription,
                  //WhatId = whatId,
                  Financial_Account__c = financialAccountId,
                  Financial_Account_Number__c = financialAccountNumber,
                  Status = statusStr,
                  Collection_Activity_Code__c = activityCode,
                  Description = taskDesc,
                  ActivityDate = Date.today()
             );
     insert newTask;
   } else {
    Task newTask = new Task(
                  //Subject = activityCode + ' - '  + codeDescription,
                  Subject =  codeDescription,
                  WhatId = whatId,
                  Financial_Account__c = financialAccountId,
                  Financial_Account_Number__c = financialAccountNumber,
                  Status = statusStr,
                  Collection_Activity_Code__c = activityCode,
                  Description = taskDesc,
                  ActivityDate = Date.today()
             );
     insert newTask;
    
   }
    
   }
   
   
   

}