objects/Activity_Code__c.object
<CustomObject>
    <description>Business rules and process metadata associated with each available code applied to tasks.</description>
    <fields>
        <fullName>CTI_Activity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CTI Activity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CTI_Reason__c</fullName>
        <label>CTI Reason</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTI_Result__c</fullName>
        <label>CTI Result</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Activity_Code__c</fullName>
        <label>Collection Activity Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Activity Code</label>
    <nameField>
        <label>Activity Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Code</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Name__c</fullName>
        <label>Model Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Charges_Late__c</fullName>
        <description>Late charges</description>
        <label>Late Charge Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charges_Miscellaneous__c</fullName>
        <description>Miscellaneous Charges</description>
        <label>Miscellaneous Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Coll_Num_Months_Past_Due__c</fullName>
        <label>Number of Payments Past Due</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_Counter_Fifteen_Days_Past_Due__c</fullName>
        <label>History Counter Fifteen Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>History_Counter_Ninety_Days_Past_Due__c</fullName>
        <label>History Counter Ninety Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>History_Counter_Non_Sufficient_Funds__c</fullName>
        <label>Reversed Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>History_Counter_SixtyDaysPastDue__c</fullName>
        <label>History Counter SixtyDaysPastDue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>History_Counter_Thirty_Days_PastDue__c</fullName>
        <label>History Counter Thirty Days PastDue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partial_Payment_Option__c</fullName>
        <formula>IF(Coll_Num_Months_Past_Due__c &gt; 1, Payment_Amount_Past_Due__c - (Payment_Amount_Scheduled__c * (Coll_Num_Months_Past_Due__c - 1)), 0)</formula>
        <label>Partial Payment Option</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Due_Charges__c</fullName>
        <formula>Payment_Amount_Past_Due__c + Charges_Late__c + Charges_Miscellaneous__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Past Due + Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Last__c</fullName>
        <description>last payment amount</description>
        <label>Last Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Past_Due__c</fullName>
        <description>Past due amount</description>
        <label>Past Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Scheduled__c</fullName>
        <description>Payment Amount</description>
        <label>Scheduled Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date_Last__c</fullName>
        <description>last payment date</description>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Date_Past_Due__c</fullName>
        <description>Past due date</description>
        <label>Past Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Due__c</fullName>
        <formula>Payment_Amount_Past_Due__c + Charges_Late__c + Charges_Miscellaneous__c +

IF(
  AND(
    RecordType.Name = &quot;Retail&quot;,
    Payment_Date_Past_Due__c &lt; TODAY(),
    TODAY() &lt; Maturity_Date__c,
    VALUE(History_Counter_Days_Past_Due__c) &gt;= 1
  ),

  Payment_Amount_Scheduled__c,

  IF(RecordType.Name = &quot;Lease&quot; &amp;&amp; Payment_Date_Past_Due__c &lt; TODAY(), Payment_Amount_Scheduled__c, 0)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Guaranty__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Picklist for user to indicate whether a dealer guarantee was written into the contract.</description>
        <label>Dealer Guaranty</label>
        <picklist>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IRepo_VendorName__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 TIBCO Pull
Trans: N
BU: RL
FD: Name of the forwarding vendor used to process the repossession. Not actively used in RL process but available for reference.</description>
        <label>iRepo Vendor Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Repo_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Date of the repossession at the place of repossession. Since date/time is received in GMT, date must be converted to a local date and stored here. Handled within the RL Set State Conditions Flow and associated date/time Apex plug-in.</description>
        <label>Local Repo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Modify_REPO_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Indicates when the next usage of the REPO activity code in the activity entry panel should include a modified generated note focused on highlighting the legal sale date change. Set by letter generation code upon regeneration and unset once the REPO activity note is saved.</description>
        <label>Modify REPO Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposed_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The earliest date by which TFS may sell a repossessed vehicle. Calculated date based upon the proposed notice date and adding days as defined in the related form rule record.</description>
        <label>Proposed Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recorded_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Updated from proposed legal sale date when rights letter is generated. Will reflect the date from the latest generated notice.</description>
        <label>Recorded Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contracts__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Picklist for user to indicate whether there are any additional service contracts / insurance products sold with the vehicle which may drive refunds to the customer.</description>
        <label>Service Contracts</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_InteractionEntryPanelController.cls
global with sharing class RL_InteractionEntryPanelController {
    
    
    public Case contextCase{get;set;}
    public Financial_Account__c contextFinancialAccount{get;set;}
    public Repossession__c contextRepo{get;set;}
    
    public String selectedActivityCodeFromJs{get;set;}
    public String selectedCodeCtiEnabled{get;set;}
    
    public String legalSaleDate {
        get{
            String strToReturn = '';
            if(contextRepo != null && contextRepo.Recorded_Legal_Sale_Date__c != null) {
                if(contextRepo.Recorded_Legal_Sale_Date__c.month() < 10) {
                    strToReturn += '0';
                }
                strToReturn += String.valueOf(contextRepo.Recorded_Legal_Sale_Date__c.month());
                strToReturn += '/';
                if(contextRepo.Recorded_Legal_Sale_Date__c.day() < 10) {
                    strToReturn += '0';
                }
                strToReturn += String.valueOf(contextRepo.Recorded_Legal_Sale_Date__c.day());
                strToReturn += '/';
                strToReturn += String.valueOf(contextRepo.Recorded_Legal_Sale_Date__c.year());
            }
            return strToReturn;
        }
    }
    
    @RemoteAction
    global static RL_WS_TaxServiceExecution.TaxService_ResponseParams tempURCallout() {
        RL_WS_TaxServiceExecution.TaxService_ResponseParams objToReturn;
        objToReturn = RL_WS_TaxServiceExecution.testService();
        return objToReturn;
    }
    
    
    public RL_InteractionEntryPanelController(ApexPages.StandardController stdController) {
        
        populateContextCase(stdController);
        
        initData();
    }
    
    
    private void initData() {
        
        if(contextCase != null) {
            
            if(contextCase.Financial_Account__c != null) {
                populateContextFA(contextCase.Financial_Account__c);
            }else if(contextCase.Parent.Financial_Account__c != null){
                populateContextFA(contextCase.Parent.Financial_Account__c);
            }else if(contextCase.Parent.Parent.Financial_Account__c != null){
                populateContextFA(contextCase.Parent.Parent.Financial_Account__c);
            }
            
            if(contextFinancialAccount != null) {
                populateCorrectTopAndBottomFACs();
            }
            
            populateContextRepo();
            
        }
    }
    
    
    private void populateContextCase(ApexPages.StandardController stdController) {
        
        try{
            Case caseObj = (Case)stdController.getRecord();
            if(caseObj != null) {
                contextCase = [select id, Financial_Account__c, ParentId, Parent.Financial_Account__c, Parent.Parent.Financial_Account__c
                                from Case 
                                where id = :caseObj.Id] ;
            }
        }catch(Exception e) {
            appendErrorMessage(e.getMessage());
        }
        
    }
    
    private void populateContextFA(Id financialAccountId) {
        try {
            contextFinancialAccount = [select id, Name, Past_Due_Charges__c, Payment_Amount_Past_Due__c, Charges_Late__c,
                                    RecordType.Name, Financial_Account_Number__c,
                                    Charges_Miscellaneous__c, Payment_Amount_Scheduled__c, Partial_Payment_Option__c,
                                    Coll_Num_Months_Past_Due__c,
                                    History_Counter_Fifteen_Days_Past_Due__c, History_Counter_Thirty_Days_PastDue__c,
                                    History_Counter_SixtyDaysPastDue__c, History_Counter_Days_Past_Due__c,
                                    Payment_Date_Past_Due__c, Total_Amount_Due__c, 
                                    History_Counter_Ninety_Days_Past_Due__c, Payment_Date_Last__c, Payment_Amount_Last__c,
                                    History_Counter_Non_Sufficient_Funds__c,
                                    Collateral__c, Collateral__r.Model_Year__c, Collateral__r.Make__c, Collateral__r.Model_Name__c,
                                    Collateral__r.Vehicle_Identification_Number__c
                                from Financial_Account__c
                                where id = :financialAccountId];
                                //(select Id, Model_Year__c, Make__c, Model_Name__c
                                    //from Assets)
        }
        catch (Exception e) {
            appendErrorMessage('Financial Account record not found.');
        }
    }
    
    
    private void populateCorrectTopAndBottomFACs() {
        
    }
    
    
    private void populateContextRepo() {
        Boolean errorHit = false;
        String errorMessage = '';
        try {
        	populateContextRepoNestedInTryCatch(contextCase.Id);
        }catch (Exception e) {
            errorHit = true;
            errorMessage = 'No repossession record related to this case.'; 
        }
        
        if(errorHit == true && contextCase.ParentId != null) {
             try {
				populateContextRepoNestedInTryCatch(contextCase.ParentId);
                errorHit = false;
            }catch (Exception e) {
                errorHit = true;
                errorMessage = 'No repossession record related to this case.'; 
            }
        }
        
        if(errorHit == true && contextCase.Parent.ParentId != null) {
             try {
                populateContextRepoNestedInTryCatch(contextCase.Parent.ParentId);
                errorHit = false;
            }catch (Exception e) {
                errorHit = true;
                errorMessage = 'No repossession record related to this case.'; 
            }
        }
        
        if(errorHit) {
            appendErrorMessage(errorMessage);
        }
        
    }
    
    private void populateContextRepoNestedInTryCatch(Id caseId) {
    	contextRepo = [select id, name, Local_Repo_Date__c, IRepo_VendorName__c, Proposed_Legal_Sale_Date__c,
                            Dealer_Guaranty__c, Service_Contracts__c, Modify_REPO_Note__c,
                            Recorded_Legal_Sale_Date__c
                        from Repossession__c
                        where Case__c = :caseId
                        limit 1];
    }
    
    
    
    
    private void appendErrorMessage(String errorMessage) {
        ApexPages.Message apexPageMessage = new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage);
        ApexPages.addMessage(apexPageMessage);
    }
    
    public PageReference updateModifyRepoNote() {
        try {
            update contextRepo;
        }catch(Exception e) {
            appendErrorMessage(e.getMessage());
        }
        
        return null;
    }
    
    public PageReference getLatestFormData() {
        initData();
        
        selectedCodeCtiEnabled = '';
        
        if(selectedActivityCodeFromJs != null && selectedActivityCodeFromJs != '' && selectedActivityCodeFromJs != 'None') {
            try{
                Activity_Code__c activityCode = [SELECT Id, Name, Description__c, Collection_Activity_Code__c, 
                                                           CTI_Reason__c, CTI_Result__c, CTI_Activity__c
                                                         From Activity_Code__c
                                                         WHERE Name = :selectedActivityCodeFromJs ];
                if(activityCode.CTI_Activity__c == true) {
                    selectedCodeCtiEnabled = 'Yes';
                }
            }catch(Exception e) {
            }
        }
        
        return null;
    }
    
    
}