objects/ArticlePDF__c.object
<CustomObject>
    <description>Article Depot
Compliance Requirement 
Store all versions of knowledge articles 
as well as PDF</description>
    <fields>
        <fullName>ArticlePdfContentVersionId__c</fullName>
        <label>ArticlePdfContentVersionId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrginalArticleVersionId__c</fullName>
        <description>OrginalArticleVersionId__c - cannot use related to</description>
        <label>OrginalArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Articles Depot</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Articles Depot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Depot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Binder__c.object
<CustomObject>
    <description>Compliance Requirement 
Collection of Knowledge Management Articles or Contents to be printed as PDF.

Rally US504</description>
    <label>Binder</label>
    <nameField>
        <label>Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BinderPage__c.object
<CustomObject>
    <description>Compliance Requirement 
Detail Record of a binder</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>BinderPages</relationshipLabel>
        <relationshipName>BinderPages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageRef__c</fullName>
        <label>Page Ref</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageType__c</fullName>
        <label>PageType</label>
        <picklist>
            <picklistValues>
                <fullName>KM Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce File</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>articleDepotId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Articles Depot</label>
        <referenceTo>ArticlePDF__c</referenceTo>
        <relationshipLabel>BinderPages</relationshipLabel>
        <relationshipName>BinderPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sequence__c</fullName>
        <label>sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BinderPage</label>
    <nameField>
        <displayFormat>BPN-{00000000}</displayFormat>
        <label>BinderPage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BinderPages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KB_App_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KB App Settings</label>
</CustomObject>

objects/PrintJob__c.object
<CustomObject>
    <description>Compliance Requirement
To keep track of the final URL of the merged PDF document.  Merged version of Article PDFs and Desk Guide PDFs.</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>PrintJobs</relationshipLabel>
        <relationshipName>PrintJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OutputLink__c</fullName>
        <label>Output Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>Now()</defaultValue>
        <label>StartTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PrintJob</label>
    <nameField>
        <displayFormat>PJ-{0000000}</displayFormat>
        <label>PrintJob Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrintJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KmPrintWebService.cls
/*

@httpPost - update status of printjob, optionally return 
@httpPatch - update final output link

*/

@RestResource(urlMapping='/KmPrintWebService/v1/*')
global class KmPrintWebService {
	
	@httpPost
	global Static KmPrintWebServieReply post (string printJobName, string status, boolean returnPages, integer startPage, integer pageCount) {
	  	
	  	List<PrintJob__c> printJobs = [
	  		select Binder__c, Binder__r.name, EndTime__c, OutputLink__c, StartTime__c, Status__c, name, id
	  		from PrintJob__c 
	  		where Name = :printJobName
	  	];
	  	
	  	KmPrintWebServieReply reply = new KmPrintWebServieReply();
	  	reply.printJobName = printJobName;
	  	if ( printJobs.size() == 0) {
	  		reply.message = 'cannot locate printjob : '+ printJobName;
	  		return reply;
	  	}
	  	
	  	
  		PrintJob__c printJob = printJobs[0];
  		reply.binderName = printJob.Binder__r.name;
  		reply.binderId = printJob.Binder__c;
  		reply.printJobName = printJob.name;
  		reply.printJobId = printJob.id;
  		reply.userName = UserInfo.getFirstName() + '.' + UserInfo.getLastName();
  		reply.totalBinderPageCount = 0;
	  	
	  	reply.basedir = '';
	  	KB_App_Settings__c kmEnginePrintBinderBaseDir = KB_App_Settings__c.getInstance('kmEnginePrintBinderBaseDir');
	  	if (kmEnginePrintBinderBaseDir != null ) {
	  		reply.basedir = kmEnginePrintBinderBaseDir.Value__c;
	  	}
	  	
	  	reply.kmEngineReadBinderURL = '';
	  	KB_App_Settings__c kmEngineReadBinderURL = KB_App_Settings__c.getInstance('kmEngineReadBinderURL');
	  	if (kmEngineReadBinderURL != null ) {
	  		reply.kmEngineReadBinderURL = kmEngineReadBinderURL.Value__c;
	  	}
	  	
	  	//update status if necessary
	  	if (status <> null && status.length() > 0) {
	  		printJob.Status__c = status;
	  		update printJob;
	  	}
	  	
	  	//get details if necessary
	  	if ( returnpages ) {
	  		List<BinderPage__c> pages = [
	  			select sequence__c, PageRef__c, articleDepotId__c, articleDepotId__r.ArticlePdfContentVersionId__c, pageType__c
	  			from BinderPage__c
	  			where Binder__c = :printJob.Binder__c
	  			order by sequence__c
	  		];
	  		
	  		if ( pages.size() > 0 ){
	  			reply.totalBinderPageCount = pages.size();
	  			reply.details = new List<KmPrintWebServiceReplyDetail>();
	  			for(BinderPage__c page : pages) {
	  				KmPrintWebServiceReplyDetail detail = new KmPrintWebServiceReplyDetail(page);  
	  				reply.details.add(detail);
	  			}
	  			
	  			//now add the articleDepotId and articleContentVersionId
	  		}
	  	}
	 
		return reply;
	} 
  
	
	@httpPatch
	global Static void patch (string printJobName, string outputURL, string title) {	  
		List<PrintJob__c> printJobs = [
	  		select EndTime__c, OutputLink__c, Status__c, Title__c
	  		from PrintJob__c 
	  		where Name = :printJobName
	  	];
	  	if ( printJobs.size() == 0) {
	  		System.Debug('KmPrintWebService::patch - cannot locate printjob : '+ printJobName) ;
	  		return;
	  	}
	  	
	  	PrintJob__c printJob = printJobs[0];
  		printJob.OutputLink__c = outputURL;
  		printJob.Status__c = 'Completed';
  		printJob.EndTime__c = DateTime.Now();
  		printJob.Title__c = title;
	  	
	  	update printJob;
	  	
		return;
	} 	

	
	///////////////////////////////////////////////////////////////
	
	global class KmPrintWebServieReply {
	
		public string binderName;
		public string binderId;
		public string printJobName;
		public string printJobId;
		public string userName;
		public integer totalBinderPageCount;
		public string kmEngineReadBinderURL;
		public string basedir;
		
		public string message;
	
		public List<KmPrintWebServiceReplyDetail> details;	
		
		public KmPrintWebServieReply() {
			totalBinderPageCount = 0;
			message = '';
			details = new List<KmPrintWebServiceReplyDetail>();
		}
	}  

	public class KmPrintWebServiceReplyDetail {
	
		public Integer seq;
		public String ref;  //OrginalArticleVersionId__c
		public String articleDepotId;
		public String articlePdfContentVersionId;
		public String pageType;
		
		public KmPrintWebServiceReplyDetail(BinderPage__c page) {
			this.seq = Integer.valueOf(page.sequence__c);
			this.ref = page.PageRef__c;
			this.articleDepotId = page.articleDepotId__c;
			if (page.articleDepotId__c <> null ) {
				this.articlePdfContentVersionId = page.articleDepotId__r.ArticlePdfContentVersionId__c;
			}
			this.pageType = page.PageType__c;
		}
	}
	
  
}