objects/ArticlePDF__c.object
<CustomObject>
    <description>Article Depot
Compliance Requirement 
Store all versions of knowledge articles 
as well as PDF</description>
    <fields>
        <fullName>ArticleNumVersion__c</fullName>
        <externalId>true</externalId>
        <label>ArticleNumVersion</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticlePdfContentVersionId__c</fullName>
        <label>ArticlePdfContentVersionId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstPublishedDate__c</fullName>
        <label>First Published Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OrginalArticleId__c</fullName>
        <description>cannot create relationship since articles will come from many article type tables</description>
        <label>OrginalArticleId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrginalArticleVersionId__c</fullName>
        <description>OrginalArticleVersionId__c - cannot use related to</description>
        <label>OrginalArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublishStatus__c</fullName>
        <label>Publish Status</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <label>Version Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Articles Depot</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Articles Depot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Depot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ArticlePdfTriggerTest.cls
@IsTest
public with sharing class ArticlePdfTriggerTest {

	@IsTest
	public static void unitTest() {
		ContentVersion cv = new ContentVersion();
		cv.Title = 'test content';
		cv.PathOnClient = '/tmp/testContent.docx';
		cv.VersionData = EncodingUtil.base64Decode('asdfasdfasdfasdfasdfadsfdas');
		insert cv;
		
		ArticlePDF__c aPdf = new ArticlePDF__c();
		aPdf.ArticleNumVersion__c = 'adfsad';
		aPdf.ArticleType__c='dfasd';
		aPdf.Article_Number__c='1234';
		aPdf.FirstPublishedDate__c=Date.Today();
		aPdf.OrginalArticleId__c='123123123';
		aPdf.OrginalArticleVersionId__c='123123';
		aPdf.PublishStatus__c='Online';
		aPdf.Title__c='asdfasafsdf';
		aPdf.VersionNumber__c = 4;
		
		
		insert aPdf;
		
		aPdf.ArticlePdfContentVersionId__c = cv.id;
		update aPdf;
		
		
	}

}