objects/ArticlePDF__c.object
<CustomObject>
    <description>Article Depot
Compliance Requirement 
Store all versions of knowledge articles 
as well as PDF</description>
    <label>Articles Depot</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Articles Depot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Depot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Binder__c.object
<CustomObject>
    <description>Compliance Requirement 
Collection of Knowledge Management Articles or Contents to be printed as PDF.

Rally US504</description>
    <label>Binder</label>
    <nameField>
        <label>Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BinderPage__c.object
<CustomObject>
    <description>Compliance Requirement 
Detail Record of a binder</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>BinderPages</relationshipLabel>
        <relationshipName>BinderPages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BinderPage</label>
    <nameField>
        <displayFormat>BPN-{00000000}</displayFormat>
        <label>BinderPage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BinderPages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FAQ_A__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>FAQ</label>
    <pluralLabel>FAQs</pluralLabel>
</CustomObject>

objects/LinkValidation__c.object
<CustomObject>
    <description>A list of links from Articles for the LinkValidation Engine to process</description>
    <fields>
        <fullName>Article_Type_Label__c</fullName>
        <label>Article Type</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_Type__c</fullName>
        <label>Link Type</label>
        <picklist>
            <picklistValues>
                <fullName>Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SF Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intranet Doc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ValidateLink</label>
    <nameField>
        <displayFormat>LB-{00000000}</displayFormat>
        <label>LinkValidation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ValidateLinks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrintJob__c.object
<CustomObject>
    <description>Compliance Requirement
To keep track of the final URL of the merged PDF document.  Merged version of Article PDFs and Desk Guide PDFs.</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>PrintJobs</relationshipLabel>
        <relationshipName>PrintJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PrintJob</label>
    <nameField>
        <displayFormat>PJ-{0000000}</displayFormat>
        <label>PrintJob Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrintJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KmWebServicesTest.cls
@IsTest
public class KmWebServicesTest {

	@IsTest
	public static void KmArticleWebServiceTest() {

		KmArticleTypeTest.createTestData();
		string articleType = 'FAQ_A__kav';
		string publishStatus = 'Online';
		string  articleRef = '1234';
		
		
		KmArticleWebService.KmArticleWebServiceReply reply = KmArticleWebService.post(articleType, articleRef, publishStatus);
		
		//this is unit test - this statement will not delete data
		KmArticleWebService.deleteAllArticleDepotPdf();
	}

	@IsTest
	public static void TestKmArticleWebServiceReply() {  
		
		ArticlePDF__c a = new ArticlePDF__c();
		KmArticleWebService.KmArticleWebServiceReply reply = new KmArticleWebService.KmArticleWebServiceReply(a);
	}   


	@IsTest
	public static void EchoWebServiceTest() {
		string msg = 'Hello World';
		System.assertEquals(msg, EchoWebService.post(msg));
	}

	@IsTest(SeeAllData=true)
	public static void KmArticleDepotWebServiceTest() {
		KmArticleDepotWebService.KmArticleDepotReply reply = KmArticleDepotWebService.post();
		System.AssertNotEquals(null, reply);
	}
	
  
	@IsTest
	public static void KmPrintWebServiceTest() {
		
		id binderId = PrintWebServiceCreateData();
		
		//then create the printjob
		PrintJob__c pj = new PrintJob__c();
		pj.binder__c = binderId;
		insert pj;
		
		pj = [select name from PrintJob__c where id = :pj.id];
		System.assertNotEquals(null, pj.name);
		
		KmPrintWebService.post(pj.name, 'Online', true, 0, 0);
		KmPrintWebService.patch(pj.name,'outputURL','This is the title');
	}

	public static id PrintWebServiceCreateData() {
		//create the binder
		Binder__c binder = new Binder__c();	
		insert binder;
		
		//now insert the page
		List<BinderPage__c> pages = new List<BinderPage__c>();
		return binder.id;
	}
	
	
	@IsTest
	public static void TestKmPrintWebServiceReplyDetail() {
		BinderPage__c page = new BinderPage__c();
		
		KmPrintWebService.KmPrintWebServiceReplyDetail detail = new KmPrintWebService.KmPrintWebServiceReplyDetail(page);
	}
	
	


	@IsTest
	public static void KmValidateLinksWebServiceTest() {
		
		ValidateLinkCreateData();
		
		KmValidateLinksWebService.KmValidateLinksWebServieReply postReply = KmValidateLinksWebService.post();
		System.AssertNotEquals(null,postReply);
		
		List<String> brokenLinkIds = new List<String>();
		List<String> connectionRefusedIds = new List<String>();
		for(KmValidateLinksWebService.KmValidateLinksWebServieReplyDetail detail : postReply.details) {
			if ( connectionRefusedIds.size() == 0) {
				connectionRefusedIds.add(detail.validateLinkId);
			} else {
				brokenLinkIds.add(detail.validateLinkId);
			}
		}
		
		
		KmValidateLinksWebService.patch(brokenLinkIds,connectionRefusedIds);
	
	}
	
	public static void ValidateLinkCreateData() {
		List<LinkValidation__c > lvSet = new List<LinkValidation__c >();
		
		ValidateLinkCreateDataDetails(lvSet,'Internet','test1','http://www.google.com');
		ValidateLinkCreateDataDetails(lvSet,'SF Document','test2','http://www.google.com');
		
		insert lvSet;
	}
	
	private static void ValidateLinkCreateDataDetails(List<LinkValidation__c > lvSet, String LinkType, String LinkLabel, String link) {
		LinkValidation__c lv = new LinkValidation__c();
		lv.Link_Type__c = LinkType;
		lv.Article_Type_Label__c = LinkLabel;
		lv.Link__c = link;
		lvSet.add(lv);	
	}
	
	
}