objects/ArticlePDF__c.object
<CustomObject>
    <description>Article Depot
Compliance Requirement 
Store all versions of knowledge articles 
as well as PDF</description>
    <fields>
        <fullName>ArticleCreatedBy__c</fullName>
        <label>ArticleCreatedBy</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleCreatedDate__c</fullName>
        <label>ArticleCreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ArticleLastModifiedBy__c</fullName>
        <label>ArticleLastModifiedBy</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleLastModifiedDate__c</fullName>
        <label>ArticleLastModifiedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ArticlePdfContentVersionId__c</fullName>
        <label>ArticlePdfContentVersionId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleTypeAPI__c</fullName>
        <label>ArticleTypeAPI</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DM_Forms__c</fullName>
        <label>DM Form #</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Department_Role__c</fullName>
        <label>Department Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FOPP_Text__c</fullName>
        <label>FOPP Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KnowledgeContainerName__c</fullName>
        <label>Knowledge Container</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Container</label>
        <referenceTo>KnowledgeContainer__c</referenceTo>
        <relationshipLabel>Article Depot</relationshipLabel>
        <relationshipName>Article_PDFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrginalArticleId__c</fullName>
        <description>cannot create relationship since articles will come from many article type tables</description>
        <label>OrginalArticleId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrginalArticleVersionId__c</fullName>
        <description>OrginalArticleVersionId__c - cannot use related to</description>
        <label>OrginalArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublishStatus__c</fullName>
        <label>Publish Status</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublishedDate__c</fullName>
        <description>Published Date = Version Published Date</description>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UrlName__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <label>Version Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Articles Depot</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Articles Depot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Depot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KnowledgeContainer__c.object
<CustomObject>
    <label>Knowledge Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KmArticleWebService.cls
/*

@httpPost - get the KM Article

*/

@RestResource(urlMapping='/KmArticleWebService/v1/*')
global class KmArticleWebService {
	
	@httpPost
	global Static KmArticleWebServiceReply post (string articleType, string articleRef, string publishStatus) {
	  	 
	  	System.debug('*** KmArticleWebService::post '+articleType + '  '+ articleRef); 
		KmArticleWebServiceReply reply = getArticleFromArticleDepot(articleRef, publishStatus);
		
		if ( reply == null) {
			System.debug('*** Error - return null for KmArticleWebService::post '+articleType + '  '+ articleRef + ' '+ publishStatus); 
		}
		
		return reply;
	}

	private static KmArticleWebServiceReply getArticleFromArticleDepot(string articleRef, string publishStatus) {
		List<ArticlePDF__c> articles = [ 
				select a.ArticleType__c, a.ArticleTypeAPI__c, a.Article_Number__c, a.OrginalArticleId__c,
					a.KnowledgeContainerName__c, a.Department_Role__c, a.Details__c, a.Title__c,
					a.DM_Forms__c, a.Expiration_Date__c, a.PublishedDate__c, a.FOPP_Text__c,
					a.VersionNumber__c, a.PublishStatus__c, a.UrlName__c, a.ArticleCreatedDate__c,
					a.ArticleCreatedBy__c, a.ArticleLastModifiedDate__c, a.ArticleLastModifiedBy__c
				from ArticlePDF__c a
				where ( a.OrginalArticleVersionId__c = :articleRef ) 
		];
		
		if ( articles.size() == 1) {
			return new KmArticleWebServiceReply(articles[0]);
		} else {
			return null;
		}
	} 
	
	//KmArticleWebService.deleteAllArticleDepotPdf();
	public static void deleteAllArticleDepotPdf () {
		List<ArticlePDF__c> articlePdfList = [
			select id, ArticlePdfContentVersionId__c
			from ArticlePDF__c
			where ArticlePdfContentVersionId__c <> null
		];
		
		List<Id> cvIdList = new List<Id>();
		for(ArticlePDF__c articlePdf : articlePdfList) {
			cvIdList.add(articlePdf.ArticlePdfContentVersionId__c);
			articlePdf.ArticlePdfContentVersionId__c = null;
		}
		
		List<ContentVersion> cvList = [
			select id
			from ContentVersion
			where id in :cvIdList
		];  
		
		//delete cvList;
		//delete not allowed on content
		update articlePdfList;
		
	}
	
	global class KmArticleWebServiceReply {
	
		public String articleTypeLabel = '';
		public String articleType = '';
	 	public String articleNumber = '';
	 	public String knowledgeArticleId = '';
	 	public String container = '';
	 	public String role = '';
	 	public String detail = '';
	 	public String title = '';
	 	public String dmforms = '';
	 	public Date expiration = Date.Today();
	 	public Datetime publishDate = DateTime.Now();
	 	public String fopp = '';
	 	public Integer version = -1;
	 	public String publishStatus = '';
	 	public String UrlName = '';
	 	
	 	public Datetime createdDate = DateTime.Now();
	 	public String createdBy = '';
	 	public Datetime lastModifiedDate = DateTime.Now();
	 	public String lastModifiedBy = '';
	 	
	 	//hierarchyId = a.Knowledge_Container__r.Name;
	 	//
	 	public KmArticleWebServiceReply( ArticlePDF__c a) {
	 		articleTypeLabel = a.ArticleType__c; 
	 		articleType = a.ArticleTypeAPI__c;
	 		articleNumber = a.Article_Number__c;
	 		knowledgeArticleId = a.OrginalArticleId__c;
	 		container = a.KnowledgeContainerName__c; 
	 		role = a.Department_Role__c;		
	 		detail = a.Details__c;
	 		title = a.Title__c;
	
	 		dmforms = a.DM_Forms__c;
	 		expiration = a.Expiration_Date__c;
	 		publishDate = a.PublishedDate__c;
	 		fopp = a.FOPP_Text__c;
	 		version = Integer.ValueOf(a.VersionNumber__c);  
	 		publishStatus = a.PublishStatus__c;
	 		UrlName = a.UrlName__c;
	 		
	 		createdDate = a.ArticleCreatedDate__c;
	 		createdBy = a.ArticleCreatedBy__c;
	 		lastModifiedDate = a.ArticleLastModifiedDate__c;
	 		lastModifiedBy = a.ArticleLastModifiedBy__c;
	 	}
	
	}
}