objects/ArticlePDF__c.object
<CustomObject>
    <description>Article Depot
Compliance Requirement 
Store all versions of knowledge articles 
as well as PDF</description>
    <fields>
        <fullName>ArticleHtml__c</fullName>
        <label>ArticleHtml</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ArticleNumVersion__c</fullName>
        <externalId>true</externalId>
        <label>ArticleNumVersion</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticlePdfContentVersionId__c</fullName>
        <label>ArticlePdfContentVersionId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleTypeAPI__c</fullName>
        <label>ArticleTypeAPI</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrginalArticleId__c</fullName>
        <description>cannot create relationship since articles will come from many article type tables</description>
        <label>OrginalArticleId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrginalArticleVersionId__c</fullName>
        <description>OrginalArticleVersionId__c - cannot use related to</description>
        <label>OrginalArticleVersionId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <label>Version Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Articles Depot</label>
    <nameField>
        <displayFormat>AP-{0000000}</displayFormat>
        <label>Articles Depot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Article Depot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KmArticleDepotWebService.cls
@RestResource(urlMapping='/KmArticleDepotWebService/v1/*')
global class KmArticleDepotWebService {

	//return ArticleDepotRecords without PDF
	@httpPost
	global static KmArticleDepotReply post() {
		List<ArticlePDF__c> articles = [ 
				select a.id, a.ArticleType__c, a.ArticleTypeAPI__c, a.Article_Number__c, a.OrginalArticleId__c, OrginalArticleVersionId__c,
					a.ArticleNumVersion__c, a.VersionNumber__c, a.ArticlePdfContentVersionId__c, a.ArticleHtml__c, a.Title__c, a.Summary__c
				from ArticlePDF__c a
				where ( a.ArticlePdfContentVersionId__c = null ) 
				limit 1000
		];
		
		return new KmArticleDepotReply(articles);
	}

	global class KmArticleDepotReply {
	
		global List<KmArticleDepotReplyDetail> details;	
		
		global KmArticleDepotReply(List<ArticlePDF__c> articlesPdfs) {
			details = new List<KmArticleDepotReplyDetail>();
			
			for(ArticlePDF__c articlePdf : articlesPdfs) {
				details.add(new KmArticleDepotReplyDetail(articlePdf) );
			}
			
		}
	}
	
	global class KmArticleDepotReplyDetail {
	
		public String Id;
		public String ArticleType;
		public String ArticleTypeAPI;
		public String Article_Number;
		public String OrginalArticleId;
		public String OrginalArticleVersionId;
		public String ArticleNumVersion;
		public String VersionNumber;
		public String ArticlePdfContentVersionId;
		public String ArticleHtml;
		public String Title;
		public String Summary;
		
		global KmArticleDepotReplyDetail(ArticlePDF__c articlePdf) {
			Id = articlePdf.Id;
			ArticleType = articlePdf.ArticleType__c;
			ArticleTypeAPI = articlePdf.ArticleTypeAPI__c;
			Article_Number = articlePdf.Article_Number__c;
			OrginalArticleId = articlePdf.OrginalArticleId__c;
			OrginalArticleVersionId = articlePdf.OrginalArticleVersionId__c;
			ArticleNumVersion = articlePdf.ArticleNumVersion__c;
			VersionNumber = String.valueOf(articlePdf.VersionNumber__c);
			ArticlePdfContentVersionId = articlePdf.ArticlePdfContentVersionId__c;
			ArticleHtml = articlePdf.ArticleHtml__c;
			Title = articlePdf.Title__c;
			Summary = articlePdf.Summary__c;  
		}
	}  

}