objects/Binder__c.object
<CustomObject>
    <description>Compliance Requirement 
Collection of Knowledge Management Articles or Contents to be printed as PDF.

Rally US504</description>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAQ</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>How To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Pass Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Talking Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FOPP__c</fullName>
        <label>FOPP</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Include_Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Archived Articles</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_children__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include children of hierarchy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Knowledge_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Container</label>
        <referenceTo>KnowledgeContainer__c</referenceTo>
        <relationshipLabel>Binders</relationshipLabel>
        <relationshipName>Binders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SOQL_Archive_1__c</fullName>
        <label>SOQL Archive 1</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Archive_2__c</fullName>
        <label>SOQL Archive 2</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Archive_3__c</fullName>
        <label>SOQL Archive 3</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_DG_Pack__c</fullName>
        <label>SOQL DG Pack</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Online__c</fullName>
        <label>SOQL Online</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Binder</label>
    <nameField>
        <label>Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BinderPage__c.object
<CustomObject>
    <description>Compliance Requirement 
Detail Record of a binder</description>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>BinderPages</relationshipLabel>
        <relationshipName>BinderPages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FOPP__c</fullName>
        <label>FOPP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Published_Date__c</fullName>
        <label>First Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <formula>Knowledge_Container_Name__r.containername__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hierarchy</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BinderPage</label>
    <nameField>
        <displayFormat>BPN-{00000000}</displayFormat>
        <label>BinderPage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BinderPages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KB_App_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KB App Settings</label>
</CustomObject>

objects/KnowledgeContainer__c.object
<CustomObject>
    <label>Knowledge Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrintJob__c.object
<CustomObject>
    <description>Compliance Requirement
To keep track of the final URL of the merged PDF document.  Merged version of Article PDFs and Desk Guide PDFs.</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>PrintJobs</relationshipLabel>
        <relationshipName>PrintJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PrintJob</label>
    <nameField>
        <displayFormat>PJ-{0000000}</displayFormat>
        <label>PrintJob Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrintJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BinderModel.cls
/**
* @author       Benjamin Lau
* @date         09/30/2014
* @description  BinderModel - methods to insert / retrieve pages into binder for printing articles by Search functions
*
* - upgraded to work with dynamic ArticleTypes
* - add without sharing keyword so that all KM team members can refresh binder pages / queries created by another KM team member
**/

public without sharing class BinderModel {
	
	public static Binder__c getBinderById(id BinderId) {
		List<Binder__c> binders = [
			select id, Article_Type__c, Comment__c,
				FOPP__c, From_Date__c, Include_children__c,  Include_Archived__c,
				Knowledge_Container__c,Knowledge_Container__r.name, recordType.name, To_Date__c,
				SOQL_Online__c, SOQL_DG_Pack__c,
				SOQL_Archive_1__c, SOQL_Archive_2__c, SOQL_Archive_3__c
			from binder__c
			where id = :binderId
		];
		
		if ( binders.size() <> 1) {
			return null;
		} else {
			return binders[0];
		}
	}


	//returns a list of binder page element based on filter criteria 1	
	public static List<BinderPage__c> getAllBinderPagesPrint1 (id BinderId) {
		List<BinderPage__c> pages = [
			select id
			from BinderPage__c
			where Binder__c = :BinderId
			order by FOPP__c,Hierarchy__c, First_Published_Date__c desc
		];
		
		return pages;
	}
	
	//returns a list of binder page element based on filter criteria 1	
	public static List<BinderPage__c> getAllBinderPagesPrint2 (id BinderId) {
		List<BinderPage__c> pages = [
			select id
			from BinderPage__c
			where Binder__c = :BinderId
			order by Article_Number__c, Title__c, First_Published_Date__c desc
		];
		
		return pages;
	}
	
	public static void clearAllBinderPages(id BinderId) {
		List<BinderPage__c> pages = getAllBinderPagesPrint1(BinderId);
		
		Delete pages;
	}  
	
	    
    public static void PrintJobTriggerHandler(List<PrintJob__c> jobs) {
    	for(PrintJob__c job : jobs ) {
   			BinderModel.processPrintJob(job.name);
   		}
    }
	
	//BinderModel.processPrintJob ('PJ-0000000');
	@future(callout=true)
    public static void processPrintJob(String printJobName) {
		Http h = new Http();
	
		// Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
		HttpRequest req = new HttpRequest();
		
		String endPointURL = '';
		
		try{
    		endPointURL = 'https://extapptest.services.toyotafinancial.com/SFDCweblinkKM/kmPdfMerger?printJobName=';
    		//endPointURL = 'http://75.85.65.144:8080/SFDCweblinkKM/kmPdfMerger?printJobName=';

    		KB_App_Settings__c kmEnginePrintBinderUrl = KB_App_Settings__c.getInstance('kmEnginePrintBinderUrl');
    		
    		if ( kmEnginePrintBinderUrl != null) {
    			endPointURL = kmEnginePrintBinderUrl.Value__c;
    		} 
    	}
    	catch(Exception e){
    		endPointURL = 'https://extapptest.services.toyotafinancial.com/SFDCweblinkKM/kmPdfMerger?printJobName=';
    	}
		
		req.setEndpoint(endPointURL+printJobName);
		req.setMethod('GET');
	 
		// Send the request, and return a response
		if (!Test.isRunningTest()) {
			HttpResponse res = h.send(req);
		}  
    }  

    
    
    /*
    ProcessPrintJob End Points
    
    PC Server at Benjamin's home office
    'http://76.95.105.179:8088/TfsKmPdfMerger?printJobName='
    
    OSX Server at Benjamin's home office
    'http://76.95.105.179:8082/SFDCweblinkKM/kmPdfMerger?printJobName='
    'http://76.95.105.179:8082/SFDCweblinkKM/kmPdfMerger?printJobName='
    'http://24.86.162.36:8080/SFDCweblinkKM/kmPdfMerger?printJobName=PJ-0000063'
    
    TFS - Test Server
    'https://extapptest.services.toyotafinancial.com/SFDCweblinkKM/kmPdfMerger?printJobName='
    
    */
    
    
	

}