objects/Binder__c.object
<CustomObject>
    <description>Compliance Requirement 
Collection of Knowledge Management Articles or Contents to be printed as PDF.

Rally US504</description>
    <fields>
        <fullName>Article_Type__c</fullName>
        <label>Article Type</label>
        <picklist>
            <picklistValues>
                <fullName>FAQ</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>How To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product and Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Pass Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Talking Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FOPP__c</fullName>
        <label>FOPP</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Include_Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include Archived Articles</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_children__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include children of hierarchy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Knowledge_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Container</label>
        <referenceTo>KnowledgeContainer__c</referenceTo>
        <relationshipLabel>Binders</relationshipLabel>
        <relationshipName>Binders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Binder</label>
    <nameField>
        <label>Binder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Binders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BinderPage__c.object
<CustomObject>
    <description>Compliance Requirement 
Detail Record of a binder</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>BinderPages</relationshipLabel>
        <relationshipName>BinderPages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FOPP__c</fullName>
        <label>FOPP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BinderPage</label>
    <nameField>
        <displayFormat>BPN-{00000000}</displayFormat>
        <label>BinderPage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BinderPages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FAQ_A__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>FOPP__c</fullName>
        <label>FOPP #</label>
        <length>2500</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Knowledge_Container__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Container</label>
        <referenceTo>KnowledgeContainer__c</referenceTo>
        <relationshipName>faq_v1_1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FAQ</label>
    <pluralLabel>FAQs</pluralLabel>
</CustomObject>

objects/KnowledgeContainer__c.object
<CustomObject>
    <fields>
        <fullName>containername__c</fullName>
        <label>containername</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Container</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Containers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PrintJob__c.object
<CustomObject>
    <description>Compliance Requirement
To keep track of the final URL of the merged PDF document.  Merged version of Article PDFs and Desk Guide PDFs.</description>
    <fields>
        <fullName>Binder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Binder</label>
        <referenceTo>Binder__c</referenceTo>
        <relationshipLabel>PrintJobs</relationshipLabel>
        <relationshipName>PrintJobs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PrintJob</label>
    <nameField>
        <displayFormat>PJ-{0000000}</displayFormat>
        <label>PrintJob Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PrintJobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BinderModelTest.cls
/**
* @author       Benjamin Lau
* @date         09/30/2014
* @description  Unit Test for BinderModel
*
**/
@IsTest
public class BinderModelTest {

	public static String testBinderId1 = null;
	public static String testBinderId1a = null;
	public static String testBinderId2 = null;
	public static String testBinderIdInvalid = null;

	@IsTest
	public static void TestGetBinderById() {
		createData();
		Test.StartTest();
		
		System.assertEquals(null, BinderModel.getBinderById(null));
		
		System.assertNotEquals(null, testBinderId1);
		Binder__c binder = BinderModel.getBinderById(testBinderId1);
		System.assertNotEquals(null, binder);
		
		System.assert(BinderModel.getAllBinderPagesPrint1(testBinderId1).size() > 0);
		System.assert(BinderModel.getAllBinderPagesPrint2(testBinderId1).size() > 0);
		
		BinderModel.clearAllBinderPages(testBinderId1);
		System.assert(BinderModel.getAllBinderPagesPrint1(testBinderId1).size() == 0);
		System.assert(BinderModel.getAllBinderPagesPrint2(testBinderId1).size() == 0);
	
		testBinderId1 = null;  // all pages deleted. reset createData

		Test.StopTest();
	}
	
	@IsTest
	public static void TestOrderBy() {
		createData();
		Test.StartTest();
		BinderPageFilter2.OrderByArticleNumVersionThenTitleForDeskGuides(testBinderId1);
		BinderPageFilter2.OrderByKnowledgeContainerArticleNumVersion(testBinderId1);
		BinderPageFilter2.OrderByFoppArticleNumVersion(testBinderId1);
		BinderPageFilter2.OrderByArticleTypeNumberVersionDesc(testBinderId1);
		BinderPageFilter2.OrderByPublishedDate(testBinderId1);
		
		Test.StopTest();
	}
	
	@IsTest
	public static void TestWebServices() {
		createData();
		BinderPageFilter2.ClearAllBinderPages(testBinderId1);
		BinderPageFilter2.RenumberAllBinderPages(testBinderId1);
	}
	
	@IsTest
	public static void TestUtils() {
		Set<id> ids = new Set<id>();
		Set<String> names = new Set<String>();
		
		for(User u : [select id from user limit 5]) {
			ids.add(u.id);
			names.add(u.id);
		}

		Test.StartTest();
		BinderPageFilter2.getDateTimeEOD(Date.today());
		BinderPageFilter2.getDateTimeEOD(null);
		BinderPageFilter2.idSetToString(ids);
		BinderPageFilter2.stringSetToString(names);
		
		Test.StopTest();  
	}
	
	@IsTest 
	public static void TestBinderTrigger() {
		createData();
		List<Binder__c> binders = [ select id from Binder__c];
		delete binders;
	}
	  
	
	@IsTest
	public static void TestProcessPrintJob() {
		createData();
		
		PrintJob__c job = new PrintJob__c();
		job.Binder__c = testBinderId1;
		insert job;
		
		//@future(callout=true)
		BinderModel.processPrintJob('PJ-0000000');		
	}
	
	// unit test for BinderPageFilter2
	@IsTest
	public static void TestQueryForArticles() {
		CreateData();
		BinderPageFilter2.QueryForArticles(null);
		BinderPageFilter2.QueryForArticles(testBinderId1);
		BinderPageFilter2.QueryForArticles(testBinderId1a);
		BinderPageFilter2.QueryForArticles(testBinderId2);
		BinderPageFilter2.QueryForArticles(testBinderIdInvalid);
	}
	
	
	public static void createData() {
		KnowledgeContainer__c kc = createKnowledgeContainer();
		createDataBinder1(kc);
		createDataBinder1a(kc);
		createDataBinder2(kc);
		createDataBinderInvalid(kc);
	}
	
	public static KnowledgeContainer__c createKnowledgeContainer() {
		KnowledgeContainer__c kc = new KnowledgeContainer__c();
		kc.containername__c = 'testContainer';
		insert kc;
		return kc;
	}
	
	
	//no children / archived
	public static void createDataBinder1(KnowledgeContainer__c kc) {
		if (testBinderId1 <> null ) {
			return;
		}
		
		// 1 - create binder
		Binder__c binder = new Binder__c();
		binder.Article_Type__c = 'FAQ_A__kav';
		binder.Comment__c = 'Test Binder';
		binder.FOPP__c = '1';
		binder.From_Date__c = Date.today().addMonths(-1);
		binder.To_Date__c = Date.today();
		binder.Knowledge_Container__c = kc.id;
		binder.Include_children__c = false;
		binder.Include_Archived__c = false;
		
		binder.RecordTypeId = RecordTypeModelKm.BinderPrint1RecTypeId;
		insert binder;
		
		System.assert(binder.id <> null);
		testBinderId1 = binder.id;
		
		// 2 - create binder pages
		List<BinderPage__c> pages = new List<BinderPage__c>();
		
		BinderPage__c page1 = new BinderPage__c();
		pages.add(page1);
		page1.Binder__c = testBinderId1;
		page1.Title__c = 'Title1';
		
		BinderPage__c page2 = new BinderPage__c();
		pages.add(page2);
		page2.Binder__c = testBinderId1;
		page2.Title__c = 'Title2';
		
		BinderPage__c page3 = new BinderPage__c();
		pages.add(page3);
		page3.Binder__c = testBinderId1;
		page3.Title__c = 'Title3';
		
		
		insert pages;
		
	}
	
	//include children / archived
	public static void createDataBinder1a(KnowledgeContainer__c kc) {
		if (testBinderId1a <> null ) {
			return;
		}
		
		// 1 - create binder
		Binder__c binder = new Binder__c();
		binder.Article_Type__c = 'FAQ_A__kav';
		binder.Comment__c = 'Test Binder';
		binder.FOPP__c = '1a';
		binder.From_Date__c = Date.today().addMonths(-1);
		binder.To_Date__c = Date.today();
		binder.Knowledge_Container__c = kc.id;
		binder.Include_children__c = true;
		binder.Include_Archived__c = true;
		
		binder.RecordTypeId = RecordTypeModelKm.BinderPrint1RecTypeId;
		insert binder;
		
		System.assert(binder.id <> null);
		testBinderId1a = binder.id;
		
		// 2 - create binder pages
		List<BinderPage__c> pages = new List<BinderPage__c>();
		
		BinderPage__c page1 = new BinderPage__c();
		pages.add(page1);
		page1.Binder__c = testBinderId1;
		page1.Title__c = 'Title1';
		
		BinderPage__c page2 = new BinderPage__c();
		pages.add(page2);
		page2.Binder__c = testBinderId1;
		page2.Title__c = 'Title2';
		
		BinderPage__c page3 = new BinderPage__c();
		pages.add(page3);
		page3.Binder__c = testBinderId1;
		page3.Title__c = 'Title3';
		
		
		insert pages;
		
	}
	
	public static void createDataBinder2(KnowledgeContainer__c kc) {
		
		if (testBinderId2 <> null) {
			return;
		}
		
		Binder__c binder2 = new Binder__c();
		binder2.Article_Type__c = 'FAQ__kav';
		binder2.Comment__c = 'Test Binder2';
		binder2.FOPP__c = '2';
		binder2.From_Date__c = Date.today().addMonths(-1);
		binder2.To_Date__c = Date.today();
		binder2.RecordTypeId = RecordTypeModelKm.BinderPrint2RecTypeId;
		insert binder2;
		
		System.assert(binder2.id <> null);
		testBinderId2 = binder2.id;
		
		// 2 - create binder pages
		List<BinderPage__c> pages = new List<BinderPage__c>();
		
		BinderPage__c page1 = new BinderPage__c();
		pages.add(page1);
		page1.Binder__c = testBinderId2;
		page1.Title__c = 'Title1';
		
		BinderPage__c page2 = new BinderPage__c();
		pages.add(page2);
		page2.Binder__c = testBinderId2;
		page2.Title__c = 'Title2';
		
		BinderPage__c page3 = new BinderPage__c();
		pages.add(page3);
		page3.Binder__c = testBinderId2;
		page3.Title__c = 'Title3';
		
		
		insert pages;
	}
	
	
	public static void createDataBinderInvalid(KnowledgeContainer__c kc) {
		
		if (testBinderIdInvalid <> null) {
			return;
		}
		
		Binder__c binder3 = new Binder__c();
		binder3.Article_Type__c = 'FAQ__kav';
		binder3.Comment__c = 'Test BinderInvalid';
		binder3.FOPP__c = '2';
		binder3.From_Date__c = Date.today().addMonths(-1);
		binder3.To_Date__c = Date.today();
		binder3.RecordTypeId = RecordTypeModelKm.BinderPrint2RecTypeId;
		insert binder3;
		
	}
	
	@IsTest
	public static void utilTest() {
		List<User> users = [select id from user limit 5];
		Set<Id> ids = new Set<Id>();
		for(User u : users) {
			ids.add(u.id);
		}
		
		String idAsString = BinderPageFilter2.idSetToString(ids);
		System.assertNotEquals(null, idAsString);
		
		System.assertNotEquals(null, BinderPageFilter2.getDateTime(Date.Today()));
		System.assertEquals('', BinderPageFilter2.getDateTime(null));
		
		
	}
	
}