objects/Case_LastViewed__c.object
<CustomObject>
    <description>Holds a single record per case of when the last time the corresponding community user, if any, last viewed the record.  Used on the community pages to highlight support requests with new updates.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case LastViews</relationshipLabel>
        <relationshipName>Case_LastViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Viewed__c</fullName>
        <description>True if the user has viewed the related Case since its last update.</description>
        <formula>Last_Viewed_Date__c &gt;= Case__r.LastModifiedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Viewed Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_LastViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case LastView</label>
    <nameField>
        <displayFormat>CLV{000000000}</displayFormat>
        <label>Case LastViewed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case LastViews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Weblogin</fullName>
        <active>true</active>
        <description>Record type for customer community web login for TFS or LFS</description>
        <label>Weblogin</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>WebLogin</fullName>
        <active>true</active>
        <description>PersonAccount to Enable Multiple Web Logins for a customer.  Will be used to enable Customer Community user</description>
        <label>Web Login</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_Weblogin_UnreadMsgCount.cls
public class TFSC_Weblogin_UnreadMsgCount extends TFSC_Weblogin_Base{

    
	public WebLoginWebServiceReply execute(String SGUID) {
		// find Community User record with Federation id = SGUID		
		User webloginUser = findUserBySGUID(SGUID);
		
		// return -1 if not found
		if (webloginUser == null) {
			return new WebLoginWebServiceReply(-1, SGUID + ' is not a valid Federation id');
		}
		
		// find last login date
		DateTime lastLoginDate = webloginUser.LastLoginDate;
		
		// find the weblogin PersonAccount associated with this user
		Contact webloginContact = findWebloginContactBySGUID(SGUID);
		
		if (webloginContact == null) {
			return new WebLoginWebServiceReply(-1, SGUID + ' is not a valid SGUID on PersonAccount of RecType Weblogin');
		}
		
	 	Id webloginContactId = webloginContact.Id;
		
		
		//find the FAC that this weblogin is registered with
		List<Financial_Account_Customer__c> facList = findFinancialAccountCustomerListByWebloginContactId(webloginContactId);

		Set<Id> facIdSet = new Set<id>();
		for(Financial_Account_Customer__c fac : facList) {
			facIdSet.add(fac.Id);
		}	

		//updated by Benjamin on 2015-02-27
		List<Case_LastViewed__c> caseLastViewedList = [
			select Case__c 
			from Case_LastViewed__c
			where User__c = :webloginUser.Id
			and Has_Viewed__c = true
		];
		
		Set<id> viewedCaseIdSet = new Set<Id>();
		for(Case_LastViewed__c clv : caseLastViewedList) {
			viewedCaseIdSet.add(clv.Case__c);
		}
		
		List<Case> contactCases = [
			select Id
			from Case
			where ContactId = :webloginContactId
			and Financial_Account_Customer__c in :facIdSet
		];
		
		Integer unreadMsgCount = 0;
		for(Case c : contactCases) {
			if ( !viewedCaseIdSet.contains(c.id )) {
				unreadMsgCount++;
			}
		} 
	
		System.Debug('TFSC_Weblogin_UnreadMsgCount for '+SGUID + ' = '+unreadMsgCount+ ' last login date = '+ lastLoginDate);		
		
		return new WebLoginWebServiceReply(unreadMsgCount, 'unread message = '+unreadMsgCount+' for '+SGUID+ ' last login date = '+ lastLoginDate);
	}  

}