objects/CaseOutCome__c.object
<CustomObject>
    <label>CaseOutCome</label>
    <nameField>
        <displayFormat>COC-{000}</displayFormat>
        <label>CaseOutCome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CaseOutComes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/tempinteraction__c.object
<CustomObject>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <label>Interaction Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Temp Interaction</label>
    <nameField>
        <label>Temp Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temp Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TFSC_CaseOutComeHandler_Test.cls
@isTest(SeeAllData=false)
private class TFSC_CaseOutComeHandler_Test {
    
    @isTest
    private static void test_resolvedCase() {
        //setup the test data
        TFSC_TestUtility test = new TFSC_TestUtility();
        System.runAs(test.testAdmin) {

            Case resolvedCase = new Case(
                RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Support Request').getRecordTypeId(),
                Subject = 'Subject',
                Status = 'Resolved',
                Closed_Disposition__c = 'Text'
            );
            insert resolvedCase;

            resolvedCase = [select Id, CaseOutCome__c from Case where Id = :resolvedCase.Id];
            System.assertEquals(resolvedCase.CaseOutCome__c, test.caseOutcomes[0].Id);

        }

    }
    
    @isTest
    private static void test_resolvedCase_Default() {
        //setup the test data
        TFSC_TestUtility test = new TFSC_TestUtility();
        System.runAs(test.testAdmin) {

            Case resolvedCase = new Case(
                RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Support Request').getRecordTypeId(),
                Subject = '',
                Status = 'Resolved',
                Closed_Disposition__c = 'Text'
            );
            insert resolvedCase;

            resolvedCase = [select Id, CaseOutCome__c from Case where Id = :resolvedCase.Id];
            System.assertEquals(resolvedCase.CaseOutCome__c, test.caseOutcomes[1].Id);

        }

    }
    // Test class added to cover changes for S-311850 by Paras Dhingra 7/10/2015 #Start
    @isTest
    private static void test_profileChangeCase(){
        //create test data
        TFSC_TestUtility test = new TFSC_TestUtility();

        System.runAs(test.testAdmin) {
            tempInteraction__c interaction  = new tempInteraction__c(name = String.valueOf(test.finAcct.id).left(15), Interaction_Type__c = 'inbound call');
            insert interaction;
            Case changeProfileCase = new Case(
                RecordTypeId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Profile Change').getRecordTypeId(),
                Subject = '',
                Status = 'Resolved',
                Closed_Disposition__c = 'Text',
                Financial_Account__c = test.finAcct.id
                );
            insert changeProfileCase;
        }
    }
    //S-311850 #End

}