objects/Case_LastViewed__c.object
<CustomObject>
    <description>Holds a single record per case of when the last time the corresponding community user, if any, last viewed the record.  Used on the community pages to highlight support requests with new updates.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case LastViews</relationshipLabel>
        <relationshipName>Case_LastViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Viewed__c</fullName>
        <description>True if the user has viewed the related Case since its last update.</description>
        <formula>Last_Viewed_Date__c &gt;= Case__r.LastModifiedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Has Viewed Updates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_LastViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case LastView</label>
    <nameField>
        <displayFormat>CLV{000000000}</displayFormat>
        <label>Case LastViewed Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case LastViews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_SupportRequestsController.cls
public with sharing class TFSC_SupportRequestsController {

    private final List<String> orderBys = new List<String> {
        ' ORDER BY CreatedDate desc',
        ' ORDER BY LastModifiedDate desc',
        ' ORDER BY CaseNumber',
        ' AND ClosedDate = NULL ORDER BY LastModifiedDate desc',
        ' AND ClosedDate != NULL ORDER BY LastModifiedDate desc'
    };

    public List<SupportRequest> supportReqs {get;private set;}
    public Integer orderBy {get;set;}

    public Boolean hasSupportRequests {
        get {
            return !(this.supportReqs == null || this.supportReqs.isEmpty());
        }
    }

    public TFSC_SupportRequestsController() {
        this.orderBy = 1; //last updated
        fetchSupportRequests();
    }

    public PageReference fetchSupportRequests() {

        if (TFSC_CommunitySettings.PERSONID != null ) {
            
            String contactId = TFSC_CommunitySettings.CONTACTID;
            String userId = UserInfo.getUserId();
            Set<Id> facIds = new Set<Id>{};


            for(Financial_Account_Customer__c fac : TFSC_CommunitySettings.findFinancialAccountCustomersForWeblogin()) {
                facIds.add(fac.Id);
            }

            String query = 
                'select Id, CaseNumber, Status, Financial_Account_Customer_Name__c, Service_Request_Subject__c, LastModifiedDate ' +
                'from Case where ContactId = :contactId and Financial_Account_Customer__c in :facIds';
            
            //how to sort
            query += this.orderBys[this.orderBy];

            //this feeds into a pageblocktable which is limited to 1000 items
            query += ' limit 1000';
            
            List<Case> reqs = Database.query(query);
            
            List<id> caseIds = new List<id>();
            for(Case req : reqs) {
                caseIds.add(req.id);
            }
            
            List<Case_LastViewed__c> clvList = [
                select Has_Viewed__c, Case__c
                from Case_LastViewed__c 
                where User__c = :userId 
                and Case__c in :caseIds
                and Has_Viewed__c = true  
            ];  
            
            set<Id> hadViewedCaseIds = new set<Id>();
            for(Case_LastViewed__c clv : clvList) {
                hadViewedCaseIds.add(clv.Case__c);
            } 
            
            
            this.supportReqs = new List<SupportRequest>{};
            for(Case req : reqs ) {
                
                this.supportReqs.add(new SupportRequest(req, !hadViewedCaseIds.contains(req.id)));
            }
        }

        return null;
    }
    //caseData.Case_LastViews__r.isEmpty() ? true : !caseData.Case_LastViews__r[0].Has_Viewed__c;

    public class SupportRequest {

        public Boolean hasUpdate {get;private set;}
        public Case details {get;private set;}
        public String style {get { return this.hasUpdate ? 'font-weight:bold;' : ''; }}

        public SupportRequest(Case caseData, boolean hasUpdate) {
            //the user has an update if:  they have never seen the case, or if Has_Viewed [Last Update] is false
            this.hasUpdate = hasUpdate;
            this.details = caseData;
        }

    }

}