objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <fields>
        <fullName>Vehicle_Identification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Vehicle Identification Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to align Form Rule with the case.</description>
        <label>State of Jurisdiction</label>
        <type>TextArea</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Auction_Agency_City__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction city at which repossession is scheduled to be sold.</description>
        <label>Auction Agency City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Name__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction name at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Phone__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction phone at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_State__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction state at which repossession is scheduled to be sold.</description>
        <label>Auction Agency State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street1__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 1 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street2__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 2 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Zip__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction zip code at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Local_Repo_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Date of the repossession at the place of repossession. Since date/time is received in GMT, date must be converted to a local date and stored here. Handled within the RL Set State Conditions Flow and associated date/time Apex plug-in.</description>
        <label>Local Repo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state of residence for the primary borrower if in the 50 states, otherwise it is the state of the dealer. The rights letters process follows the laws in the given state. The value is set by the RL Set State Conditions flow.</description>
        <label>State of Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_City__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The city to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Name__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The name to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_State__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Street1__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The first line of the street address to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Street1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Street2__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The second line of the street address to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Street2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title_Zip__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The zip code to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>United_Road_Order_Date__c</fullName>
        <description>SRC: United Road 
INT: United Road Auction 
Trans: N 
BU: RL 
FD: The created date of the order according to the United Road system. For reference only.</description>
        <label>United Road Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>United_Road_Transport_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: United Road 
INT: United Road Auction 
Trans: N 
BU: RL 
FD: The fee for vehicle transportation from the repo agency to the auction. United Road coordinates the effort. The user clicks a button to query United Road for the fee based on the VIN.</description>
        <label>Transportation Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>iRepo_AccountNumber__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Account number value iRepo has received from Collections system. Format is 20-characters long and requires manipulation to map to SFDC format. Used in RL Set State Conditions Flow to set the lookup field to the financial account number if FA found and VIN matches.

Retail format: 00070401234567890001
000 = leading pads
704 = bank number (charge-off is 700 for retail and 800 for leases - out-of-scope for current RL)
0123456789 = 10-digit SFDC account number
0001 = sequence number for borrower - internal to host and can be ignored

Lease format: 000000000002382KD841
0000000000 = leading pads
02 = region
&quot;&quot; = add a 0 after that
382 = branch
KD841 = unique lease number</description>
        <label>iRepo Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iRepo_AssignmentNumber__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Unique work item identification in the iRepo system. Used as the external ID to support upsert operations on both Repossession and Case.</description>
        <externalId>true</externalId>
        <label>iRepo Assignment Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>iRepo_VIN__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Vehicle identification number as stored in iRepo&apos;s system. Compared with the VIN on the collateral of the searched financial account to confirm a successful match between iRepo assignment and SFDC financial account. Also used as a reference to facilitate looking up a financial account for a mismatched repo.</description>
        <label>iRepo VIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_UpdateURRedirectController.cls
public with sharing class RL_UpdateURRedirectController {
    
    private Repossession__c contextRepo;
    
    public String referrerUrl{get;set;}
    public String errDisplayText{get;set;}
    
    public RL_UpdateURRedirectController(ApexPages.StandardController stdController) {
        
        String[] repoFields = new String[] {'Case__r.Form_Rule__c', 'Case__c', 'iRepo_VIN__c', 
                                            'Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c', 
                                            'iRepo_AccountNumber__c', 'Financial_Account__c', 'State_of_jurisdiction__c',
                                            'Title_Name__c', 'Title_Street1__c', 'Title_Street2__c', 
                                            'Title_State__c', 'Title_City__c', 'Title_Zip__c', 'United_Road_Transport_Fees__c',
                                            'Auction_Agency_Zip__c','Auction_Agency_State__c','Auction_Agency_City__c',
                                            'Auction_Agency_Street2__c','Auction_Agency_Street1__c','Auction_Agency_Name__c', 
                                            'United_Road_Order_Date__c', 'Local_Repo_Date__c', 'iRepo_AssignmentNumber__c' };
        if (!Test.isRunningTest()) {   
            stdController.addFields(repoFields);
        }
        contextRepo = (Repossession__c) stdController.getRecord();
        referrerUrl = ApexPages.currentPage().getHeaders().get('Referer');
    }

    public PageReference updateURDetails() {
        PageReference pageRefToReturn = null;
        
        try {
            runUnitedRoadCallout();
            
        }catch(Exception e){
            appendErrorMessage( 'Salesforce Response: ' + e.getMessage());
        }
        return null;
    }
    
    
    public void runUnitedRoadCallout() {
        
        RL_WS_GetUnitedRoadData.UR_RequestParams requestParams;
        requestParams = new RL_WS_GetUnitedRoadData.UR_RequestParams();
        if(contextRepo.Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c != null) {
            requestParams.VIN = contextRepo.Financial_Account__r.Collateral__r.Vehicle_Identification_Number__c;
        }else{
            requestParams.VIN = contextRepo.iRepo_VIN__c;
        }
        
        if(requestParams.VIN == null || requestParams.VIN.length() == 0) {
            appendErrorMessage('Invalid Salesforce data.  There is not a VIN number associated with this account.');
            return;
        }
        
        
        System.debug( '***** requestParams.VIN =' + requestParams.VIN );
        
        RL_WS_GetUnitedRoadData.UR_ResponseParams responseParams;
        RL_WS_GetUnitedRoadData.UR_ResponseRecord responseRecord;
        if (Test.isRunningTest()) {
            responseParams = new RL_WS_GetUnitedRoadData.UR_ResponseParams();
            responseRecord = new RL_WS_GetUnitedRoadData.UR_ResponseRecord();
            responseParams.StatusParams.Status = 'SUCCESS';
            responseRecord.LocationName = 'TEST NAME'; 
            responseRecord.TransportFee = '1234';
            responseRecord.LocationId = '1234';
            responseRecord.CreatedDate = '01-01-2015';
        } else {
            responseParams = RL_WS_GetUnitedRoadData.getURdata(requestParams);
            responseRecord = responseParams.responseRecord ;
        }
        
        System.debug( '***** responseParams =' + responseParams );
        
        
        
        if(responseParams.StatusParams != null && responseParams.StatusParams.Status != null && responseParams.StatusParams.Status == 'FAIL') {
            errDisplayText = 'TIBCO Error: ' + responseParams.StatusParams.Error;
            appendErrorMessage(errDisplayText);
        } else if(responseRecord != null && 
                (
                    (responseRecord.LocationName == null || responseRecord.LocationName == '')
                    && (responseRecord.TransportFee == null || responseRecord.TransportFee == '')
                    && (responseRecord.LocationID == null || responseRecord.LocationID == '')
                ) ) 
        {
            appendInfoMessage('No records found on United Road.  Redirecting...');
        } else if(responseRecord != null) { 
            System.debug( '***** responseRecord =' + responseRecord );
            
            String locationId = responseRecord.LocationID;
            String locationName = responseRecord.LocationName ;
            String locationAdd1 = responseRecord.LocationAdd1 ;
            String locationAdd2 = responseRecord.LocationAdd2 ;
            String locationCity = responseRecord.LocationCity ;
            String locationState = responseRecord.LocationState ;
            String locationZIP = responseRecord.LocationZIP ;
            String locationPhone = responseRecord.LocationPhone ;
            String transportFee = responseRecord.TransportFee ;
            String createdDate = responseRecord.CreatedDate ;
            String orderStatus = responseRecord.OrderStatus ;
            
            contextRepo.Auction_Agency_Zip__c = locationZIP; 
            contextRepo.Auction_Agency_City__c = locationCity; 
            contextRepo.Auction_Agency_State__c = locationState; 
            contextRepo.Auction_Agency_Street2__c = locationAdd2; 
            contextRepo.Auction_Agency_Street1__c = locationAdd1; 
            contextRepo.Auction_Agency_Name__c = locationName;
            contextRepo.Auction_Agency_Phone__c = locationPhone;
            
            System.debug( '***** locationPhone =' + locationPhone );
            System.debug( '***** locationZIP =' + locationZIP );
            
            if(transportFee == null || transportFee == '') {
                contextRepo.United_Road_Transport_Fees__c = null;
                System.debug( '***** transportFee null' );
            }else{
                try{
                    contextRepo.United_Road_Transport_Fees__c = Decimal.valueOf(transportFee) ;
                    System.debug( '***** contextRepo.United_Road_Transport_Fees__c = ' + contextRepo.United_Road_Transport_Fees__c );
                    System.debug( '***** transportFee = ' + transportFee );
                }catch(Exception e) {
                    System.debug( '***** e.error.transportFee = ' + e.getMessage() );
                    System.debug( '***** transportFee = ' + transportFee );
                }
            }
            
            Boolean dateError = false;
            if(createdDate == null || createdDate == '') {
                contextRepo.United_Road_Order_Date__c = null;
                System.debug( '***** createdDate null' );
            }else{
                try{
                    //2010-08-05 00:00:00.000
                    List<String> dateStringArray = createdDate.split('-'); 
                    String yyyy = dateStringArray[0];
                    String mm = dateStringArray[1];
                    String dd = dateStringArray[2].substring(0,2);
                    
                    Date date1 = Date.newInstance( Integer.valueOf(yyyy), Integer.valueOf(mm), Integer.valueOf(dd) );
                    Date date2 = Date.valueOf( createdDate );
                    contextRepo.United_Road_Order_Date__c = date1;
                    
                    System.debug('**** dateStringArray = ' + dateStringArray);
                    System.debug( '***** createdDate = ' + createdDate );
                    System.debug( '***** contextRepo.United_Road_Order_Date__c = ' + contextRepo.United_Road_Order_Date__c );
                }catch(Exception e) {
                    System.debug( '***** e.createdDate = ' + e.getMessage() );
                    System.debug( '***** createdDate = ' + createdDate );
                    appendErrorMessage(e.getMessage());
                    dateError = true;
                }
                    
            }
            
            if(contextRepo.Local_Repo_Date__c != null && contextRepo.United_Road_Order_Date__c != null) {
            	if(contextRepo.United_Road_Order_Date__c < contextRepo.Local_Repo_Date__c) {
            		
            		appendErrorMessage('United Road date is before this repossession date. \nUR Date = ' + String.valueOf(contextRepo.United_Road_Order_Date__c) + '. Repo date = ' + String.valueOf(contextRepo.Local_Repo_Date__c));
                    dateError = true;
            	}
            }else{
            	//iRepo_AssignmentNumber__c matches UR Order number.
            }
            
            System.debug( '***** contextRepo =' + contextRepo );
            
            if(!dateError) {
            	appendInfoMessage('Data successfully retrieved. Title fields updated.  Redirecting...');
            	update contextRepo;
            }
        }
    }
    
    
    private void appendInfoMessage(String infoMessage) {
        appendMessage(infoMessage, ApexPages.Severity.INFO);
    }
    
    private void appendErrorMessage(String errorMessage) {
        errDisplayText = errorMessage;
        appendMessage(errorMessage, ApexPages.Severity.ERROR);
    }
    
    private void appendMessage(String errorMessage, ApexPages.severity severity) {
        ApexPages.Message apexPageMessage = new ApexPages.Message(severity, errorMessage);
        ApexPages.addMessage(apexPageMessage);
    }
}