objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/FAQ_A__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>FAQ</label>
    <pluralLabel>FAQs</pluralLabel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Coll_Racf_Id__c</fullName>
        <label>Coll Racf Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lan_Id__c</fullName>
        <label>Lan Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TFSC_TestUtils.cls
public with sharing class TFSC_TestUtils {
    
    
    
    
    public static User generateTestUser(String profileName, Boolean insertUser) {
        
        String randomString = generateRandomString(6);
        
        //'Collections'
        Profile p = [SELECT Id FROM Profile WHERE Name=:profileName]; 
        User usr = new User(Alias = 'stst123', 
                            Coll_Racf_Id__c = 'XXX123',
                            Lan_Id__c = 'LANID', 
                            Email='usr' + randomString + '@toyotaDevish.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', 
                            UserName='usr' + randomString + '@toyotaDevish.com');
        
        if(insertUser) {
            insert usr;
        }
        
        return usr;
    }
    
    
    public static String generateRandomString(Integer charLength) {
        String randomString = EncodingUtil.convertToHex(crypto.generateAesKey(128)).substring(1,charLength);
        return randomString;
    }
    
    
    
    public static Account setupAndReturnNewAccount() {
        String randString = generateRandomString(5);
        Account acct = new Account(name = 'testAcct' + randString);
        insert acct;
        
        return acct;
    }
    
    
    public static Financial_Account__c setupAndReturnNewFinancialAccount(Account acct, String randString) {
        Collateral__c ast = new Collateral__c( name = 'testAsset' + randString );
        insert ast;
        
        Financial_Account__c financialAccount = new Financial_Account__c();
        financialAccount.Financial_Account_Number__c = randString;
        financialAccount.Collateral__c = ast.Id;
        insert financialAccount;
        
        return financialAccount;
    }
    public static Financial_Account__c setupAndReturnNewFinancialAccount(Account acct) {
        String randString = generateRandomString(8);
        return setupAndReturnNewFinancialAccount(acct, randString);
    }
    
    
    /**
    *   @borrowerPosition = 'Co-X' or 'Primary'
    */
    public static Financial_Account_Customer__c setupAndReturnFAC(Financial_Account__c fa, Account acct, String borrowerPosition) {
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c();
        fac.Borrower_Position__c = borrowerPosition;
        fac.Borrower_Status__c = 'Active';
        fac.Financial_Account__c = fa.Id;
        fac.Account__c = acct.Id;
        fac.Home_Phone_Garage__c = '4063775023';
        fac.Mobile_Phone__c = '4063775024';
        fac.Work_Phone_Garage__c = '4063775025';
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = 'test';
        fac.FA_Role_Status__c = 'test';
        fac.Financial_Account_Customer__c = 'test2' + TFSC_TestUtils.generateRandomString(4);
        insert fac;
        
        return fac;
    }
    
    public static FAQ_A__kav setupAndReturnArticle() {
        
        FAQ_A__kav artcl = new FAQ_A__kav(Title = 'Test Article',
                                          Summary = 'Test article type created by Apex',
                                          Answer__c = 'test',
                                          URLName = 'test'
                                         );
        
        insert artcl;
        //retrieve master article Id created on FAQ_A__kav record insertion
        //in order to get the KnowledgeArticleId
        artcl = [SELECT KnowledgeArticleId FROM FAQ_A__kav WHERE Id = :artcl.Id];
        
        //publish it
        KbManagement.PublishingService.publishArticle(artcl.KnowledgeArticleId, true);

        return artcl;
    }
    
    
}