objects/Collateral__c.object
<CustomObject>
    <description>Stores details of vehicles associated with financial accounts.</description>
    <label>Collateral</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collateral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collateral</label>
        <referenceTo>Collateral__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_AccountHighlightsControllerTest.cls
/**
*   @Author     : Jeremy Mooer
*   @Date       : 12 May 2014
*   @Description unit test for TFSC_AccountHighlightsController.
*   @   the controller is for a view-only vf page, so code-coverage is more important than assertions. 
*/
@isTest
private class TFSC_AccountHighlightsControllerTest {
    
    static testmethod void testValidFacQueries() {
        Account acct = new Account(name = 'testAcct1');
        insert acct;
        
        Financial_Account__c fAcct = setupData(acct);
        Financial_Account_Customer__c facPrimary = generateAndInsertFAC(fAcct.Id, 'Primary','Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
        Financial_Account_Customer__c facCo = generateAndInsertFAC(fAcct.Id, 'Co-X','Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
        
        addDummyFACsForCountingOfOtherAccounts(fAcct, acct.Id);
        
        PageReference pageRef = Page.TFSC_AccountHighlights;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', fAcct.Id);
        
        TFSC_AccountHighlightsController ctrl = new TFSC_AccountHighlightsController();
        
        System.assert( fAcct.Id == ctrl.contextFinancialAccount.Id );
        System.assert( facPrimary.Id == ctrl.topSectionFAC.Id );
        System.assert( facCo.Id == ctrl.bottomSectionFAC.Id );
        
        ctrl.showTopPopup();
        ctrl.showBottomPopup();
        ctrl.closePopup();
        
        ctrl.borrowerPhoneFromJS = '1234560000';
        ctrl.updateTopFac();
        
        //System.assert( ctrl.bottomSectionClosedOtherAccountCount == 0 );
        //System.assert( ctrl.bottomSectionOpenOtherAccountCount == 0 );
        //System.assert( ctrl.topSectionClosedOtherAccountCount == 1 );
        //System.assert( ctrl.topSectionOpenOtherAccountCount == 1 );
        
    }
    
    
    static testmethod void testErrorHandling() {
        
        PageReference pageRef = Page.TFSC_AccountHighlights;
        Test.setCurrentPage(pageRef);
        //ApexPages.currentPage().getParameters().put('id', fAcct.Id);
        
        TFSC_AccountHighlightsController ctrl = new TFSC_AccountHighlightsController();
        
    }
    
    
    
    private static Financial_Account__c setupData(Account acct) {
        
        Collateral__c ast = new Collateral__c( name = 'testAsset1' );
        insert ast;
        
        Financial_Account__c financialAccount = new Financial_Account__c(
                                                            Financial_Account_Number__c = '1212', 
                                                            Collateral__c = ast.Id,
                                                            Finance_Account_Status__c = 'Open');
        
        insert financialAccount;
        
        
        Case caseToInsert = new Case(  Financial_Account__c = financialAccount.Id,
                                       RecordTypeId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case')
                                        );
        insert caseToInsert;
        
        
        return financialAccount;
    }
    
    
    /**
    *   @borrowerPosition = 'Co-X' or 'Primary'
    *   @openOrClosed = 'Open' or 'Close'; (yes, close. not closed.) 
    */
    private static Financial_Account_Customer__c generateAndInsertFAC(Id FAId, String borrowerPosition, String openOrClosed, Id AcctId, String randString) {
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c();
        fac.Borrower_Position__c = borrowerPosition;
        fac.Borrower_Status__c = 'Active';
        fac.Financial_Account__c = FAId;
        fac.Account__c = acctId;
        fac.Home_Phone_Garage__c = '4063775012';
        fac.Mobile_Phone__c = '4063775013';
        fac.Work_Phone_Garage__c = '4063775014';
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = 'test';
        fac.FA_Role_Status__c = 'test';
        fac.Financial_Account_Customer__c = 'test' + randString;
        //fac.Finance_Account_Status__c = openOrClosed;
        insert fac;
        
        return fac;
    }
    
    private static void addDummyFACsForCountingOfOtherAccounts(Financial_Account__c fAcct, Id acctId) {
        Financial_Account__c financialAccount2 = new Financial_Account__c(Financial_Account_Number__c = '121212121');
        insert financialAccount2;
        generateAndInsertFAC(financialAccount2.Id, 'Co-X', 'Close', acctId, TFSC_TestUtils.generateRandomString(4));
        generateAndInsertFAC(financialAccount2.Id, 'Co-X', 'Open', acctId, TFSC_TestUtils.generateRandomString(4));
        generateAndInsertFAC(financialAccount2.Id, 'Primary', 'Close', acctId, TFSC_TestUtils.generateRandomString(4));
        generateAndInsertFAC(financialAccount2.Id, 'Primary', 'Open', acctId, TFSC_TestUtils.generateRandomString(4));
    }
    
    
    
    
    
    
}