objects/Collections_Pass_Strategy__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Some code in the SkipTraceController is dependent upon there being records in this CustomSetting with Sort = 3, 4, 6 and 8.  It is best to simply have values for 1-11.  Before changing, check the code for the TFSC_SkipTrace page.</description>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RES__c</fullName>
        <label>RES#</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort__c</fullName>
        <label>Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Collections Pass Strategy</label>
</CustomObject>

objects/CollectionsPassStrategy__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Collections Pass Strategy</label>
    <pluralLabel>Collections Pass Strategies</pluralLabel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collection_List_Number_1__c</fullName>
        <label>Collection List Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_List_Status_1__c</fullName>
        <label>Collection List Status 1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>HomePhone BillTo</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code_Garage__c</fullName>
        <description>Zip Code</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_BillTo__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Bill_To__c</fullName>
        <description>Work Phone Number</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skip_Trace__c.object
<CustomObject>
    <description>Transformed copy of skip trace notes entered in Collections Host PF11 screen and primary
location for creation and maintenance of skip trace information within Salesforce.</description>
    <fields>
        <fullName>Accurint_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accurint Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address1_Source__c</fullName>
        <label>Address1 Source</label>
        <picklist>
            <picklistValues>
                <fullName>System Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved 3rd Party Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iVault</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DMS_Credit_App_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit App Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fast_Data_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fast Data Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Skip Trace</relationshipLabel>
        <relationshipName>Skip_Trace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Innovis_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Innovis Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multiple_Accounts_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multiple Accounts Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multiple_Accounts_Date__c</fullName>
        <label>Multiple Accounts Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Review_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Review Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone1_Source__c</fullName>
        <label>Phone1 Source</label>
        <picklist>
            <picklistValues>
                <fullName>System Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved 3rd Party Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iVault</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone1__c</fullName>
        <label>Phone1</label>
        <type>Phone</type>
    </fields>
    <label>Skip Trace</label>
    <nameField>
        <label>Skip Trace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skip Trace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Toyota_Vendor_Phone_Number__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Phone numbers to be stored in the Name field</description>
    <label>Toyota Vendor Phone Number</label>
</CustomObject>

classes/TFSC_SkipTraceControllerTest.cls
@isTest
private class TFSC_SkipTraceControllerTest {
    
   static testmethod void testFaWithPopulatedSkipTrace() {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c financialAccount = setupData(acct);
        
        Financial_Account_Customer__c fac = generateAndInsertFAC(financialAccount.Id, 'Primary', 'Open', acct.Id);
        Financial_Account_Customer__c coFac = generateAndInsertFAC(financialAccount.Id, 'Co-X', 'Open', acct.Id);
        
        Skip_Trace__c skipTrace = new Skip_Trace__c(Financial_Account__c = financialAccount.Id);
        skipTrace.Address1__c = '1234 addy ST';
        skipTrace.Phone1__c = '4064434043';
        insert skipTrace;
        
        Id collectionCaseId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case');
        Case newCase = new Case(Financial_Account__c = financialAccount.Id, RecordTypeId = collectionCaseId, status='PASS1x');
        insert newCase;
        
        CollectionsPassStrategy__kav helpTextObj = new CollectionsPassStrategy__kav(UrlName = '123', Title = 'test123', Details__c = 'test123', Language = 'en_US');
        insert helpTextObj;
        String articleNum = [select ArticleNumber, id from CollectionsPassStrategy__kav where id = :helpTextObj.Id].ArticleNumber ;
        
        PageReference pageRef = Page.TFSC_SkipTrace;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(financialAccount);
        TFSC_SkipTraceController controllerExt = new TFSC_SkipTraceController(standardController);
        controllerExt.selectedPassStrategy = articleNum;
        controllerExt.populatePhonesAndAddresses();
        
        TFSC_SkipTraceController.generateArticleText( articleNum );
        
        testAddingRemovingPhoneNumber(controllerExt);
        testTimeStampUpdate(controllerExt);
    }
    
    
    static void testTimeStampUpdate(TFSC_SkipTraceController controller) {
        
        String newPhone = '7014457667';
        
        //insert phone
        TFSC_SkipTraceController.PhoneNumberObject tmpPhoneObj = new TFSC_SkipTraceController.PhoneNumberObject(newPhone, 'G - Good Number (C,A)', 'Mobile', 'Innovis', Date.today());
        TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest request = new TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest(tmpPhoneObj);
        request.randomId = '';
        String tempJsonRequest = JSON.serialize(request);
        controller.saveJsonRequest = tempJsonRequest;
        controller.savePhoneLineItem();
        
        TFSC_SkipTraceController.LastCalledTimestampRequestAndResponse request2 = new TFSC_SkipTraceController.LastCalledTimestampRequestAndResponse(tmpPhoneObj);
        request2.randomId = '';
        tempJsonRequest = JSON.serialize(request);
        controller.saveJsonRequest = tempJsonRequest;
        controller.updateTimestamp();
    	
    }
    
    
    
    static testmethod void testSkipTraceController() {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        Toyota_Vendor_Phone_Number__c vendorCS = new Toyota_Vendor_Phone_Number__c(Name = '7015741984');
        insert vendorCS;
        
        Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c financialAccount = setupData(acct);
        
        Financial_Account_Customer__c fac = generateAndInsertFAC(financialAccount.Id, 'Primary', 'Open', acct.Id);
        Financial_Account_Customer__c coFac = generateAndInsertFAC(financialAccount.Id, 'Co-X', 'Open', acct.Id);
        
        Id collectionCaseId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case');
        Case newCase = new Case(Financial_Account__c = financialAccount.Id, RecordTypeId = collectionCaseId, status='PASS1x');
        insert newCase;
        
        CollectionsPassStrategy__kav helpTextObj = new CollectionsPassStrategy__kav(UrlName = '123', Title = 'test123', Details__c = 'test123', Language = 'en_US');
        insert helpTextObj;
        String articleNum = [select ArticleNumber, id from CollectionsPassStrategy__kav where id = :helpTextObj.Id].ArticleNumber ;
        Collections_Pass_Strategy__c passStrat = [Select Article_Number__c from Collections_Pass_Strategy__c limit 1];
        passStrat.Article_Number__c = articleNum;
        update passStrat;
        PageReference pageRef = Page.TFSC_SkipTrace;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(financialAccount);
        TFSC_SkipTraceController controllerExt = new TFSC_SkipTraceController(standardController);
        controllerExt.selectedPassStrategy = articleNum;
        controllerExt.initializeNewSkipTraceRecordAndPopulateData();
        controllerExt.populatePhonesAndAddresses();
        
        testAndValidateCheckboxes(controllerExt);
        testAddingRemovingAddress(controllerExt);
        testAddingRemovingPhoneNumber(controllerExt);
        testUpdatingAltBorrower(controllerExt);
        
    }
    
    private static void testUpdatingAltBorrower(TFSC_SkipTraceController controllerExt) {
        controllerExt.borrowerPhoneFromJS = '4064434044';
        controllerExt.updateAltBorrower();
        
        //validate that phone num is 'top fac';
    }
    
    
    private static String EXISTING_PHONE = '4064434011';
    
    private static void testAddingRemovingPhoneNumber(TFSC_SkipTraceController controllerExt) {
        
        //use existing phone to hit 'disable skip phone' code.
        TFSC_SkipTraceController.PhoneNumberObject tmpPhoneObj = new TFSC_SkipTraceController.PhoneNumberObject(EXISTING_PHONE, 'G - Good Number (C,A)', 'Mobile', 'Innovis', Date.today());
        TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest request = new TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest(tmpPhoneObj);
        request.randomId = '';
        String tempJsonRequest = JSON.serialize(request);
        controllerExt.saveJsonRequest = tempJsonRequest;
        controllerExt.savePhoneLineItem();
        
        tmpPhoneObj = controllerExt.phoneNumList[0];
        request = new TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest(tmpPhoneObj);
        controllerExt.saveJsonRequest = JSON.serialize(request);
        controllerExt.savePhoneLineItem(); //for update
        controllerExt.saveJsonRequest = 'ahrdsfas';
        controllerExt.savePhoneLineItem(); //for save with error
        
        tmpPhoneObj = controllerExt.phoneNumList[0];
        request = new TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest(tmpPhoneObj);
        controllerExt.saveJsonRequest = JSON.serialize(request);
        controllerExt.deletePhoneLineItem(); //for delete
        controllerExt.saveJsonRequest = JSON.serialize('asdvabnaiena');
        controllerExt.deletePhoneLineItem(); //for delete with error
        
        //test vendor phone number update-and-alert
        tmpPhoneObj = new TFSC_SkipTraceController.PhoneNumberObject('7015741984', 'G - Good Number (C,A)', 'Mobile', 'Innovis', Date.today());
        request = new TFSC_SkipTraceController.PhoneNumberSaveResponseAndRequest(tmpPhoneObj);
        request.randomId = '';
        controllerExt.saveJsonRequest = JSON.serialize(request);
        controllerExt.savePhoneLineItem();
    }
    
    
    private static void testAddingRemovingAddress(TFSC_SkipTraceController controllerExt) {
        TFSC_SkipTraceController.AddressHistory addyObj = new TFSC_SkipTraceController.AddressHistory('1234 addy ST', 'Innovis', '1/1 - 12/12');
        TFSC_SkipTraceController.AddyJsonResponseAndRequest request = new TFSC_SkipTraceController.AddyJsonResponseAndRequest();
        request.updateValuesFromAddyObj(addyObj);
        request.randomId = '';
        
        controllerExt.saveAddyJsonRequest = JSON.serialize(request);
        controllerExt.saveAddress();
        
        addyObj = controllerExt.addressHistory[0];
        request.updateValuesFromAddyObj(addyObj);
        controllerExt.saveAddyJsonRequest = JSON.serialize(request);
        controllerExt.saveAddress(); //for update
        controllerExt.saveAddyJsonRequest = 'asdf';
        controllerExt.saveAddress(); //for update with error
        
        addyObj = controllerExt.addressHistory[0];
        request.updateValuesFromAddyObj(addyObj);
        request.randomId = '';
        controllerExt.saveAddyJsonRequest = JSON.serialize(request);
        controllerExt.saveAddress(); //for duplicate phone check.
        
        addyObj = controllerExt.addressHistory[0];
        request.updateValuesFromAddyObj(addyObj);
        controllerExt.saveAddyJsonRequest = JSON.serialize(request);
        controllerExt.deleteAddress(); //for delete
        controllerExt.saveAddyJsonRequest = 'asdhab';
        controllerExt.deleteAddress(); //for delete with error.
    }
    
    private static void testAndValidateCheckboxes(TFSC_SkipTraceController controllerExt) {
        controllerExt.contextSkipTrace.Multiple_Accounts_Checkbox__c = true;
        controllerExt.contextSkipTrace.DMS_Credit_App_Checkbox__c = true;
        controllerExt.contextSkipTrace.Payment_Review_Checkbox__c = true;
        controllerExt.contextSkipTrace.Innovis_Checkbox__c = true;
        controllerExt.contextSkipTrace.Accurint_Checkbox__c = true;
        controllerExt.contextSkipTrace.Fast_Data_Checkbox__c = true;
        
        controllerExt.saveAfterFieldValueChange();
        
        System.assert( (controllerExt.contextSkipTrace.Multiple_Accounts_Date__c != null) );
    }
    
    
    
    private static Financial_Account__c setupData(Account acct) {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = randomString);
        financialAccount.Collection_List_Number_1__c = '1704'; // for FPD
        financialAccount.History_Counter_Days_Past_Due__c = '10';
        insert financialAccount;
        
        
        Collections_Pass_Strategy__c passStrat = new Collections_Pass_Strategy__c(Name = 'Test1', Sort__c = 1, Article_Number__c = '1', Account_Type__c = 'General', RES__c = 'RES1');
        Collections_Pass_Strategy__c passStrat2 = new Collections_Pass_Strategy__c(Name = 'Test2', Sort__c = 2, Article_Number__c = '2', Account_Type__c = 'General', RES__c = 'RES2');
        Collections_Pass_Strategy__c passStrat3 = new Collections_Pass_Strategy__c(Name = 'Test3', Sort__c = 3, Article_Number__c = '3', Account_Type__c = 'General', RES__c = 'RES3');
        Collections_Pass_Strategy__c passStrat4 = new Collections_Pass_Strategy__c(Name = 'Test4', Sort__c = 4, Article_Number__c = '4', Account_Type__c = 'General', RES__c = 'RES4');
        Collections_Pass_Strategy__c passStrat5 = new Collections_Pass_Strategy__c(Name = 'Test5', Sort__c = 5, Article_Number__c = '5', Account_Type__c = 'General', RES__c = 'RES5');
        insert new Collections_Pass_Strategy__c[]{passStrat, passStrat2, passStrat3, passStrat4, passStrat5};
        
        
        return financialAccount;
    }
    private static Financial_Account_Customer__c generateAndInsertFAC(Id FAId, String borrowerPosition, String openOrClosed, Id AcctId) {
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c();
        fac.Borrower_Position__c = borrowerPosition;
        fac.Borrower_Status__c = 'Active';
        fac.Financial_Account__c = FAId;
        fac.Account__c = acctId;
        fac.Mailing_State_BillTo__c = 'CO';
        fac.Mailing_Postal_Code_Garage__c = '80524';
        
        fac.Work_Phone_Garage__c = EXISTING_PHONE;
        fac.Mobile_Phone__c = EXISTING_PHONE;
        fac.Home_Phone_Garage__c = EXISTING_PHONE;
        fac.Work_Phone_Bill_To__c = EXISTING_PHONE;
        fac.HomePhone_BillTo__c = EXISTING_PHONE;
        
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = 'test';
        fac.FA_Role_Status__c = 'test';
        fac.Financial_Account_Customer__c = 'test2' + TFSC_TestUtils.generateRandomString(4);
        //fac.Finance_Account_Status__c = openOrClosed;
        insert fac;
        
        return fac;
    }
    
 static testmethod void testFaWithPopulatedSkipTrace1() {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c financialAccount = setupData(acct);
        
        Financial_Account_Customer__c fac = generateAndInsertFAC(financialAccount.Id, 'Primary', 'Open', acct.Id);
        Financial_Account_Customer__c coFac = generateAndInsertFAC(financialAccount.Id, 'Co-X', 'Open', acct.Id);
        
        Skip_Trace__c skipTrace = new Skip_Trace__c(Financial_Account__c = financialAccount.Id);
        skipTrace.Address1__c = '1234 addy ST';
        skipTrace.Phone1__c = '4064434043';
        skipTrace.Phone1_Source__c = 'Innovis';
     skipTrace.Address1_Source__c = 'Innovis';
        insert skipTrace;
        
        Id collectionCaseId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case');
        Case newCase = new Case(Financial_Account__c = financialAccount.Id, RecordTypeId = collectionCaseId, status='PASS1x');
        insert newCase;
        
        CollectionsPassStrategy__kav helpTextObj = new CollectionsPassStrategy__kav(UrlName = '123', Title = 'test123', Details__c = 'test123', Language = 'en_US');
        insert helpTextObj;
        String articleNum = [select ArticleNumber, id from CollectionsPassStrategy__kav where id = :helpTextObj.Id].ArticleNumber ;
        Collections_Pass_Strategy__c passStrat = [Select Article_Number__c from Collections_Pass_Strategy__c where RES__c = 'RES3' limit 1];
        passStrat.Article_Number__c = articleNum;
        update passStrat;
        PageReference pageRef = Page.TFSC_SkipTrace;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(financialAccount);
        TFSC_SkipTraceController controllerExt = new TFSC_SkipTraceController(standardController);
        controllerExt.selectedPassStrategy = articleNum;
        controllerExt.populatePhonesAndAddresses();
        
        TFSC_SkipTraceController.generateArticleText( articleNum );
        
        testAndValidateCheckboxes(controllerExt);
        testAddingRemovingAddress(controllerExt);
        testAddingRemovingPhoneNumber(controllerExt);
        testUpdatingAltBorrower(controllerExt);
        testTimeStampUpdate(controllerExt);
    }   
    
    static testmethod void testFaWithPopulatedSkipTrace2() {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c financialAccount = setupData(acct);
        financialAccount.Collection_List_Number_1__c = '1704';
        financialAccount.Collection_List_Status_1__c = 'A';
        update financialAccount;
        Financial_Account_Customer__c fac = generateAndInsertFAC(financialAccount.Id, 'Primary', 'Open', acct.Id);
        Financial_Account_Customer__c coFac = generateAndInsertFAC(financialAccount.Id, 'Co-X', 'Open', acct.Id);
        
        Skip_Trace__c skipTrace = new Skip_Trace__c(Financial_Account__c = financialAccount.Id);
        skipTrace.Address1__c = '1234 addy ST';
        skipTrace.Phone1__c = '4064434043';
        skipTrace.Phone1_Source__c = 'Innovis';
     skipTrace.Address1_Source__c = 'Innovis';
        insert skipTrace;
        
        Id collectionCaseId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case');
        Case newCase = new Case(Financial_Account__c = financialAccount.Id, RecordTypeId = collectionCaseId, status='PASS1x');
        insert newCase;
        
        CollectionsPassStrategy__kav helpTextObj = new CollectionsPassStrategy__kav(UrlName = '123', Title = 'test123', Details__c = 'test123', Language = 'en_US');
        insert helpTextObj;
        String articleNum = [select ArticleNumber, id from CollectionsPassStrategy__kav where id = :helpTextObj.Id].ArticleNumber ;
        Collections_Pass_Strategy__c passStrat = [Select Article_Number__c from Collections_Pass_Strategy__c where RES__c = 'RES3' limit 1];
        passStrat.Article_Number__c = articleNum;
        update passStrat;
        PageReference pageRef = Page.TFSC_SkipTrace;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(financialAccount);
        TFSC_SkipTraceController controllerExt = new TFSC_SkipTraceController(standardController);
        
    }
    
    static testmethod void testFaWithPopulatedSkipTrace3() {
        
        String randomString = TFSC_TestUtils.generateRandomString(6);
        
        Account acct = new Account(name = 'test' + randomString);
        insert acct;
        
        Financial_Account__c financialAccount = setupData(acct);
        financialAccount.Collection_List_Number_1__c = '1800';
        financialAccount.Collection_List_Status_1__c = 'A';
        update financialAccount;
        Financial_Account_Customer__c fac = generateAndInsertFAC(financialAccount.Id, 'Primary', 'Open', acct.Id);
        Financial_Account_Customer__c coFac = generateAndInsertFAC(financialAccount.Id, 'Co-X', 'Open', acct.Id);
        
        Skip_Trace__c skipTrace = new Skip_Trace__c(Financial_Account__c = financialAccount.Id);
        skipTrace.Address1__c = '1234 addy ST';
        skipTrace.Phone1__c = '4064434043';
        skipTrace.Phone1_Source__c = 'Accurint';
     skipTrace.Address1_Source__c = 'Accurint';
        insert skipTrace;
        
        Id collectionCaseId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Collection', 'Case');
        Case newCase = new Case(Financial_Account__c = financialAccount.Id, RecordTypeId = collectionCaseId, status='PASS1x');
        insert newCase;
        
        CollectionsPassStrategy__kav helpTextObj = new CollectionsPassStrategy__kav(UrlName = '123', Title = 'test123', Details__c = 'test123', Language = 'en_US');
        insert helpTextObj;
        String articleNum = [select ArticleNumber, id from CollectionsPassStrategy__kav where id = :helpTextObj.Id].ArticleNumber ;
        Collections_Pass_Strategy__c passStrat = [Select Article_Number__c from Collections_Pass_Strategy__c where RES__c = 'RES4' limit 1];
        passStrat.Article_Number__c = articleNum;
        update passStrat;
        PageReference pageRef = Page.TFSC_SkipTrace;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController standardController = new ApexPages.StandardController(financialAccount);
        TFSC_SkipTraceController controllerExt = new TFSC_SkipTraceController(standardController);
        
    }
    
}