objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerPersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Account - Parent of Weblogin contact</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Weblogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Borrower_Number__c</fullName>
        <description>First Character of Customer_role_Type</description>
        <formula>LEFT(Customer_Role_Type__c, 1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Borrower Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weblogin_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Weblogin Contact stores the contact id of the weblogin register to this FinAcctCustomer Record.
Null if no Weblogin Contact is register.

Customer Community will allow weblogin customer to read this record</description>
        <label>Weblogin Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_Weblogin_Register.cls
public class TFSC_Weblogin_Register extends TFSC_Weblogin_Base{
    
    public WebLoginWebServiceReply execute(String SGUID, String FinancialAccountNumber, String FinancialAccountBorrowerNumber) {
        
        Contact webloginContact = findWebloginContactBySGUID(SGUID);
        
        if (webloginContact == null) {
        	return new WebLoginWebServiceReply(-1,'TFSC_Weblogin_Register cannot match SGUID - '+SGUID);
        }
        
        //find the parent customerAccount
        Id parentCustomerAccount = webloginContact.CustomerPersonAccount__c;
          
          
        //find the FA
        List<Financial_Account__c> faList = [
            select id
            from Financial_Account__c
            where Financial_Account_Number__c = :FinancialAccountNumber
        ];
        
        if (faList.size()  <> 1) {
            return new WebLoginWebServiceReply(-1,'TFSC_Weblogin_Register cannot find FA to register - '+FinancialAccountNumber);
        }
        
        Id financialAccountId = faList[0].Id;
        
        //get the FAC record
        List<Financial_Account_Customer__c> facList = [
            select id, Account__c, Weblogin_Contact__c
            from Financial_Account_Customer__c
            where Financial_Account__c = :financialAccountId
            and Customer_Borrower_Number__c = :FinancialAccountBorrowerNumber
        ];
        
        if (facList.size() <> 1) {
            //cannot find the customerPersonAccount - data problem
            return new WebLoginWebServiceReply(-1,'cannot use FinancialAccountNumber & FinancialAccountBorrowerNumber to find Financial_Account_Customer__c. Aborting');
        }
        
        Financial_Account_Customer__c fac = facList[0];
        
        /*//check if FinancialAccountNumber & FinancialAccountBorrowerNumber belongs to the same parent customerAccount
        if ( fac.Account__c <> parentCustomerAccount) {
            // we have a data consistency issue - abort now
            return new WebLoginWebServiceReply(-1,'TFSC_Weblogin_Register : Data consistency issue for SGUID '+ SGUID);
        }   */
        
        //update the FAC record with the webloginPersonAccount.contactId
        fac.Weblogin_Contact__c = webloginContact.Id;
        System.Debug('TFSC_Weblogin_Register : SGUID = '+SGUID+'   webloginAccount.PersonContactId = '+ webloginContact.Id);
        update fac;
        
        return new WebLoginWebServiceReply(0,'TFSC_Weblogin_Register : register SGUID '+SGUID+' to FAC '+fac.id+' is successful' +
             '  webloginAccount.PersonContactId = '+ webloginContact.Id);
    }
}