objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Weblogin</fullName>
        <active>true</active>
        <description>Record type for customer community web login for TFS or LFS</description>
        <label>Weblogin</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weblogin_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Weblogin Contact stores the contact id of the weblogin register to this FinAcctCustomer Record.
Null if no Weblogin Contact is register.

Customer Community will allow weblogin customer to read this record</description>
        <label>Weblogin Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>WebLogin</fullName>
        <active>true</active>
        <description>PersonAccount to Enable Multiple Web Logins for a customer.  Will be used to enable Customer Community user</description>
        <label>Web Login</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_Weblogin_Unregister.cls
public class TFSC_Weblogin_Unregister extends TFSC_Weblogin_Base {

	public  WebLoginWebServiceReply execute(String SGUID, String FinancialAccountNumber) {
	
		//get the weblogin PersonAccount contact id
		Contact webloginContact = findWebloginContactBySGUID(SGUID);
		
		if (webloginContact == null) {
			return new WebLoginWebServiceReply(-1, SGUID + ' is not a valid SGUID on Contact of RecType Weblogin');
		}
		
		
		//find the FA
		List<Financial_Account__c> faList = [
			select id
			from Financial_Account__c
			where Financial_Account_Number__c = :FinancialAccountNumber
		];
		
		if (faList.size()  <> 1) {
			return new WebLoginWebServiceReply(-1,'TFSC_Weblogin_Unregister cannot find FA to unregister - '+FinancialAccountNumber);
		}
		
		Id financialAccountId = faList[0].Id;
		
			
		List<Financial_Account_Customer__c> facList = [
			select id, Weblogin_Contact__c
			from Financial_Account_Customer__c
			where Financial_Account__c = :financialAccountId
			and Weblogin_Contact__c = :webloginContact.Id
		];
		
		
		//update the FAC record by removing the weblogin contact id
		if ( facList.size() <> 1) {
			return new WebLoginWebServiceReply(-1,'TFSC_Weblogin_Unregister cannot find FAC with SGUID to unregister - '+FinancialAccountNumber+' : '+SGUID);
		}
		
		Financial_Account_Customer__c fac = facList[0];
		fac.Weblogin_Contact__c = null;
		update fac;
		
		return new WebLoginWebServiceReply(0,'TFSC_Weblogin_Unregister completed  - '+FinancialAccountNumber+' : '+SGUID);
	}
}