objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CustomerPersonAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Account - Parent of Weblogin contact</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Weblogins</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGUID__c</fullName>
        <description>Unique federation identifier provided by TFSWeb IDP</description>
        <externalId>true</externalId>
        <label>SGUID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Web_CompanyName__c</fullName>
        <label>Company Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_DeProvisioned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Web DeProvisioned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Web_UserId__c</fullName>
        <label>Web UserId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weblogin_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Weblogin Contact stores the contact id of the weblogin register to this FinAcctCustomer Record.
Null if no Weblogin Contact is register.

Customer Community will allow weblogin customer to read this record</description>
        <label>Weblogin Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_Weblogin_Base.cls
public virtual class TFSC_Weblogin_Base {


	public User findUserBySGUID(String SGUID) {
		// find Community User record with Federation id = SGUID
		List<User> users = [
			SELECT LastLoginDate, IsActive, LastName, FirstName, FederationIdentifier, Name, ProfileId
			FROM User 
			WHERE FederationIdentifier =:SGUID
		];
		
		// return -1 if not found
		if (users.size() <> 1) {
			return null;
		} else {
			return users[0];
		}
		
	}
	
	public Contact findWebloginContactBySGUID(String SGUID) {
		List<Contact> contacts = [
			select id, CustomerPersonAccount__c, Web_CompanyName__c, Web_UserId__c, Web_DeProvisioned__c,
				FirstName, LastName, Email, SGUID__c
			from Contact
			where SGUID__c = :SGUID
			and RecordTypeId = :RecordTypeModel.ContactWebLoginRecTypeId
		];
		
		if (contacts.size() <> 1) {
			return null;
		} else {  
			return contacts[0];
		}
	}
	
	public List<Financial_Account_Customer__c> findFinancialAccountCustomerListByWebloginContactId(String webloginContactId) {
		List<Financial_Account_Customer__c> facList = [
			select Id
			from Financial_Account_Customer__c
			where Weblogin_Contact__c = :webloginContactId
		];
		
		return facList;
	}

	//protected List<Financial_Account__c> find
}