objects/Dailight_Savings_Periods__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Dailight_Savings_In_Effect__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether dailight savings apply to the period of time</description>
        <label>Dailight Savings In Effect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Period end date (included)</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Period start date (included)</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Dailight Savings Periods</label>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>History_Counter_Days_Past_Due__c</fullName>
        <description>&quot;DPD</description>
        <label>Days Past Due</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>HomePhone BillTo</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Past_Due__c</fullName>
        <description>Past due amount</description>
        <label>Past Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date_Next__c</fullName>
        <description>next due payment date</description>
        <label>Payment Date Next</label>
        <type>Date</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_Phone_No_Call_Reason_Code_Garage__c</fullName>
        <label>Home Phone No-Call Reason Code Garage</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code_Garage__c</fullName>
        <description>Zip Code</description>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone_No_Call_Reason_Code__c</fullName>
        <label>Mobile Phone No-Call Reason Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Bill_To__c</fullName>
        <description>Work Phone Number</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TimeZone_Indicator__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping the garage zip code ranges to Timezone</description>
    <fields>
        <fullName>GMT_From_With_Daylight_Saving__c</fullName>
        <inlineHelpText>Format hh:mm:ss</inlineHelpText>
        <label>GMT From With Daylight Saving</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMT_From_Without_Daylight_Saving__c</fullName>
        <inlineHelpText>Format hh:mm:ss</inlineHelpText>
        <label>GMT From Without Daylight Saving</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMT_Till_With_Daylight_Saving__c</fullName>
        <inlineHelpText>Format hh:mm:ss</inlineHelpText>
        <label>GMT Till With Daylight Saving</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GMT_Till_Without_Daylight_Saving__c</fullName>
        <inlineHelpText>Format hh:mm:ss</inlineHelpText>
        <label>GMT Till Without Daylight Saving</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Higher_Range_of_Zip_Code__c</fullName>
        <label>Higher Range of Zip Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lower_Range_of_Zip_Code__c</fullName>
        <label>Lower Range of Zip Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Observe_Daylight_Saving__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Observe Daylight Saving</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Timezone_Indicator__c</fullName>
        <label>Timezone Indicator</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The closest representation in terms of GMT offset of the time zone that Salesforce maintains as a user-selectable time zone on their detail record, i.e. America/Los_Angeles, America/Denver, America/Chicago, and America/New_York.</description>
        <label>Timezone</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>TimeZone Indicator</label>
</CustomObject>

classes/TFSC_UtilsTest.cls
@isTest
private class TFSC_UtilsTest {

    static testMethod void isDailightSavingsPeriodTest() {
        
        // Create Dailight_Savings_Periods__c
        List<Dailight_Savings_Periods__c> listOfDailightSavingsPeriod = new List<Dailight_Savings_Periods__c>();
        Dailight_Savings_Periods__c dailightSavingsPeriod_1 = new Dailight_Savings_Periods__c(
            Name = 'FIRST_DAILIGHT_SAVING',
            Start_Date__c = Date.newInstance(2014, 2, 22),
            End_Date__c = Date.newInstance(2014, 8, 21),
            Dailight_Savings_In_Effect__c = true
        );
        Dailight_Savings_Periods__c dailightSavingsPeriod_2 = new Dailight_Savings_Periods__c(
            Name = 'FIRST_NON_DAILIGHT_SAVING',
            Start_Date__c = Date.newInstance(2014, 8, 22),
            End_Date__c = Date.newInstance(2015, 2, 21),
            Dailight_Savings_In_Effect__c = false
        );
        listOfDailightSavingsPeriod.add(dailightSavingsPeriod_1);
        listOfDailightSavingsPeriod.add(dailightSavingsPeriod_2);
        insert listOfDailightSavingsPeriod;
        
        Date currentDate = Date.newInstance(2014, 3, 10);
        System.assertEquals(TFSC_Utils.isDailightSavingsPeriod(currentDate), true);
        
        currentDate = Date.newInstance(2014, 10, 10);
        System.assertEquals(TFSC_Utils.isDailightSavingsPeriod(currentDate), false);
        
        currentDate = Date.newInstance(2015, 8, 10);
        System.assertEquals(TFSC_Utils.isDailightSavingsPeriod(currentDate), false);
        
    }
    
    static testMethod void getEnablePhoneNumberDependingOnTimeZoneTest() {
    
        // Create Dailight_Savings_Periods__c
        List<Dailight_Savings_Periods__c> listOfDailightSavingsPeriod = new List<Dailight_Savings_Periods__c>();
        Dailight_Savings_Periods__c dailightSavingsPeriod_1 = new Dailight_Savings_Periods__c(
            Name = 'FIRST_DAILIGHT_SAVING',
            Start_Date__c = Date.newInstance(2014, 2, 22),
            End_Date__c = Date.newInstance(2014, 8, 21),
            Dailight_Savings_In_Effect__c = true
        );
        Dailight_Savings_Periods__c dailightSavingsPeriod_2 = new Dailight_Savings_Periods__c(
            Name = 'FIRST_NON_DAILIGHT_SAVING',
            Start_Date__c = Date.newInstance(2014, 8, 22),
            End_Date__c = Date.newInstance(2015, 2, 21),
            Dailight_Savings_In_Effect__c = false
        );
        listOfDailightSavingsPeriod.add(dailightSavingsPeriod_1);
        listOfDailightSavingsPeriod.add(dailightSavingsPeriod_2);
        insert listOfDailightSavingsPeriod;
    
        // Create timezone indicator
        List<TimeZone_Indicator__c> listOfTimeZoneIndicators = new List<TimeZone_Indicator__c>();
        TimeZone_Indicator__c timezoneIndicator_1 = new TimeZone_Indicator__c(
            Name = '90000',
            Higher_Range_of_Zip_Code__c = 90099,
            Lower_Range_of_Zip_Code__c = 90000,
            Timezone__c = 'PACIFIC',
            Timezone_Indicator__c = 'PST',
            GMT_Till_Without_Daylight_Saving__c = '',
            GMT_From_Without_Daylight_Saving__c = '',
            GMT_Till_With_Daylight_Saving__c = '',
            GMT_From_With_Daylight_Saving__c = '',
            Observe_Daylight_Saving__c = true
        );
        TimeZone_Indicator__c timezoneIndicator_2 = new TimeZone_Indicator__c(
            Name = '90100',
            Higher_Range_of_Zip_Code__c = 90199,
            Lower_Range_of_Zip_Code__c = 90100,
            Timezone__c = 'PACIFIC',
            Timezone_Indicator__c = 'PST',
            GMT_Till_Without_Daylight_Saving__c = '',
            GMT_From_Without_Daylight_Saving__c = '',
            GMT_Till_With_Daylight_Saving__c = '',
            GMT_From_With_Daylight_Saving__c = '',
            Observe_Daylight_Saving__c = true
        );
        
        TimeZone_Indicator__c timezoneIndicator_3 = new TimeZone_Indicator__c(
            Name = '90200',
            Higher_Range_of_Zip_Code__c = 90299,
            Lower_Range_of_Zip_Code__c = 90200,
            Timezone__c = 'PACIFIC',
            Timezone_Indicator__c = 'PST',
            GMT_Till_Without_Daylight_Saving__c = '',
            GMT_From_Without_Daylight_Saving__c = '',
            GMT_Till_With_Daylight_Saving__c = '',
            GMT_From_With_Daylight_Saving__c = '',
            Observe_Daylight_Saving__c = true
        );
        
        listOfTimeZoneIndicators.add(timezoneIndicator_1);
        listOfTimeZoneIndicators.add(timezoneIndicator_2);
        listOfTimeZoneIndicators.add(timezoneIndicator_3);
        insert listOfTimeZoneIndicators;
        
    } 
    
    static testMethod void getEnablePhoneNumberInSkipTraceTableTest(){
        String hStatus = 'H - H_Status';
        String nStatus = 'N - N_Status';
        String gStatus = 'G - G_Status';
        String emptyStatus = '';
        
        System.assertEquals(TFSC_Utils.getEnablePhoneNumberInSkipTraceTable(hStatus), false);
        System.assertEquals(TFSC_Utils.getEnablePhoneNumberInSkipTraceTable(nStatus), false);
        System.assertEquals(TFSC_Utils.getEnablePhoneNumberInSkipTraceTable(gStatus), true);
        System.assertEquals(TFSC_Utils.getEnablePhoneNumberInSkipTraceTable(emptyStatus), true);
    }
    
    static testMethod void getListDisplayFACNumbersTest(){
    
        List<Account> listAccounts = new List<Account>();
        listAccounts.add(new Account(name = 'Primary'));
        listAccounts.add(new Account(name = 'CoBorrower'));
        
        insert listAccounts;
        
        Financial_Account__c financialAccount = new Financial_Account__c(
            Financial_Account_Number__c = '12345',
            Payment_Amount_Past_Due__c = 300,
            Payment_Date_Next__c = date.newInstance(2015, 2, 17),
            History_Counter_Days_Past_Due__c = '51'
        );
        insert financialAccount;
    
        List<Financial_Account_Customer__c> listFACustomers = new List<Financial_Account_Customer__c>();
        Financial_Account_Customer__c financialAccountCustomer_1 = new Financial_Account_Customer__c(
            HomePhone_BillTo__c = '7014478311',
            Work_Phone_Bill_To__c = '7014833222',
            Mobile_Phone__c = '7014478333',
            Mailing_Postal_Code_Garage__c = '90240',
            Home_Phone_No_Call_Reason_Code_Garage__c = 'D',
            Mobile_Phone_No_Call_Reason_Code__c = 'K',
            Financial_Account__c = financialAccount.Id,
            Account__c = listAccounts.get(0).Id,
            Borrower_Position__c = 'Primary',
            Borrower_Status__c = 'Active',
            Customer_Role_Type__c = 'test',
            FA_Role_Status__c = 'test',
            Financial_Account_Customer__c = 'test2asdf'
        );
        Financial_Account_Customer__c financialAccountCustomer_2 = new Financial_Account_Customer__c(
            HomePhone_BillTo__c = '7014478332',
            Work_Phone_Bill_To__c = '7014478331',
            Mobile_Phone__c = '7014478334',
            Financial_Account__c = financialAccount.Id,
            Account__c = listAccounts.get(1).Id,
            Borrower_Position__c = 'Co-X',
            Borrower_Status__c = 'Active',
            Customer_Role_Type__c = 'test',
            FA_Role_Status__c = 'test',
            Financial_Account_Customer__c = 'test24asdf'
        );
        
        listFACustomers.add(financialAccountCustomer_1);
        listFACustomers.add(financialAccountCustomer_2);
        insert listFACustomers;
        
        TimeZone_Indicator__c timezoneIndicator_1 = new TimeZone_Indicator__c(
            Name = '90200',
            Higher_Range_of_Zip_Code__c = 90299,
            Lower_Range_of_Zip_Code__c = 90200,
            Timezone__c = 'PACIFIC',
            Timezone_Indicator__c = 'PST',
            GMT_Till_Without_Daylight_Saving__c = '23:59',
            GMT_From_Without_Daylight_Saving__c = '00:01',
            GMT_Till_With_Daylight_Saving__c = '23:59',
            GMT_From_With_Daylight_Saving__c = '00:01',
            Observe_Daylight_Saving__c = true
        );
        insert timezoneIndicator_1;
        
        List<Boolean> listOfResults = new List<Boolean>();
        
        Test.startTest();
        listOfResults = TFSC_Utils.getListDisplayFACNumbers(financialAccountCustomer_1);
        Test.stopTest();
        
        System.assertEquals(listOfResults.get(0), false);
        System.assertEquals(listOfResults.get(1), true);
        System.assertEquals(listOfResults.get(2), true);
    
    }
}