objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Render Form Service Error Description</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Render Form Service Status (Success, Failure)</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RL_DocReqStatusChangeTriggerTest.cls
@isTest
private class RL_DocReqStatusChangeTriggerTest {
	
	
	static testmethod void testTrigger() {
		
		Case caze = new Case(recordTypeId = TFSC_Utils.getRecordTypeIdFromNameAndsObjectName('Rights Letter','Case'));
		insert caze;
		
		Document_Request__c docRequest = new Document_Request__c(status__c = 'test', case__c = caze.Id);
		insert docRequest;
		
		test.startTest();
			
			docRequest.status__c = 'ERROR';
			docRequest.Code__c = 'ERR';
			docRequest.Message__c = 'Error Recieved';
			docRequest.Description__c = 'Error Description Test';
			
			update docRequest;
			
		test.stopTest();
		
	}
	
	
}