objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>Days_Till_Sale__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Identifies the minimum number of days required between notice date and legal sale date.</description>
        <label>Days Till Sale</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Calendar__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Basis for time measurement in calculating legal sale date (Calendar, Business).</description>
        <label>Sale Calendar</label>
        <picklist>
            <picklistValues>
                <fullName>Calendar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The earliest date by which TFS may sell a repossessed vehicle. Calculated date based upon the proposed notice date and adding days as defined in the related form rule record.</description>
        <label>Proposed Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_Notice_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Calculated date to print on letter. Usually today&apos;s date, but may be advanced to next business day by code if mailing cutoff time has passed. Mailing cutoff times are specified in RL_Mail_Cutoff... custom labels.</description>
        <label>Proposed Notice Date</label>
        <type>Date</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_RepossessionTriggerHandler.cls
/*****
 * Salesforce.com Success Services
 * Name: RL_RepossessionTriggerHandler
 * Description: Handler class for Repossession Trigger to reject updates from iRepo and UR after Doc request was created and to compute the legal sale date.
 */

public with sharing class RL_RepossessionTriggerHandler implements TFSC_TriggerDispatcher.Handler{
    private List<Repossession__c> newRepoList = (List<Repossession__c>)Trigger.new;
    private Map<Id,Repossession__c> newRepoMap = (Map<Id,Repossession__c>)Trigger.NewMap;
    private Map<Id,Repossession__c> oldRepoMap = (Map<Id,Repossession__c>)Trigger.oldMap;
        
    private Map<Id, Repossession__c> caseIdRepoMap = new Map<Id, Repossession__c>();
    private Map<Repossession__c, Case> repoCaseMap = new Map<Repossession__c, Case>();
    private Map<Id, Repossession__c> ruleIdRepoMap = new Map<Id, Repossession__c>();
    private Map<Repossession__c, Form_Rule__c> repoFormRuleMap = new Map<Repossession__c, Form_Rule__c>();
    private Repossession__c readOnlyRepo;
    private DateTime legalSaleDateTime = null;
    private Time aTime = Time.newInstance(1, 0, 0, 0);    

    private List<Schema.FieldSetMember> unitedRoadFields = SObjectType.Repossession__c.FieldSets.United_Road.getFields();
    private List<Schema.FieldSetMember> iRepoFields = SObjectType.Repossession__c.FieldSets.iRepo.getFields();

    public void handle() {
        // Block updates from iRepo and UR if a document request exists for this repossession
        if (Trigger.isUpdate) {
            for (Document_Request__c docRequest : [SELECT Id, Repossession__c FROM Document_Request__c WHERE Repossession__c =: newRepoList]) {
                readOnlyRepo = (Repossession__c) newRepoMap.get(docRequest.Repossession__c);

                //United Road fields
                for (Schema.FieldSetMember fs : unitedRoadFields) {
                    readOnlyRepo.put(fs.getFieldPath(), oldRepoMap.get(docRequest.Repossession__c).get(fs.getFieldPath()));
                }

                //iRepo Fields
                for (Schema.FieldSetMember iRepoFs : iRepoFields) {
                    readOnlyRepo.put(iRepoFs.getFieldPath(), oldRepoMap.get(docRequest.Repossession__c).get(iRepoFs.getFieldPath()));
                }
            }
        }
        
        // Build CaseID to Repossession sObject dictionary
        for (Repossession__c repo : newRepoList) {
            if ((repo.Proposed_Notice_Date__c != null && oldRepoMap == null) || (oldRepoMap != null && repo.Proposed_Notice_Date__c != oldRepoMap.get(repo.Id).Proposed_Notice_Date__c)) {
                caseIdRepoMap.put(repo.Case__c, repo);
            }
        }

        // Build Repossession to Case sObject dictionary
        for (Case aCase : [Select Id, Form_Rule__c, Financial_Account__c, BusinessHours.Id FROM Case where Id in : caseIdRepoMap.keySet()]) {
            repoCaseMap.put(caseIdRepoMap.get(aCase.Id), aCase);
            ruleIdRepoMap.put(aCase.Form_Rule__c, caseIdRepoMap.get(aCase.Id)); // !!!!!!!!!!!!!!!!
        }

        // Build Repossession to Form Rule sObject dictionary
        for (Form_Rule__c rule : [SELECT Id, Sale_Calendar__c, Days_Till_Sale__c from Form_Rule__c WHERE Id in : ruleIdRepoMap.keySet()]) {
            repoFormRuleMap.put(ruleIdRepoMap.get(rule.Id), rule);
        }

        // Compute Legal sale date on repossession
        for (Repossession__c repo : repoFormRuleMap.keySet()) {
            //Business Days
            if (repoFormRuleMap.get(repo).Sale_Calendar__c.equalsIgnoreCase(RL_Constants.NOTICE_CALENDAR_BUSINESS)) {
                legalSaleDateTime = RL_Utility.AddBusinessDays(DateTime.newInstance(repo.Proposed_Notice_Date__c, aTime), Integer.valueOf(repoFormRuleMap.get(repo).Days_Till_Sale__c), repoCaseMap.get(repo).BusinessHours.Id);

            //Calendar Days
            }  else if (repoFormRuleMap.get(repo).Sale_Calendar__c.equalsIgnoreCase(RL_Constants.NOTICE_CALENDAR_CALENDAR)) {
                legalSaleDateTime = (repo.Proposed_Notice_Date__c).addDays(Integer.valueOf(repoFormRuleMap.get(repo).Days_Till_Sale__c));
            }
            repo.Proposed_Legal_Sale_Date__c = Date.valueOf(legalSaleDateTime);
        }
    }
}