objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Render Form Service Status (Success, Failure)</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RL_Bankruptcy_Status__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Used in the Rights Letters process. When the Financial Account is in an active or discharged bankruptcy status, this indicates the individual borrower&apos;s BK status, where it may be the same or different from the account&apos;s.</description>
        <inlineHelpText>Used in the Rights Letters process. When the Financial Account is in an active or discharged bankruptcy status, this indicates the individual borrower&apos;s BK status, where it may be the same or different from the account&apos;s.</inlineHelpText>
        <label>Bankruptcy Status</label>
        <picklist>
            <picklistValues>
                <fullName>Filing Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Filing Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to align Form Rule with the case.</description>
        <label>State of Jurisdiction</label>
        <type>TextArea</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Auction_Agency_City__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction city at which repossession is scheduled to be sold.</description>
        <label>Auction Agency City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Name__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction name at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Phone__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction phone at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_State__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction state at which repossession is scheduled to be sold.</description>
        <label>Auction Agency State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street1__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 1 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Street2__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction street address line 2 at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Street2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auction_Agency_Zip__c</fullName>
        <description>SRC: United Road
INT: United Road TIBCO Callout
Trans: N
BU: RL
FD: Auction zip code at which repossession is scheduled to be sold.</description>
        <label>Auction Agency Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BK_Active_or_Discharged__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to indicate whether the financial account is in an active or discharged bankruptcy status. Used by Apex classes (generate doc request and validate repossession) to validate whether all related FACs have been assigned a bankruptcy status.</description>
        <formula>IF(CASE(Financial_Account__r.Bankruptcy_Flag__c,
&quot;A&quot;, 1,
&quot;B&quot;, 1,
&quot;C&quot;, 1,
&quot;D&quot;, 1,
&quot;T&quot;, 1,
&quot;E&quot;, 1,
&quot;F&quot;, 1,
&quot;G&quot;, 1,
&quot;H&quot;, 1,
0
) = 1, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BK - Active or Discharged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modify_REPO_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Indicates when the next usage of the REPO activity code in the activity entry panel should include a modified generated note focused on highlighting the legal sale date change. Set by letter generation code upon regeneration and unset once the REPO activity note is saved.</description>
        <label>Modify REPO Note</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state of residence for the primary borrower if in the 50 states, otherwise it is the state of the dealer. The rights letters process follows the laws in the given state. The value is set by the RL Set State Conditions flow.</description>
        <label>State of Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validation_Comments__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: User-entered comments to explain soft validation failures. Entry required to generate a letter if any soft validation failures exist.</description>
        <label>Validation Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Validation_Issues__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Code-generated validation failure messages when validation criteria is met as defined in Form Validation object.</description>
        <label>Validation Issues</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_GenerateDocRequestController.cls
/*****
 * Salesforce.com Success Services
 * Name: RL_GenerateDocRequestController
 * Description: Controller for RL_GenerateDocRequestPage.page
 */

public with sharing class RL_GenerateDocRequestController {
    private final Repossession__c repo; 
    private List<Schema.FieldSetMember> repoFields;
    private Flow.Interview.RL_Quality_Review_Selection qualityReviewFlow {get; set;}    
    private Case RLParentCase {get; set;}
    private Boolean isQualityReviewRequired = false;
    public String errDisplayText{get;set;} //if populated, the page will not redirect to /{!repo.Id}

    public RL_GenerateDocRequestController(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(RL_Utility.getListOfRepoFields());
            repo = (Repossession__c) stdController.getRecord(); 
        } else {
            Id repoId = stdController.getId();
            String repoQuery = 'SELECT ';
            for (String str : RL_Utility.getListOfRepoFields()) {
                repoQuery += repoQuery.contains(' ' + str+',') ? '' : str + ', ';
            }
            repoQuery += 'Modify_REPO_Note__c, State_of_Jurisdiction__c, Auction_Agency_Name__c, Auction_Agency_Street1__c, Auction_Agency_Street2__c, Auction_Agency_Phone__c, Auction_Agency_City__c, Auction_Agency_State__c, Auction_Agency_Zip__c FROM Repossession__c where Id =: repoId';
            repo = Database.Query(repoQuery);
        }
    }

    public PageReference generateDocRequest() {
        PageReference pageRefToReturn;
        
        try{
            pageRefToReturn = genDocRequestAndReturnPageRef();
        }catch(Exception e) {
            String errorMsg = e.getMessage();
            errorMsg += '\n line: ' + String.valueOf(e.getLineNumber());
            addErrorMessage(ApexPages.Severity.ERROR, errorMsg);
            return null;
        }
        
        return pageRefToReturn;
    }
    
    private String runValidationsAndReturnErrorString() {
    	String strToReturn = '';
    	
    	Id formRuleId = [SELECT Form_Rule__c FROM Case WHERE Id =: repo.Case__c].Form_Rule__c; //Needed for unit tests. 
        RL_RepossessionValidateDynamically validator = new RL_RepossessionValidateDynamically('Repossession__c', formRuleId);
    	validator.updateSObjectValidationErrorValues(repo.Id, 'Repossession__c', 'Case__r.Form_Rule__c', 'Validation_Issues__c', true);
    	
    	RL_RepossessionValidateDynamically.ValidationErrorMessages errorMessage = validator.errorMessagesMap.get(repo.Id);
        //If an error exists and there is no validation comment, then stop.
        if(errorMessage != null && errorMessage.hasHardErrors) {
            strToReturn = 'There are validation failures.  Fix them to generate document: ' + '\n ' + errorMessage.hardErrors;
        }else if(errorMessage != null && errorMessage.hasSoftErrors && (repo.Validation_Comments__c == null || repo.Validation_Comments__c.length() == 0) ) {
            strToReturn = 'There are soft validation failures.  Please add a validation comment to generate document.';
        }
        
        //complex relationship validation.
        String facErrorString = '';
        if(repo.BK_Active_or_Discharged__c == true) {
        	for(Financial_Account_Customer__c validFac : [select id, RL_Bankruptcy_Status__c from Financial_Account_Customer__c
	        												where Financial_Account__c = :repo.Financial_Account__c AND Borrower_Status__c = 'Active'])
			{
				if(validFac.RL_Bankruptcy_Status__c == null || validFac.RL_Bankruptcy_Status__c == '') {
					facErrorString = 'At least one Financial Account Customer has a blank BK Status.';
				}
			}
        }
	        
		
		if(facErrorString != '') {
        	Repossession__c latestRepo = [select id, Validation_Issues__c from Repossession__c where id = :repo.Id];
        	if(latestRepo.Validation_Issues__c == null || latestRepo.Validation_Issues__c == '') {
        		latestRepo.Validation_Issues__c = RL_Constants.HARD_VALIDATION_MESSAGE + '\n' + facErrorString;
        	}else{
        		String tmpErrString = RL_Constants.HARD_VALIDATION_MESSAGE + '\n' + facErrorString ;
        		if(!latestRepo.Validation_Issues__c.contains(RL_Constants.HARD_VALIDATION_MESSAGE)) {
        			latestRepo.Validation_Issues__c += tmpErrString; 
        		}else{
        			latestRepo.Validation_Issues__c = latestRepo.Validation_Issues__c.replaceFirst(RL_Constants.HARD_VALIDATION_MESSAGE, tmpErrString );
        		}
        	}
        	
        	if(strToReturn == '') {
        		strToReturn = 'There are validation failures.  Fix them to generate document';
        	}
        	
        	update latestRepo;
        }
    	
    	return strToReturn;
    }
    
    private PageReference genDocRequestAndReturnPageRef() {
        RL_DocRequestHandler requestHandler;
        Set<Id> docRequestIds = new Set<Id>(); 
        
        
        String validatorString = runValidationsAndReturnErrorString();
        if(validatorString != null && validatorString != '') {
        	addErrorMessage(ApexPages.Severity.ERROR, validatorString);
        	return null;
        }
        
        
        if (repo.Recorded_Legal_Sale_Date__c == null) { // Initial Document generation
            //Check if parent case requires QA by invoking the flow
            RLParentCase = [SELECT Id, Status, RecordTypeId, RL_System_Required_Notice_Date_Time__c, Form_Rule__c FROM Case WHERE Id = :repo.Case__c limit 1];
            String UserRole = [SELECT Name FROM UserRole WHERE Id = :UserInfo.getUserRoleId() limit 1].Name;
            Case_Skills__c cs = Case_Skills__c.getInstance();

            // Call the flow with the variables
            Map<String, Object> params = new Map<String, Object>();
            params.put('sRLParentCase', RLParentCase);
            params.put('vUserRole', UserRole);
            params.put('vNewHire', cs.RL_New_Hire__c);
            params.put('vBandwidth', cs.RL_Daily_Case_Bandwidth__c);
            params.put('vDailySelection', cs.RL_Daily_Cases_for_Quality_Review__c);

            Flow.Interview.RL_Quality_Review_Selection qualityReviewFlow = new Flow.Interview.RL_Quality_Review_Selection(params);
            
            qualityReviewFlow.start();
            this.isQualityReviewRequired = (Boolean)qualityReviewFlow.getVariableValue('vQualityReviewRequired');

            if (!this.isQualityReviewRequired) {
                //Generate document
                requestHandler = new RL_DocRequestHandler(this.repo);
                requestHandler.generateDocRequest();
                
                for(Document_Request__c docReq : requestHandler.docRequestList) {
	    			docRequestIds.add(docReq.Id);
	    		}
	            RL_GenerateDocRequestController.generateLivecycleDocuments(docRequestIds);
                                
                this.repo.Recorded_Legal_Sale_Date__c = this.repo.Proposed_Legal_Sale_Date__c;
                update this.repo;   

            } else { //Quality review is required for the case
                addErrorMessage(ApexPages.Severity.CONFIRM, 'Case has been selected for quality review, queued for processing, and status updated.');
                return null;
            }
        } else { //Not the first generation of a document
            requestHandler = new RL_DocRequestHandler(this.repo);
            requestHandler.generateDocRequest();
            for(Document_Request__c docReq : requestHandler.docRequestList) {
    			docRequestIds.add(docReq.Id);
    		}
            RL_GenerateDocRequestController.generateLivecycleDocuments(docRequestIds);
            
            Date oldRLSD = repo.Recorded_Legal_Sale_Date__c;
            this.repo.Modify_REPO_Note__c = true;               
            this.repo.Recorded_Legal_Sale_Date__c = this.repo.Proposed_Legal_Sale_Date__c;
            update this.repo;
            

            if (oldRLSD != repo.Recorded_Legal_Sale_Date__c) {
                DateTime recordedDateTime = DateTime.newInstance(this.repo.Recorded_Legal_Sale_Date__c.year(), this.repo.Recorded_Legal_Sale_Date__c.month(), this.repo.Recorded_Legal_Sale_Date__c.day());
                addErrorMessage(ApexPages.Severity.CONFIRM, 'Please update LSD in AutoIMS to ' + recordedDateTime.format('MM/dd/yyyy'));
                return null; 
            }            
        }  
        
        
        if(ApexPages.hasMessages(ApexPages.Severity.ERROR)) {
        	return null;
        }
        

        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Document Generation Successful'));
        PageReference pageRef = new PageReference('/' + this.repo.Id);    
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    
    private static String printingEnabledCached;
    public static String printingEnabled {
    	get {
    		if(printingEnabledCached == null) {
		        if (!Test.isRunningTest()) {
		            printingEnabledCached = Label.RL_Enable_Printing_and_Document_Generation;
		        } else {
		            printingEnabledCached = 'TRUE';
		        }
		    	printingEnabledCached = printingEnabledCached.toUpperCase();
    		}
    		
    		return printingEnabledCached;
    	}
    	set {
    		printingEnabledCached = value;
    	}
    }
    
    @future (callout=true)
    public static void generateLivecycleDocuments(Set<Id> docRequestIds) {
    	
    	String printingIsEnabled = RL_GenerateDocRequestController.printingEnabled;
    	
    	if(docRequestIds != null) {
    		List<Document_Request__c> docsToUpdate = new List<Document_Request__c>();
    		List<System_Message__c> messagesToSend = new List<System_Message__c>();
    		
	    	for(Document_Request__c documntRequest : [select id, SourceFormIdentifier1__c, Sync_Callout_Error_Response__c, Sync_Callout_Response_Status__c,
	    												Repossession__r.Case__r.CaseNumber
	    												from Document_Request__c
	    												where id in :docRequestIds]) {
	    		
	    		String caseNumberString = ''; 
    			if(documntRequest.Repossession__r != null && documntRequest.Repossession__r.Case__r != null && documntRequest.Repossession__r.Case__r.CaseNumber != null) {
    				caseNumberString = String.valueOf(documntRequest.Repossession__r.Case__r.CaseNumber) ;
    			}
	    		
	    		try {
	    			
	    			if(printingIsEnabled != 'TRUE') {
	    				documntRequest.Sync_Callout_Response_Status__c = 'PRINTING DISABLED';
	    				documntRequest.Status__c = 'PRINTING DISABLED';
	    				documntRequest.Sync_Callout_Error_Response__c = 'To enable printing, contact the salesforce system administrator.' ;
	    				docsToUpdate.add(documntRequest);
			    		messagesToSend.add(buildSystemMessage( 'Document Generation and Printing Disabled by Salesforce System Administrator.', documntRequest.Id, 'Doc Gen Disabled', 'SFDC', caseNumberString ));
	    			}else{
	    				RL_WS_GenerateDocument.ResponseRecord responseRecord = RL_WS_GenerateDocument.callDocGenerationWebService(documntRequest.SourceFormIdentifier1__c, documntRequest.Id);
			    		documntRequest.Sync_Callout_Response_Status__c = responseRecord.ResultDesc;
			    		
			    		if(responseRecord.ResultCode == -101 || responseRecord.ResultCode == -225) {
			    			documntRequest.Sync_Callout_Error_Response__c = responseRecord.ResultString ; 
			    		}
			    		
		    			documntRequest.Sync_Callout_Error_Response__c = cleanString(documntRequest.Sync_Callout_Error_Response__c, 32767);
		    			documntRequest.Sync_Callout_XML_Request__c = cleanString(responseRecord.RequestString, 32767);
			    		docsToUpdate.add(documntRequest);
			    		if(documntRequest.Sync_Callout_Response_Status__c != null && documntRequest.Sync_Callout_Error_Response__c != null && documntRequest.Sync_Callout_Response_Status__c != 'SUCCESS') {
			    			String syncErr = 'Issue submitting form and communication between Salesforce and TIBCO.  Reference: ' + documntRequest.Id + '. ';
			    			syncErr += documntRequest.Sync_Callout_Error_Response__c ;
			    			messagesToSend.add(buildSystemMessage(syncErr, documntRequest.Id, 'Document Generation Error', 'TIBCO', caseNumberString));
			    		}
	    			}
	    		}catch(Exception e) {
	    			documntRequest.Sync_Callout_Response_Status__c = 'CAUGHT ERROR';
	    			documntRequest.Sync_Callout_Error_Response__c = e.getMessage() + ' line: ' + String.valueOf(e.getLineNumber()) + ' -- ' + e.getStackTraceString();
	    			docsToUpdate.add(documntRequest);
		    		messagesToSend.add(buildSystemMessage( 'Salesforce Error in Document Generation - ' + documntRequest.Sync_Callout_Error_Response__c, documntRequest.Id, 'Document Generation Error', 'TIBCO', caseNumberString ));
	    		}
		    		
	    	}
	    	
	    	if(messagesToSend.size() > 0) {
	    		insert messagesToSend;
	    	}
	    	
	    	update docsToUpdate;
	    }
    }
    
    public static System_Message__c buildSystemMessage(String description, Id docReqId, String messageTitle, String source, String caseNumber) {
    	System_Message__c msgToInsert = new System_Message__c();
    	
		msgToInsert.OwnerId = UserInfo.getUserId();
		msgToInsert.Notify_User__c = true ;
		msgToInsert.Source__c = source;
		msgToInsert.Title__c = messageTitle;
		if(caseNumber != null && caseNumber.length() > 0) {
			msgToInsert.Title__c += caseNumber;
		}
		msgToInsert.Type__c = 'Handled Error';
		msgToInsert.Description__c = description;
		
		return msgToInsert;
    }
    
    private static String cleanString(String str, Integer maxLength) {
    	if(str == null)
    		str = '';
    	
    	str = str.replaceAll('&amp;','&');
		str = str.replaceAll('&lt;','<');
		str = str.replaceAll('&gt;','>');
		if(str.length() > maxLength) {
			str = str.substring(0,maxLength);
		}
		return str;
    }
    
    public void addErrorMessage(ApexPages.Severity severity, String errorMessage) {
        errDisplayText = errorMessage;
        ApexPages.addMessage(new ApexPages.Message(severity, errorMessage));
    }
    
    
}