objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Render Form Service Error Description</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Render Form Service Status (Success, Failure)</description>
        <label>Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/System_Message__c.object
<CustomObject>
    <description>Used to send messages to users in the console.  Can also be used as an Exception reporting tool.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Handled Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhandled Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>System Message</label>
    <nameField>
        <label>System Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RL_DocReqStatusChangeTriggerHandler.cls
public with sharing class RL_DocReqStatusChangeTriggerHandler implements TFSC_TriggerDispatcher.Handler {
    
    
    public void handle() {
        Map<Id,Document_Request__c> newMap = (Map<Id,Document_Request__c>)Trigger.newMap;
        Map<Id,Document_Request__c> oldMap = (Map<Id,Document_Request__c>)Trigger.oldMap;
        
        ifStatusChangedSendConsoleMessage(newMap, oldMap);
    }
    
    
    
    private void ifStatusChangedSendConsoleMessage(Map<Id,Document_Request__c> newdocReqMap, Map<Id,Document_Request__c> olddocReqMap) {
    	
    	List<System_Message__c> messagesToInsert = new List<System_Message__c>();
    	String msgType;
    	Boolean notifyUser = false;
    	
    	Set<Id> repoIds = new Set<Id>();
    	for(Document_Request__c docReq1 : newdocReqMap.values()) {
    		if(docReq1.Repossession__c != null){
    			repoIds.add(docReq1.Repossession__c);
    		}
    	}
    	
    	Map<Id,Repossession__c> repoMap = new Map<Id,Repossession__c>();
    	if(!repoIds.isEmpty()) {
    		repoMap = new Map<Id,Repossession__c>([select id, case__r.CaseNumber from Repossession__c where id in :repoIds]);
    	}
    	
    	
    	for(Document_Request__c docReq : newdocReqMap.values()) {
    		
    		Document_Request__c olddocReq = olddocReqMap.get(docReq.Id);
    		
    		if(olddocReq != null && docReq.Status__c != null && docReq.Status__c != ''  && docReq.Status__c != olddocReq.Status__c) {
    			//leaving if(olddocReq != null) because integration should only update after created.  coding against mis-use of handler in trigger implementation.
    			msgType = 'Informational';
    			Boolean success = true;
    			if(docReq.Status__c != 'Success') {
    				msgType = 'Handled Error';
    				notifyUser = true;
    				success = false;
    				Repossession__c repo = null;
    				String caseNumberString = '';
    				if(docReq.Repossession__c != null) {
    					repo = repoMap.get(docReq.Repossession__c);
    					if(repo.Case__r != null && repo.Case__r.CaseNumber != null) {
    						caseNumberString = String.valueOf(repo.Case__r.CaseNumber);
    					}
    				}
    				
    				
    				System_Message__c msg = insertMessageForNonSuccessStatus(docReq, msgType, notifyUser, success, caseNumberString);
    				messagesToInsert.add(msg);
    			}
    		}
    	}
    	
    	if(messagesToInsert.size() > 0) {
    		insert messagesToInsert;
    	}
    }
    
    private System_Message__c insertMessageForNonSuccessStatus(Document_Request__c docReq, String msgType, Boolean notifyUser, Boolean success, String caseNumber) {
    	String descriptionString = 'Reference: ' + docReq.Id + '.\n ';
    	
    	if(docReq.Status__c != null) {
    		descriptionString += docReq.Status__c + '\n';
    	}
    	if(docReq.Code__c != null) {
    		descriptionString += 'Error Code: ' + docReq.Code__c + '\n';
    	}
    	if(docReq.Message__c != null) {
    		descriptionString += docReq.Message__c + '\n';
    	}
    	if(docReq.Description__c != null) {
    		descriptionString += docReq.Description__c + '\n';
    	}
    	
    	if(descriptionString.length() > 32767) {
    		descriptionString = descriptionString.substring(0,32767);
    	}
    	
    	System_Message__c msgToInsert = new System_Message__c();
		msgToInsert.OwnerId = docReq.CreatedById;
		msgToInsert.Notify_User__c = notifyUser ;
		msgToInsert.Source__c = 'LiveCycle';
		msgToInsert.Title__c = (success) ? 'Document Generated in LiveCycle' : 'LiveCycle Error';
		msgToInsert.Title__c += '; Case ' + caseNumber;
		msgToInsert.Type__c = msgType;
		msgToInsert.Description__c = descriptionString;
		
		return msgToInsert;
    }
    
    
    
    
    
}