objects/Document_Request__c.object
<CustomObject>
    <description>Snapshots of data used to generate unique inputs for document processing in the Adobe Forms Service.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Document Requests</relationshipLabel>
        <relationshipName>Document_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Document Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recorded_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Updated from proposed legal sale date when rights letter is generated. Will reflect the date from the latest generated notice.</description>
        <label>Recorded Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recorded_Notice_Date__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Updated from proposed notice date when rights letter is generated. Will reflect the date from the latest generated notice. Note that code may not have been implemented to copy latest date and ticket required to address the issue, if desired. Business decision not to implement at go-live.</description>
        <label>Recorded Notice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>iRepo_AssignmentNumber__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Unique work item identification in the iRepo system. Used as the external ID to support upsert operations on both Repossession and Case.</description>
        <externalId>true</externalId>
        <label>iRepo Assignment Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Third_Party__c.object
<CustomObject>
    <description>In the rights letters process, represents contacts associated with the customer who will receive copies of printed documents.</description>
    <fields>
        <fullName>Repossession__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Master-detail relationship field to link third party recipient with a repossession record.</description>
        <label>Repossession</label>
        <referenceTo>Repossession__c</referenceTo>
        <relationshipLabel>Third Parties</relationshipLabel>
        <relationshipName>Third_Parties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Third Party</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>Third Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Rl_CloneCaseInConsoleController.cls
public with sharing class Rl_CloneCaseInConsoleController {
	
	private Repossession__c contextRepo;
	
	public String newCaseId{get;set;}
	public String errDisplayText{get;set;}
	
	public Rl_CloneCaseInConsoleController(ApexPages.StandardController stdController) {
		String[] repoFields = new String[] {'Id','Case__r.Form_Rule__c', 'Case__c'};
		if(!Test.isRunningTest()) {
			stdController.addFields(repoFields);
	        contextRepo = (Repossession__c) stdController.getRecord();
		} else {
			contextRepo = [SELECT Id, Case__r.Form_Rule__c, Case__c FROM Repossession__c WHERE Id =: stdController.getId()];
		}
	}
	
	
	
	private String validationErrorString(Case contextCase) {
		String stringToReturn = '';
		
		//try{
			List<Document_Request__c> drs = [select id from Document_Request__c where Repossession__c = :contextRepo.Id];
			if(drs == null || drs.size() == 0) {
				stringToReturn = 'There are not yet any Document Requests for this Case. Clone functionality disabled.';
			}
		//}catch(Exception e) {
		//}
		
		return stringToReturn;
	}
	
	
	public PageReference cloneCaseAndRelatedRecords() {
		errDisplayText = '';
		String tmpErrorString;
		try{
			Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Case.fields.getMap();
			Case contextCase = (Case)runQueryOnAllFields(fldObjMap, contextRepo.Case__c, 'Case');
			
			tmpErrorString = validationErrorString(contextCase);
			
			if(tmpErrorString == null || tmpErrorString.length() == 0) {
				cloneRepoAndCase(contextCase);
			}
		}catch(Exception e) {
			tmpErrorString = e.getMessage() + ' line: ' + e.getLineNumber();
		}
		
		
		
		if(tmpErrorString != null && tmpErrorString.length() > 0) {
			appendErrorMessage( tmpErrorString );
		}
		return null;
	}
	
	
	private void cloneRepoAndCase(Case contextCase) {
		Id currentUserId = Userinfo.getUserId();
		
		Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Repossession__c.fields.getMap();
		Repossession__c repoWithAll = (Repossession__c)runQueryOnAllFields(fldObjMap, contextRepo.Id, 'Repossession__c');
		
		Case newCase = contextCase.clone(false, true, false, false);
		newCase.Integration_ID__c = null;
		insert newCase;
		newCaseId = newCase.Id;
		
		Repossession__c newRepo = repoWithAll.clone(false,true,false,false);
		newRepo.iRepo_AssignmentNumber__c = null;
		newRepo.Recorded_Legal_Sale_Date__c = null;
		newRepo.Recorded_Notice_Date__c = null;
		newRepo.Case__c = newCase.Id;
		insert newRepo;
		
		fldObjMap = schema.SObjectType.Third_Party__c.fields.getMap();
		List<Third_Party__c> listThirdParty = (List<Third_Party__c>)runQueryOnAllFieldsAndReturnList(fldObjMap, contextRepo.Id, 'Third_Party__c');
		if(listThirdParty != null && listThirdParty.size() > 0) {
			List<Third_Party__c> listToInsert = new List<Third_Party__c>();
			for(Third_Party__c tp : listThirdParty) {
				Third_Party__c clonedTp = tp.clone(false,true,false,false);
				clonedTp.Repossession__c = newRepo.Id;
				listToInsert.add(clonedTp);
			}
			
			insert listToInsert;
		}
		
	}
	
	
	private sObject runQueryOnAllFields(Map<String, Schema.SObjectField> fldObjMap, String idVal, String sobjType) {
		String whereClause = ' WHERE id = \'' + idVal + '\'';
		String queryString = buildQueryString(fldObjMap, idVal, sobjType, whereClause);
		
		return Database.query(queryString);
	}
	
	private List<sObject> runQueryOnAllFieldsAndReturnList(Map<String, Schema.SObjectField> fldObjMap, String repoId, String sobjType) {
		String whereClause = ' WHERE Repossession__c = \'' + repoId + '\'';
		String queryString = buildQueryString(fldObjMap, repoId, sobjType, whereClause);
		
		return Database.query(queryString);
	}
	
	private String buildQueryString(Map<String, Schema.SObjectField> fldObjMap, String idVal, String sobjType, String whereClause) {
		List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
		
		String queryString = 'SELECT ';
		Integer i = 0;
		for(Schema.SObjectField s : fldObjMapValues)
		{
			String theLabel = s.getDescribe().getLabel();
			String theName = s.getDescribe().getName();
			String theNameUpper = theName.toUpperCase();
			//String theType = s.getDescribe().getType();
			Boolean isFormula = s.getDescribe().isCalculated() ;
			
			if(!isFormula && 
					theNameUpper != 'OWNER' && theNameUpper != 'OWNERID' && 
					theNameUpper != 'CREATEDBY' && theNameUpper != 'CREATEDBYID' &&
					theNameUpper != 'LASTMODIFIEDBY' && theNameUpper != 'LASTMODIFIEDBYID') {
				if(i  > 0) {
					queryString += ',' ;
				}
				queryString += theName;
				i++;
			}
		}
		
		queryString += ' FROM ' + sobjType + whereClause;
		
		return queryString;
	}
	
	
	
	/*private void appendInfoMessage(String infoMessage) {
     appendMessage(infoMessage, ApexPages.Severity.INFO);
    }*/
    private void appendErrorMessage(String errorMessage) {
        errDisplayText = errorMessage;
        appendMessage(errorMessage, ApexPages.Severity.ERROR);
    }
    
    private void appendMessage(String errorMessage, ApexPages.severity severity) {
        ApexPages.Message apexPageMessage = new ApexPages.Message(severity, errorMessage);
        ApexPages.addMessage(apexPageMessage);
    }
}