objects/FAQ_A__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>FAQ</label>
    <pluralLabel>FAQs</pluralLabel>
</CustomObject>

objects/How_To_A__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Process_Steps__c</fullName>
        <label>Process Steps</label>
        <length>65536</length>
        <type>Html</type>
    </fields>
    <label>How To</label>
    <pluralLabel>How To(s)</pluralLabel>
</CustomObject>

classes/KmSoslSearchModelTest.cls
@IsTest
public class KmSoslSearchModelTest {

	@IsTest
	public static void TestSearchArticles() {
		
		KmArticleTypeTest.createTestData();
		KmArticleTypeModelTest.createTestDataActiveKa();
		
		List<KmSearchModel.FindKavResult> articles = (new KmSOSLSearchModel()).SearchArticles('*function*');

	}
	
	//KmSoslSearchModel.testFind();
	public static void testFind() {
		
		String queryStr = 'Find \'*div*\' IN ALL FIELDS RETURNING ' +
			'how_to_a__kav (process_steps__c WHERE PublishStatus = \'Online\' AND Language = \'en_US\')'; //', ' +
			//'faq_a__kav (answer__c WHERE PublishStatus = \'Online\' AND Language = \'en_US\'), ' ;
		
		//String queryStr = 'Find \'tfs\' IN ALL FIELDS RETURNING user(name) '; 
		
		System.Debug(queryStr);
		List<List<sObject>> myQueryResult = search.query(queryStr);
		
		
	}

	//KmSoslSearchModel.testFind2();
	public static void testFind2() {
		
		String queryStr = 'Find \'*div*\' IN ALL FIELDS RETURNING ' +
			'how_to_a__kav (process_steps__c WHERE PublishStatus = \'Online\' AND Language = \'en_US\'), ' +
			'faq_a__kav (answer__c WHERE PublishStatus = \'Online\' AND Language = \'en_US\') ' ;
	
		
		System.Debug(queryStr);
		List<List<sObject>> myQueryResult = search.query(queryStr);
		
		
	}
}