objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RL_Bankruptcy_Status__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Used in the Rights Letters process. When the Financial Account is in an active or discharged bankruptcy status, this indicates the individual borrower&apos;s BK status, where it may be the same or different from the account&apos;s.</description>
        <inlineHelpText>Used in the Rights Letters process. When the Financial Account is in an active or discharged bankruptcy status, this indicates the individual borrower&apos;s BK status, where it may be the same or different from the account&apos;s.</inlineHelpText>
        <label>Bankruptcy Status</label>
        <picklist>
            <picklistValues>
                <fullName>Filing Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Filing Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Third_Party__c.object
<CustomObject>
    <description>In the rights letters process, represents contacts associated with the customer who will receive copies of printed documents.</description>
    <fields>
        <fullName>Attorney_Representing_Borrower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Lookup to FAC to indicate the third party recipient is an attorney representing the related borrower (FAC).</description>
        <label>Attorney Representing Borrower</label>
        <referenceTo>Financial_Account_Customer__c</referenceTo>
        <relationshipLabel>Attorneys</relationshipLabel>
        <relationshipName>Attorneys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Formula field to pull down the related financial account reference.</description>
        <formula>Repossession__r.Financial_Account__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial Account</label>
        <type>Text</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>Third Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RL_ThirdPartyAttorneyRepController.cls
public with sharing class RL_ThirdPartyAttorneyRepController {
    private final Third_Party__c thirdParty;
    private String financialAccountId;
    
    public String representing {get;set;}
    
    // Fill picklist options with active FACs (borrowers) related to associated financial account - default is blank/Not an Attorney
    public List<SelectOption> getFACs() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', 'Not an Attorney'));
        for (Financial_Account_Customer__c fac : [select Id, Name from Financial_Account_Customer__c where Financial_Account__c = :financialAccountId and Borrower_Status__c = 'Active' and RL_Bankruptcy_Status__c = 'Filing Party' order by Customer_Role_Type__c]){
            options.add(new SelectOption(fac.Id, fac.Name));
        }
        return options;
    }

    public RL_ThirdPartyAttorneyRepController(ApexPages.StandardController stdController){
        // Get context to set picklist to currently saved FAC value
        List<String> fieldsList = new List<String>();
        fieldsList.add('Financial_Account__c');
        fieldsList.add('Attorney_Representing_Borrower__r.Name');
        if (!Test.isRunningTest()) {
            stdController.addFields(fieldsList);
        }
        thirdParty = (Third_Party__c) stdController.getRecord();
        financialAccountId = thirdParty.Financial_Account__c;
        
        // Set picklist to currently saved FAC value or blank if not associated
        if (thirdParty.Attorney_Representing_Borrower__r.Name == null){
            representing = '';
        } else {
            representing = thirdParty.Attorney_Representing_Borrower__c;
        }
    }

    // Save any changes made in picklist to Attorney Representing Borrower lookup(FAC)
    public void saveRepresenting() {
        thirdParty.Attorney_Representing_Borrower__c = representing;
        update thirdParty;
    }
}