objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collection_Recourse_Code__c</fullName>
        <description>Copy of the recourse code from the case</description>
        <label>Collection Recourse Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_CollectionsCaseHandlerTest.cls
@isTest
private class TFSC_CollectionsCaseHandlerTest {
	
	static String testFAId = null;
	static String testFARecourseCode = null;
	static String testFACId = null;
	

	private static void setupTestFA(){

		Account acct = TFSC_TestUtils.setupAndReturnNewAccount();
		Financial_Account__c testFA = TFSC_TestUtils.setupAndReturnNewFinancialAccount(acct);
		Financial_Account_Customer__c testFAC = TFSC_TestUtils.setupAndReturnFAC(testFA, acct, 'Primary');

		testFAId = testFA.Id;
		testFACId = testFAC.Id;
		testFARecourseCode = testFA.Collection_Recourse_Code__c;
		System.debug('*************** testFAId: ' + testFAId);

	}


	static testMethod void 	testCollectionsCase(){

		String caseRecTypeId = RecordTypeModel.LookupRecordTypeId('Case', 'Collection');

		System.debug('****************** Collection rec type ID: ' + caseRecTypeId);

		setupTestFA();

		Case testCase = new Case(
							Status = 'New',
							Collection_Recourse_Code__c = 'N',
							RecordTypeId = caseRecTypeId,
							Financial_Account__c = testFAId,
							Financial_Account_Customer__c = testFACId
							);

		Test.startTest();
		insert testCase;
		Test.stopTest();

		System.debug('************** Case ID:' + testCase.Id + ' ~ Case Record Type: ' + testCase.RecordTypeId);

		testFARecourseCode = [SELECT Collection_Recourse_Code__c FROM Financial_Account__c WHERE Id = :testFAId LIMIT 1].Collection_Recourse_Code__c;

		System.debug('*************** testFARecourseCode: ' + testFARecourseCode);

		System.assertEquals(testFARecourseCode,testCase.Collection_Recourse_Code__c);

	}

}