objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_SoftPhoneExceptionController.cls
global class TFSC_SoftPhoneExceptionController {
    
    
    public TFSC_SoftPhoneExceptionController() {
    	
    }
    
    @RemoteAction
    global static List<Financial_Account__c> getFaidStringListFromAccountNumSearch(String acctNum) {
    	List<Financial_Account__c> listToReturn = new List<Financial_Account__c>();
    	
    	for(Financial_Account__c fa : [select id, name from Financial_Account__c
    									where Financial_Account_Number__c = :acctNum])
		{
			listToReturn.add(fa);
		}
    	
    	
    	return listToReturn;
    }
    
    
    
    
}