objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Communication_Comments__c</fullName>
        <label>Communication Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Communication_Comments__c</fullName>
        <formula>Financial_Account__r.Communication_Comments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Communication Comments</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Election_Payment_NotReceivedText__c</fullName>
        <label>Payment Not Received Text</label>
        <picklist>
            <controllingField>Election_Overall_Consent__c</controllingField>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing_State_BillTo__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Request_Field_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conversion_Type__c</fullName>
        <inlineHelpText>If a conversion is required, enter the conversion type here that matches apex conversion mapping.  &quot;Boolean&quot; = convert yes/no text to Bool.</inlineHelpText>
        <label>Conversion Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Group</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Category__c</fullName>
        <label>Service Request Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Result__c</fullName>
        <label>Service Result</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <length>43</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <label>Source Object</label>
        <length>43</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <label>Target Field</label>
        <length>43</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <label>Target Object</label>
        <length>43</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Request Field Map</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Coll_Racf_Id__c</fullName>
        <label>Coll Racf Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lan_Id__c</fullName>
        <label>Lan Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Service_Type__c</fullName>
        <label>Service Request Service Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Comment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet E-mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet Incoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lexus Term Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Contact Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Related Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota Term Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Request_User_Group__c</fullName>
        <label>Service Request User Group</label>
        <picklist>
            <picklistValues>
                <fullName>ADM COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Solution Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2P System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDS System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Recovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Recovery System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate CRM Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CR COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS COE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Loyalty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Daily System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMS System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document Control Clerk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DSSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBPP System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Management System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPAY System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FOCUS General</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TFSC_FinancialActEditCaseCreateTest.cls
@isTest
private class TFSC_FinancialActEditCaseCreateTest {
    
    
    static testmethod void testWithDefaultUser() {
        Account acct = new Account(name = 'testAcct123');
        insert acct;
        
        Financial_Account__c fAcct = setupData(acct);
        Financial_Account_Customer__c facPrimary = generateAndInsertFAC(fAcct.Id, 'Primary','Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
        
        Test.startTest();
            facPrimary.Mailing_State_BillTo__c = 'MT';
            facPrimary.Election_Payment_NotReceivedText__c = 'Yes';
            update facPrimary;
        Test.stopTest();
    }
    
    
    static testmethod void testWithAcceptableUser() {
        User testUser = generateTestUser();
        
        System.RunAs(testUser){
            Test.startTest();
                
                Account acct = new Account(name = 'testAcct123321');
                insert acct;
                
                Financial_Account__c fAcct = setupData(acct);
                Financial_Account_Customer__c facPrimary = generateAndInsertFAC(fAcct.Id, 'Primary','Open', acct.Id, TFSC_TestUtils.generateRandomString(4));
                
                //facPrimary.Mailing_State_BillTo__c = 'MT';
                facPrimary.Election_Payment_NotReceivedText__c = 'Yes';
                update facPrimary;
            Test.stopTest();
        }
    }
    
    private static User generateTestUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Collections']; 
        User usr = new User(Alias = 'stst123', Email='standarduser123@toyotaDevish.com', 
        					Coll_Racf_Id__c = 'XXX123',
                            Lan_Id__c = 'LANID', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            Service_Request_User_Group__c = 'test',
                            Service_Request_Service_Type__c = 'test',
                            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@toyotaDevish.com');
        return usr;
    }
    
    
    private static Financial_Account__c setupData(Account acct) {
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = '12123434');
        financialAccount.Communication_Comments__c = 'test comments';
        financialAccount.RecordTypeId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Lease', 'Financial_Account__c') ;
        insert financialAccount;
        
        //Asset ast = new Asset( name = 'testAsset1', AccountId = acct.Id, Financial_Account__c = financialAccount.Id );
        //insert ast;
        
        Service_Request_Field_Map__c customSettingToInsert = new Service_Request_Field_Map__c();
        customSettingToInsert.Name = 'Mailing_State_BillTo__c';
        customSettingToInsert.Source_Field__c = 'Mailing_State_BillTo__c';
        customSettingToInsert.Source_Object__c = 'Financial_Account_Customer__c';
        customSettingToInsert.Target_Object__c = 'Case';
        customSettingToInsert.Target_Field__c = 'Description';
        customSettingToInsert.Record_Type__c = 'Customer Profile Change';
        customSettingToInsert.Type__c = 'Test';
        customSettingToInsert.Group__c = 1;
        customSettingToInsert.Conversion_Type__c = '';
        customSettingToInsert.Address_Type__c = 'test';
        customSettingToInsert.Service_Request_Category__c = 'test';
        customSettingToInsert.Service_Result__c = 'test';
        insert customSettingToInsert;
        
        Service_Request_Field_Map__c customSettingToInsert2 = new Service_Request_Field_Map__c();
        customSettingToInsert2.Name = 'Election_Payment_NotReceivedText__c';
        customSettingToInsert2.Source_Field__c = 'Election_Payment_NotReceivedText__c';
        customSettingToInsert2.Source_Object__c = 'Financial_Account_Customer__c';
        customSettingToInsert2.Target_Object__c = 'Case';
        customSettingToInsert2.Target_Field__c = 'Payment_Not_Received_Text__c';
        customSettingToInsert2.Record_Type__c = 'Customer Profile Change';
        customSettingToInsert2.Type__c = 'Test';
        customSettingToInsert2.Group__c = 1;
        customSettingToInsert2.Conversion_Type__c = ''; //Boolean was here.
        customSettingToInsert.Address_Type__c = 'test';
        customSettingToInsert.Service_Request_Category__c = 'test';
        customSettingToInsert.Service_Result__c = 'test';
        insert customSettingToInsert2;
        
        
        return financialAccount;
    }
    private static Financial_Account_Customer__c generateAndInsertFAC(Id FAId, String borrowerPosition, String openOrClosed, Id AcctId, String randString) {
        Financial_Account_Customer__c fac = new Financial_Account_Customer__c();
        fac.Borrower_Position__c = borrowerPosition;
        fac.Borrower_Status__c = 'Active';
        fac.Financial_Account__c = FAId;
        fac.Account__c = acctId;
        fac.Mailing_State_BillTo__c = 'CO';
        fac.Mailing_City_BillTo__c = 'Fort Collins';
        fac.Mailing_PostalCode_BillTo__c = '23456';
        fac.Mailing_Street_BillTo__c = '123 1st st';
        
        fac.Mailing_State_Garage__c = 'CO';
        fac.Mailing_City_Garage__c = 'Fort Collins';
        fac.Mailing_Postal_Code_Garage__c = '23456';
        fac.Mailing_Street_Garage__c = '123 1st st';
        //fac.Mailing_Postal_Code_Garage__c = '12345';
        fac.Financial_Account_Customer__c = '12345566';
        fac.Election_Overall_Consent__c = 'Y';
        fac.Borrower_Status__c = 'Active';
        fac.Customer_Role_Type__c = 'test';
        fac.FA_Role_Status__c = 'test';
        fac.Financial_Account_Customer__c = 'test' + randString;
        //fac.Finance_Account_Status__c = openOrClosed;
        insert fac;
        
        return fac;
    }
    
    
    
}