objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Skip_Trace__c.object
<CustomObject>
    <description>Transformed copy of skip trace notes entered in Collections Host PF11 screen and primary
location for creation and maintenance of skip trace information within Salesforce.</description>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Skip Trace</relationshipLabel>
        <relationshipName>Skip_Trace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone1__c</fullName>
        <label>Phone1</label>
        <type>Phone</type>
    </fields>
    <label>Skip Trace</label>
    <nameField>
        <label>Skip Trace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skip Trace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_ConsoleManagerControllerTest.cls
@isTest
private class TFSC_ConsoleManagerControllerTest {
    
    
    static testmethod void testPublicStaticMethods() {
    	
    	Account acct = TFSC_TestUtils.setupAndReturnNewAccount();
    	String accountNum = TFSC_TestUtils.generateRandomString(8);
    	Financial_Account__c fa = TFSC_TestUtils.setupAndReturnNewFinancialAccount(acct, accountNum);
    	TFSC_TestUtils.setupAndReturnFAC(fa, acct, 'Primary');
    	
    	Skip_Trace__c skipTrace = new Skip_Trace__c(Financial_Account__c = fa.Id);
        skipTrace.Address1__c = '1234 addy ST';
        skipTrace.Phone1__c = '4063775012';
        insert skipTrace;
    	
    	String testStr = TFSC_ConsoleManagerController.getObjectIdFromAccountNumber(accountNum);
    	System.assert( testStr != null ); 
    	
    	List<TFSC_ConsoleManagerController.FaObject> testList;
    	testList = TFSC_ConsoleManagerController.getFaObjectsFromFaIdList( new String[]{fa.Id} );
    	System.assert( testList != null ); 
        // Story S-311850 7/10/2015 #start
        TFSC_ConsoleManagerController.setInteractionType(String.valueOf(fa.id).left(15),'Inbound Call' );
        TFSC_ConsoleManagerController.deleteInteractionType(String.valueOf(fa.id).left(15));
        // Story S-311850 #end
    }
    
    
    
    
}