objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Skip_Trace__c.object
<CustomObject>
    <description>Transformed copy of skip trace notes entered in Collections Host PF11 screen and primary
location for creation and maintenance of skip trace information within Salesforce.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Skip Trace</relationshipLabel>
        <relationshipName>Skip_Trace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Innovis_Date__c</fullName>
        <label>Innovis Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone1_CS_CX__c</fullName>
        <label>Phone1 CS/CX</label>
        <picklist>
            <picklistValues>
                <fullName>CS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone1_Date__c</fullName>
        <label>Phone1 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone1_Source__c</fullName>
        <label>Phone1 Source</label>
        <picklist>
            <picklistValues>
                <fullName>System Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accurint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved 3rd Party Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iVault</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone1_Status__c</fullName>
        <label>Phone1 Status</label>
        <picklist>
            <picklistValues>
                <fullName>? - Unverified</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>G - Good Number (C,A)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C - Cell/Mobile (C-auth, B-no)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L - Land Line (C-valid, X-no)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S - Same as System (A, S)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M - Multiple Work Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D - Disconnected (X)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B - Bad Number (X)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T - Toyota Financial/Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H - DNC but Good (C,A)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N - Do Not Call Number (D, S)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone1_Type__c</fullName>
        <label>Phone1 Type</label>
        <picklist>
            <picklistValues>
                <fullName>CS - Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS - Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS - Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CS - ?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CX - ?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSS - Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSS - Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSS - Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSS - ?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3P - Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3P - Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3P - Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3P - ?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>?</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone1__c</fullName>
        <label>Phone1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone2_CS_CX__c</fullName>
        <label>Phone2 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone2_Date__c</fullName>
        <label>Phone2 Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone2_Source__c</fullName>
        <label>Phone2 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone2_Status__c</fullName>
        <label>Phone2 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone2_Type__c</fullName>
        <label>Phone2 Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone2__c</fullName>
        <label>Phone2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone3_CS_CX__c</fullName>
        <label>Phone3 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone3_Source__c</fullName>
        <label>Phone3 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone3_Status__c</fullName>
        <label>Phone3 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone3_Type__c</fullName>
        <label>Phone3 Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone3__c</fullName>
        <label>Phone3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone4_CS_CX__c</fullName>
        <label>Phone4 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone4_Source__c</fullName>
        <label>Phone4 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone4_Status__c</fullName>
        <label>Phone4 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone4_Type__c</fullName>
        <label>Phone4 Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone4__c</fullName>
        <label>Phone4</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone5_CS_CX__c</fullName>
        <label>Phone5 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone5_Source__c</fullName>
        <label>Phone5 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone5_Status__c</fullName>
        <label>Phone5 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone5__c</fullName>
        <label>Phone5</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone6_CS_CX__c</fullName>
        <label>Phone6 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone6_Source__c</fullName>
        <label>Phone6 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone6_Status__c</fullName>
        <label>Phone6 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone6__c</fullName>
        <label>Phone6</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone7_CS_CX__c</fullName>
        <label>Phone7 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone7_Source__c</fullName>
        <label>Phone7 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone7_Status__c</fullName>
        <label>Phone7 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone7__c</fullName>
        <label>Phone7</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone8_CS_CX__c</fullName>
        <label>Phone8 CS/CX</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone8_Source__c</fullName>
        <label>Phone8 Source</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone8_Status__c</fullName>
        <label>Phone8 Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone8__c</fullName>
        <label>Phone8</label>
        <type>Phone</type>
    </fields>
    <label>Skip Trace</label>
    <nameField>
        <label>Skip Trace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skip Trace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TFSC_SkipTraceUpdateSyncPF11Test.cls
@isTest
private class TFSC_SkipTraceUpdateSyncPF11Test {
    
    
    
    static testmethod void testSkipTraceUpdate() {
        
        Account acct = new Account(name = 'testAcct' + TFSC_TestUtils.generateRandomString(4));
        insert acct;
        
        Financial_Account__c fAcct = setupData(acct);
        
        Test.startTest();
            Skip_Trace__c st = generateSkipTraceRecord(fAcct);
            insert st;
        Test.stopTest();
    }
    
    
    private static Skip_Trace__c generateSkipTraceRecord(Financial_Account__c fAcct) {
        
        Skip_Trace__c st = new Skip_Trace__c();
        st.Financial_Account__c = fAcct.Id;
        st.Phone1__c = '1111111111';
        st.Phone1_CS_CX__c = 'CX';
        st.Phone1_Source__c = 'Credit App';
        st.Phone1_Status__c = 'G - Good Number (C,A)';
        st.Phone2__c = '2222222222';
        st.Phone2_CS_CX__c = 'CX';
        st.Phone2_Source__c = 'Credit App';
        st.Phone2_Status__c = 'G - Good Number (C,A)';
        st.Phone3__c = '3333333333';
        st.Phone3_CS_CX__c = 'CX';
        st.Phone3_Source__c = 'Credit App';
        st.Phone3_Status__c = 'G - Good Number (C,A)';
        st.Phone4__c = '4444444444';
        st.Phone4_CS_CX__c = 'CX';
        st.Phone4_Source__c = 'Credit App';
        st.Phone4_Status__c = 'G - Good Number (C,A)';
        st.Phone5__c = '5555555555';
        st.Phone5_CS_CX__c = 'CX';
        st.Phone5_Source__c = 'Credit App';
        st.Phone5_Status__c = 'G - Good Number (C,A)';
        st.Phone6__c = '6666666666';
        st.Phone6_CS_CX__c = 'CX';
        st.Phone6_Source__c = 'Credit App';
        st.Phone6_Status__c = 'G - Good Number (C,A)';
        st.Phone7__c = '7777777777';
        st.Phone7_CS_CX__c = 'CX';
        st.Phone7_Source__c = 'Credit App';
        st.Phone7_Status__c = 'G - Good Number (C,A)';
        st.Phone8__c = '8888888888';
        st.Phone8_CS_CX__c = 'CX';
        st.Phone8_Source__c = 'Credit App';
        st.Phone8_Status__c = 'G - Good Number (C,A)';
        st.Innovis_Date__c = Date.today();
        
        st.Phone1_Type__c = 'Mobile';
        st.Phone2_Type__c = '';
        st.Phone3_Type__c = 'Work';
        st.Phone4_Type__c = 'Work';
        st.Phone1_Date__c = Date.newInstance(Date.today().year(), 12, 30);
        st.Phone2_Date__c = Date.newInstance(Date.today().year() - 1, 1, 1);
        
        
        
        
        return st;
    }
    
    
    
    
    private static Financial_Account__c setupData(Account acct) {
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = '1212aabb45');
        insert financialAccount;
        
        
        return financialAccount;
    }
    
    
}