objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collection_List_Number_1__c</fullName>
        <label>Collection List Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease type of account</description>
        <label>Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>Retail</fullName>
        <active>true</active>
        <description>Loan type of account</description>
        <label>Retail</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>Salvage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to support different notice of sale form for salvage.</description>
        <label>Salvage</label>
        <type>Checkbox</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Rule_Validation_Junction__c.object
<CustomObject>
    <description>Junction object linking Form Rules with Form Validations supporting differentiated validation requirements and rules across states as well as sharing validations across states.</description>
    <fields>
        <fullName>Form_Rule__c</fullName>
        <label>Form Rule</label>
        <referenceTo>Form_Rule__c</referenceTo>
        <relationshipLabel>Form Rule-Validation Junctions</relationshipLabel>
        <relationshipName>Form_Rule_Validation_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Form_Validation__c</fullName>
        <label>Form Validation</label>
        <referenceTo>Form_Validation__c</referenceTo>
        <relationshipLabel>Form Rule-Validation Junctions</relationshipLabel>
        <relationshipName>Form_Rule_Validation_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Form Rule-Validation Junction</label>
    <nameField>
        <displayFormat>FRV-{000000}</displayFormat>
        <label>Form Rule-Validation Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Rule-Validation Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Form_Validation__c.object
<CustomObject>
    <description>Field-level quality checks supporting a soft validation of inputs prior to generation of rights letters or documents in the Adobe Forms Service.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Text to display to users and enter into error/issues field when validation rule fails.</description>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hard_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Checkbox to indicate whether failing this validation rule should stop a process from moving forward.</description>
        <label>Hard Error</label>
        <type>Checkbox</type>
    </fields>
    <label>Form Validation</label>
    <nameField>
        <label>Form Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Validations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Account_Terminated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Checkbox for user to indicate whether account has been terminated in Host.</description>
        <label>Account Terminated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conditional_Reinstatement__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Picklist for user to indicate whether reinstatement rights are required to be offered by the contract when the state of jurisdiction does not mandate nor deny it.</description>
        <label>Conditional Reinstatement</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IRepo_AssignmentType__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 TIBCO Pull
Trans: Y
BU: RL
FD: Identifies whether the repossession was voluntary or not. TIBCO transforms &quot;Voluntary Recovery&quot; into true value in Voluntary_Surrender__c.</description>
        <label>iRepo Assignment Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impound_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo
INT: iRepo M2 TIBCO Pull
Trans: N
BU: RL
FD: Impound fee (repairs, citations, etc.) sent from iRepo for release of vehicle. Included in total balance owed.</description>
        <label>Impound Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Local_Repo_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Date of the repossession at the place of repossession. Since date/time is received in GMT, date must be converted to a local date and stored here. Handled within the RL Set State Conditions Flow and associated date/time Apex plug-in.</description>
        <label>Local Repo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Personal_Property_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo
INT: iRepo M2 TIBCO Pull
Trans: N
BU: RL
FD: Fee optionally assessed in repossession process and sourced from iRepo.</description>
        <label>Personal Property Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RepoLocationName__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: Used to validate logic which drives individual vehicle location information to send to Adobe Forms Service. Not used or displayed in production.</description>
        <formula>IF(Financial_Account__r.Collection_List_Number_1__c = &quot;1812&quot; &amp;&amp; !ISPICKVAL(iRepo_RepoState__c, &quot;CA&quot;),

Repo_Agency_Name__c &amp; &quot;, &quot; &amp; Repo_Agency_Street1__c &amp; &quot;, &quot; &amp; IF(!ISBLANK(Repo_Agency_Street2__c), Repo_Agency_Street2__c &amp; &quot;, &quot;, &quot;&quot;) &amp; Repo_Agency_City__c &amp; &quot;, &quot; &amp; TEXT(Repo_Agency_State__c) &amp; &quot; &quot; &amp; Repo_Agency_Zip__c,

Auction_Agency_Name__c &amp; &quot;, &quot; &amp; Auction_Agency_Street1__c &amp; &quot;, &quot; &amp; IF(!ISBLANK(Auction_Agency_Street2__c), Auction_Agency_Street2__c &amp; &quot;, &quot;, &quot;&quot;) &amp; Auction_Agency_City__c &amp; &quot;, &quot; &amp; TEXT(Auction_Agency_State__c) &amp; &quot; &quot; &amp; Auction_Agency_Zip__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vehicle Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salvage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Indicates whether the vehicle has been sufficiently damaged to disqualify it from the standard auction process. User checks the box after reviewing the damage details provided by the repo and/or auction agencies.</description>
        <label>Salvage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Full_Address__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: The full address to which the vehicle title should be sent. Usually it is the auction location. Used to communicate with title services via a DMS work item (copy &amp; paste).</description>
        <formula>Title_Name__c &amp; &quot;, &quot; &amp; Title_Street1__c &amp; &quot;, &quot; &amp; IF(!ISBLANK(Title_Street2__c), Title_Street2__c &amp; &quot;, &quot;, &quot;&quot;) &amp; Title_City__c &amp; &quot;, &quot; &amp; Title_State__c &amp; &quot; &quot; &amp; Title_Zip__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>United_Road_Transport_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: United Road 
INT: United Road Auction 
Trans: N 
BU: RL 
FD: The fee for vehicle transportation from the repo agency to the auction. United Road coordinates the effort. The user clicks a button to query United Road for the fee based on the VIN.</description>
        <label>Transportation Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Issues__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Code-generated validation failure messages when validation criteria is met as defined in Form Validation object.</description>
        <label>Validation Issues</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>iRepo_RepoState__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 TIBCO Pull
Trans: N
BU: RL
FD: State of location of actual repossession. Used to determine whether in-state or out-of-state processes apply when state of jurisdiction is CA.</description>
        <label>iRepo Repo State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_RepossessionValidateDynamicTest.cls
@isTest
private class RL_RepossessionValidateDynamicTest {

    static testMethod void testValidationRules() {
        
        
        List<Form_Validation__c> validations = generateListOfValidations();
        insert validations;
        
        RL_GenerateTestData.createTimezoneIndicators();
        Map<String, Form_Rule__c> formRuleMap = RL_GenerateTestData.insertFormRuleData();
        Id dealerRTId = RL_GenerateTestData.getRecordType('Account', 'Dealer');
        Account dealer = RL_GenerateTestData.createTestDealer(dealerRTId);

        Id retailRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Retail');
        Id leaseRTId = RL_GenerateTestData.getRecordType('Financial_Account__c', 'Lease');
        Financial_Account__c faRetail = RL_GenerateTestData.createFARetailIL(dealer, retailRTId);
        faRetail.Collection_List_Number_1__c = '1812';
        update faRetail;
        Financial_Account__c faLease = RL_GenerateTestData.createFALeaseIL(dealer, leaseRTId);        

        // Create Case
        Id caseRTId = RL_GenerateTestData.getRecordType('Case', 'Rights Letter');        
        Case aCase = RL_GenerateTestData.createCase(faRetail, caseRTId);
        aCase.Form_Rule__c = formRuleMap.get('4015IL').Id;
        update aCase;

        // Create Repossession
        Id repoRTId = RL_GenerateTestData.getRecordType('Repossession__c', 'RL Retail-Generic');
        Repossession__c repo = RL_GenerateTestData.createRepossession(aCase, faRetail, repoRTId);
        
        
        List<Form_Rule_Validation_Junction__c> junctionObjs = new List<Form_Rule_Validation_Junction__c>(); 
        for(Form_Validation__c v1 : validations) {
        	junctionObjs.add( new Form_Rule_Validation_Junction__c(Form_Rule__c = formRuleMap.get('4015IL').Id, Form_Validation__c = v1.Id) );
        }
        insert junctionObjs;
        
        
        Date badDate = date.today();
        repo.Local_Repo_Date__c = badDate;
        //repo.Collection_List_Number_1__c = '1812';
        repo.iRepo_RepoState__c = 'NV';
        update repo;
        
        Map<Id,Repossession__c> repoMap = new Map<Id,Repossession__c>();
        repo = [select id, Case__r.Form_Rule__c, Account_Terminated__c, Local_Repo_Date__c,
        			Conditional_Reinstatement__c, Personal_Property_Fee__c,
        			iRepo_RepoState__c, United_Road_Transport_Fees__c, Salvage__c,
        			Impound_Fee__c, irepo_assignmenttype__c,
        			RepoLocationName__c, Title_Full_Address__c
        		from Repossession__c where id = :repo.id] ;
        repoMap.put(repo.Id, repo);
        Set<Id> repoListForValidation = new Set<Id>();
        repoListForValidation.add(repo.Id);
        
        
        Test.startTest();
        	
        	RL_RepossessionValidateDynamically validationClass = new RL_RepossessionValidateDynamically();
        	//validationClass.updateSObjectValidationErrorValues(repoMap, 'Case__r.Form_Rule__c', 'Validation_Issues__c', true);
        	validationClass.updateSObjectValidationErrorValues(repoListForValidation, 'Repossession__c', 'Case__r.Form_Rule__c', 'Validation_Issues__c', true);
        	
        Test.StopTest();
        
    }
    
    private static Form_Validation__c generateFormValidation(Boolean hardErr, String errMsg,
    									String fieldName1, String fieldType1, String operator1, String value1,
    									String fieldName2, String fieldType2, String operator2, String value2) {
    	
    	Form_Validation__c validation = new Form_Validation__c(
    	    Error_Message__c = errMsg, Hard_Error__c = hardErr, 
    	    RL_Field_Name1__c = fieldName1, RL_Field_Name2__c = fieldName2, 
    	    RL_Field1_Type__c = fieldType1, RL_Field2_Type__c = fieldType2, 
    	    RL_Operator1__c = operator1, RL_Operator2__c = operator2, 
    	    RL_Value1__c = value1, RL_Value2__c = value2 ,
    	    SObject__c = 'Repossession__c'
    	);
    	
    	return validation; 
    }
    
    private static List<Form_Validation__c> generateListOfValidations() {
    	List<Form_Validation__c> listToReturn = new List<Form_Validation__c>();
    	
    	//DateTime, Date, Number, Boolean, Picklist, String
    	// == (Equal To), <> (Not Equal To), >= Greater Than or Equal To, >= Greater Than or Equal To, > (Greater Than), < (Less Than), IN 
    	
    	listToReturn.add( generateFormValidation(false, 'error occurred', 'Account_Terminated__c', 'Boolean', '<> (Equal To)', 'TRUE', null, null, null, null) );
    	listToReturn.add( generateFormValidation(false, 'error occurred', 'Salvage__c', 'Boolean', '== (Equal To)', 'FALSE', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '>= (Greater than or EQ2)', 'TODAY', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '<= (LTE)', 'TODAY', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '== (EQ)', 'TODAY', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '>  (GT)', 'TODAY', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '< (LT)', 'TODAY', null, null, null, null) );
    	
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '>= (Greater than or EQ2)', 'TODAY', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '<= (LTE)', '2010-10-10', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '== (EQ)', '2010-10-10', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '>  (GT)', '2010-10-10', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Local_Repo_Date__c', 'Date', '< (LT)', '2020-10-10', null, null, null, null) );
    	
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Conditional_Reinstatement__c', 'String', '==', '', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Conditional_Reinstatement__c', 'String', '<>', 'asdf', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Personal_Property_Fee__c', 'Number', '< (Greater than)', '100', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Personal_Property_Fee__c', 'Number', '> (Greater than)', '100', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Personal_Property_Fee__c', 'Number', '== (Greater than)', '100', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Personal_Property_Fee__c', 'Number', '>= (Greater than)', '100', null, null, null, null) );
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'Personal_Property_Fee__c', 'Number', '<= (Greater than)', '100', null, null, null, null) );
    	
    	//Transportation Expenses = Blank AND [Recovery State is not CT] 
    	listToReturn.add( generateFormValidation(true, 'error occurred', 'United_Road_Transport_Fees__c', 'Number', '== (equal)', '', 'iRepo_RepoState__c', 'String', '<>', 'CT') );
    	
    	//listToReturn.add( generateFormValidation(false, 'error occurred', 'Impound_Fee__c', 'Number', '== (Equal To)', '', 'IRepo_AssignmentType__c', 'String', '==', 'Impound') );
    	listToReturn.add( generateFormValidation(false, 'error occurred', 'Impound_Fee__c', 'Number', '== (Equal To)', '', null, null, null, null) );
    	
    	//[Vehicle Location does not match Titles Services Address AND salvage checkbox = false]
    	Form_Validation__c fv = generateFormValidation(false, 'error occurred', 'RepoLocationName__c', 'String', '== (Equal To)', 'Title_Full_Address__c', 'Salvage__c', 'Boolean', '== ', 'false');
    	fv.Is_Validation_Val_A_Field1__c = true;
    	listToReturn.add( fv );
    		
    	return listToReturn;
    }
}