objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Collection_Recourse_Code__c</fullName>
        <description>Copy of the recourse code from the case</description>
        <label>Collection Recourse Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Repo_Recovery_Activity_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A list of activity used by the repo/recovery process.</description>
    <label>Repo/Recovery Activity Codes</label>
</CustomObject>

classes/TFSC_ActivityModelTest.cls
@isTest
private class TFSC_ActivityModelTest {
    
    //Setup test data
    static String testFAId = null;
    static String testFARecourseCode = null;
    static String testFACId = null;
    static String testFANumber = null;
    static String testActivityCode = 'CMNP';
    

    private static void setupTestFA(){

        Account acct = TFSC_TestUtils.setupAndReturnNewAccount();
        Financial_Account__c testFA = TFSC_TestUtils.setupAndReturnNewFinancialAccount(acct);
        Financial_Account_Customer__c testFAC = TFSC_TestUtils.setupAndReturnFAC(testFA, acct, 'Primary');

        testFAId = testFA.Id;
        testFACId = testFAC.Id;
        testFARecourseCode = testFA.Collection_Recourse_Code__c;
        testFANumber = testFA.Name;
        System.debug('*************** testFAId: ' + testFAId);

    }

    private static void setupTestTask(){

        String activityCode = 'CMNP';

        Task note = new Task(ActivityDate = Date.today(),
                             Collection_Activity_Code__c = testActivityCode,
                             Description = 'Test note',
                             Financial_Account_Number__c = testFANumber,
                             Financial_Account__c = testFAId,
                             Priority = 'Normal',
                             Source_System_Created_By__c = 'SFDC',
                             Status = 'Completed',
                             Subject = testActivityCode + ' - Test',
                             WhatId = testFAId
                            );

        insert note;

    }

    private static void setupCustomSetting(){

        Repo_Recovery_Activity_Codes__c testSetting = new Repo_Recovery_Activity_Codes__c(Name = testActivityCode);

        insert testSetting;

    }

    //Execute test
    static testmethod void testActivityModel(){
        setupTestFA();
        setupTestTask();
        setupCustomSetting();
      
        List<String> testFAIds = new List<String>();
        String currentDate = String.valueOf(Date.today().month()) +'/'+ String.valueOf(Date.today().day()) +'/' +String.valueOf(Date.today().year());
        // 5/22/2015
        
        
        
        System.debug('************************ currentDate: ' +currentDate);
        testFAIds.add(testFAId);

        Test.startTest();
        List<String> contactDates = TFSC_ActivityModel.LookupMostRecentContactDate(testFAIds);
        Test.stopTest();

        System.debug('************************ returned date: ' + contactDates.get(0));
        System.assert(contactDates.size() > 0);
       
      //  String[] strcontactDate = new List<String>();
        
        
      /*  
       // String[] strcontactDate = new String()[];
        if(contactDates.get(0).contains(':')){
           strcontactDate = contactDates.get(0).Split(':');
        }
        system.debug('@@@'+strcontactDate);
      */
      
      
        System.assertEquals(contactDates.get(0), currentDate );


    }


}