objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Field__c.object
<CustomObject>
    <description>Represents fields that appear on forms in the Adobe Forms Service. The columns identify source objects and fields, the target field on Document Request, and special processing instructions.</description>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The source field from which the data should be fetched.</description>
        <label>Source Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Object__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The source object from which the data should be fetched.</description>
        <label>Source Object</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Form Field</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>Salvage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to support different notice of sale form for salvage.</description>
        <label>Salvage</label>
        <type>Checkbox</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>BK_Active_or_Discharged__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to indicate whether the financial account is in an active or discharged bankruptcy status. Used by Apex classes (generate doc request and validate repossession) to validate whether all related FACs have been assigned a bankruptcy status.</description>
        <formula>IF(CASE(Financial_Account__r.Bankruptcy_Flag__c,
&quot;A&quot;, 1,
&quot;B&quot;, 1,
&quot;C&quot;, 1,
&quot;D&quot;, 1,
&quot;T&quot;, 1,
&quot;E&quot;, 1,
&quot;F&quot;, 1,
&quot;G&quot;, 1,
&quot;H&quot;, 1,
0
) = 1, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BK - Active or Discharged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The earliest date by which TFS may sell a repossessed vehicle. Calculated date based upon the proposed notice date and adding days as defined in the related form rule record.</description>
        <label>Proposed Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recorded_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Updated from proposed legal sale date when rights letter is generated. Will reflect the date from the latest generated notice.</description>
        <label>Recorded Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reinstatement_Denial_Reason__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: When optional reinstatement rights are denied, this picklist provides the abbreviated version of the denial reason for the user to select.</description>
        <label>Reinstatement Denial Reason</label>
        <picklist>
            <controllingField>Conditional_Reinstatement__c</controllingField>
            <picklistValues>
                <fullName>Reinstated 1x Last 12 Mos / 2x in Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concealed Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acts of Destruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acts of Violence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commission of Crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seizure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy Discharge - Filing Parties Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salvage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Indicates whether the vehicle has been sufficiently damaged to disqualify it from the standard auction process. User checks the box after reviewing the damage details provided by the repo and/or auction agencies.</description>
        <label>Salvage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transport_Fees_for_Form__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: Formula field to exempt CT from transportation fees.</description>
        <formula>IF(State_of_Jurisdiction__c = &quot;CT&quot;, 0, United_Road_Transport_Fees__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transport Fees for Form</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Comments__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: User-entered comments to explain soft validation failures. Entry required to generate a letter if any soft validation failures exist.</description>
        <label>Validation Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_Utility.cls
global class RL_Utility {
    // Adds business days to a given DateTime based on a BusinessHours calendar
    static public DateTime AddBusinessDays(DateTime StartDate, integer BusinessDaysToAdd, Id bHoursId) {
      //Add or decrease in BusinessDaysToAdd days 
        DateTime finalDate = StartDate;
        while(BusinessDaysToAdd != 0)
        {
            finalDate = finalDate.AddDays(1);
            if (BusinessHours.isWithin(bHoursId, finalDate)){
                BusinessDaysToAdd -= 1;
            }
        }
        return finalDate;
    }

    static public Repossession__c executeRepoQuery(List<String> repoFields, Id repoId) {
        String query = 'SELECT ';
        for (String field : repoFields) {
            query += field + ', ';
        }
        query += 'Name FROM Repossession__c WHERE Id =: repoId';
        return Database.query(query);
    }

    static public List<String> getListOfRepoFields() {
        List<Form_Field__c> repoFormFields = [SELECT Id, Name, Source_Field__c, Source_Object__c FROM Form_Field__c WHERE Source_Object__c =: 'Repossession__c'];
        List<String> fieldsList = new List<String>();
        for (Form_Field__c ff : repoFormFields) {
            fieldsList.add(ff.Source_Field__c);
        }
        fieldsList.addAll(new String[] {'Financial_Account__r.Financial_Account_Number__c', 'Case__r.Form_Rule__c', 'Id', 'Salvage__c', 'Validation_Comments__c', 'Validation_Comments__c', 
            'Recorded_Legal_Sale_Date__c', 'Proposed_Legal_Sale_Date__c', 'Case__c', 'BK_Active_or_Discharged__c', 'Transport_Fees_for_Form__c', 'recordtype.name','Reinstatement_Denial_Reason__c'});
        Set<String> repoFormFieldsSet = new Set<String>(fieldsList); //Remove duplicate fields.
        return new List<String>(repoFormFieldsSet);
    }
    
    
    /*
     * getQueryStringForSelectStar()
     * fldObjMapfldObjMap = schema.SObjectType.Case.fields.getMap();
     * sobjType = 'Case' or 'Repossession__c' for example
     *
    */ 
    
    static public String getQueryStringForSelectStar(Map<String, Schema.SObjectField> fldObjMap, String sobjType, String[] otherRelationshipFieldsToInclude) {
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        
        String queryString = 'SELECT ';
        Boolean appendComma = false;
        for(Schema.SObjectField s : fldObjMapValues)
        {
            String theName = s.getDescribe().getName();
            //Boolean isFormula = s.getDescribe().isCalculated() ;
            
            if(appendComma) {
                queryString += ',' ;
            }
            queryString += theName;
            appendComma = true;
        }
        
        if(otherRelationshipFieldsToInclude != null) {
            for(String otherField : otherRelationshipFieldsToInclude) {
                queryString += ',' ;
                queryString += otherField ;
            }
        }
        
        queryString += ' FROM ' + sobjType + ' ';
        
        return queryString;
    }
    
}