objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Finance_Account_Status__c</fullName>
        <label>Finance Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist_Data_Goes_Here</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Repossession__c</fullName>
        <formula>CASE(Risk_Strategy_Code_3__c,
&quot;CND&quot;, &quot;COND - Assign based on account status&quot;,
&quot;NOR&quot;, &quot;NOR - Do not assign&quot;,
&quot;RPO&quot;, &quot;RCVR - Assign for repossession&quot;,
&quot;XXX&quot;, &quot;&quot;,
&quot;&quot;, &quot;COND - Assign based on account status&quot;,
Risk_Strategy_Code_3__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Repossession</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: T/F whether certified mailing requirements apply.</description>
        <label>Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to align Form Rule with the case.</description>
        <label>State of Jurisdiction</label>
        <type>TextArea</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Financial account for which repo is executed. Value assigned during RL Set State Conditions Flow from the provided iRepo account number when VIN matches and able to be re-assigned by the user.</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Notice_Date_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Checkbox to suppress recalculation of proposed notice date if the user has overridden it. Set by RL Set Proposed Notice Date Override workflow and unset in triggered flow wait action.</description>
        <label>Proposed Notice Date Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposed_Notice_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Calculated date to print on letter. Usually today&apos;s date, but may be advanced to next business day by code if mailing cutoff time has passed. Mailing cutoff times are specified in RL_Mail_Cutoff... custom labels.</description>
        <label>Proposed Notice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state of residence for the primary borrower if in the 50 states, otherwise it is the state of the dealer. The rights letters process follows the laws in the given state. The value is set by the RL Set State Conditions flow.</description>
        <label>State of Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_RepoHiddenCompCtrlTest.cls
@isTest
private class RL_RepoHiddenCompCtrlTest {
	
	
    static testmethod void testControllerInitAndActionFunction() {
                
        Financial_Account__c financialAccount = new Financial_Account__c(
                                                            Financial_Account_Number__c = '400921', 
                                                            Finance_Account_Status__c = 'Open');
        insert financialAccount;
        
        Case rlCase = generateAndInsertCase(financialAccount.Id);
        
        Repossession__c repo = generateAndInsertRepo(rlCase);
        
        repo = [select id, Proposed_Notice_Date__c, Case__r.RL_System_Required_Notice_Date_Time__c,
                    State_of_Jurisdiction__c, Case__r.BusinessHoursId, Financial_Account__r.RecordType.Name,
                    Case__c, Proposed_Notice_Date_Override__c, Case__r.Form_Rule__c, Case__r.Form_Rule__r.Certified__c 
                 from Repossession__c where id = :repo.Id]; //doing this to get values populated via page layout.        

        PageReference pageRef = Page.RL_RepoHiddenComponent;
        //RL_TakeOwnershipPassThru?cs1={id1}&cs2={id2}
            
        ApexPages.StandardController standardController = new ApexPages.StandardController(repo);
        RL_RepoHiddenComponentController ctrl = new RL_RepoHiddenComponentController(standardController);
        
        User testUser = TFSC_TestUtils.generateTestUser(RL_Constants.RL_AGENT_PROFILE_NAME, true);        
        System.RunAs(testUser)
        {
            Test.setCurrentPage(pageRef);

            system.assert(ctrl.errorStringOnUpdate == null || ctrl.errorStringOnUpdate == '');
            system.assert(ctrl.businessHrs != null);
            
            ctrl.updateProposedStartDate();
        }
    }
    
    
    private static Case generateAndInsertCase(Id financialAccountId) {
        Id recordTypeId = TFSC_Utils.getRecordTypeIdFromDeveloperNameAndsObjectName('Rights_Letter_on_case', 'Case');
        System.debug(recordTypeId);
        List<BusinessHours> bhs=[select id from BusinessHours where IsDefault=true];
        
        Case caseToInsert = new Case( Financial_Account__c = financialAccountId,
                                      BusinessHours = bhs,
                                      RecordTypeId = recordTypeId );
        
        insert caseToInsert;
        return caseToInsert;
    }
    
    
    private static Repossession__c generateAndInsertRepo(Case rlCase) {
    	
    	Repossession__c repo = new Repossession__c();
    	repo.Case__c = rlCase.Id;
    	
    	
    	insert repo;
    	return repo;
    }
    
    
    
}