objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Borrower_Position__c</fullName>
        <label>Borrower Position</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Status__c</fullName>
        <label>Borrower Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Role_Type__c</fullName>
        <label>Customer Role Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Election_Overall_Consent__c</fullName>
        <label>Overall Consent</label>
        <picklist>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FA_Role_Status__c</fullName>
        <description>external ID -  Account No~Position~Status</description>
        <externalId>true</externalId>
        <label>FA Role Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Home_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Home Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Mobile_Phone_DNC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_BillTo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Flag_Work_Phone_DNC_Garage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work Phone DNC</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FlowGetFinancialAccountDataTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class FlowGetFinancialAccountDataTest {

    static testMethod void testSimple() {
      System.assertEquals('Simple', 'Simple'); 
    
    }
    
    
    static testMethod void invokeTest() {
        Test.startTest();
      
      
       String facNumber = '123testfac';
     
       Financial_Account__c financialAccount = insertFinancialAccount(facNumber);
       Financial_Account__c dbFinancialAccount = getFinancialAccount(financialAccount.id);
       
       insertFinancialAccountCustomer (financialAccount, 'Primary');
       insertFinancialAccountCustomer (financialAccount, 'Co-X');
       
        
       
       Map<String,Object> inputParams = new Map<String,Object>();
       Map<String,Object> outputParams = new Map<String,Object>();
       
       
       inputParams.put('vFinanceAccountId',facNumber);
       
       
       
       FlowGetFinancialAccountData fgfad = new FlowGetFinancialAccountData();
       Process.PluginRequest request = new Process.PluginRequest(inputParams);
       
       try {
         fgfad.describe();
         fgfad.invoke(request);
       }
       catch (Exception e){
        System.Debug(e);
        
       }
       
        
       
       
       
       Test.StopTest();
    }
    
    
      private static void insertFinancialAccountCustomer(Financial_Account__c financialAccount, String borrowerPosition) {
        
        
     Account acct = new Account(Name  = 'Test Account');
     insert acct;
     
     Financial_Account_Customer__c newFac = new Financial_Account_Customer__c (
           Borrower_Position__c = borrowerPosition
           ,Financial_Account__c = financialAccount.Id
      
           ,Election_Overall_Consent__c ='Y'
        
          ,Flag_Home_Phone_DNC_Garage__c = true
          ,Flag_Home_Phone_DNC_BillTo__c = true
          
           ,Flag_Work_Phone_DNC_Garage__c = true
           ,Flag_Work_Phone_DNC_BillTo__c = true
           
           ,Flag_Mobile_Phone_DNC__c = true
           
           ,Account__c = acct.Id
           ,Borrower_Status__c = 'Active'
           ,Customer_Role_Type__c = 'test'
           ,FA_Role_Status__c = 'test'
           ,Financial_Account_Customer__c = 'test2' + TFSC_TestUtils.generateRandomString(4) 
                     
         );
         insert newFac;
    }
   
   
    
     private static Financial_Account__c insertFinancialAccount( String facNumber) {
        
        Financial_Account__c financialAccount = new Financial_Account__c(Financial_Account_Number__c = facNumber);
        insert financialAccount;
        
       
       
        return financialAccount;
    }
    
    private static Financial_Account__c getFinancialAccount(String id) {
        Financial_Account__c financialAccount = [ SELECT id, Financial_Account_Number__c FROM Financial_Account__c WHERE id=:id];
        
        return financialAccount;
    }
}