objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TFSC_CureNoteInfoControllerTest.cls
@isTest
private class TFSC_CureNoteInfoControllerTest {
    
    
    static testmethod void testController() {
    	
    	String cureString = TFSC_CureNoteInfoController.cureNoticeSent ;
    	
    	Account acct = TFSC_TestUtils.setupAndReturnNewAccount();
    	Financial_Account__c fa = TFSC_TestUtils.setupAndReturnNewFinancialAccount(acct, '199d7vf');
    	Task tsk = new Task(ActivityDate = Date.today(),
							 Collection_Activity_Code__c = 'CURE',
							 Description = cureString + ' $123.12 test expires 121215 ',
							 Financial_Account_Number__c = '1234',
							 Financial_Account__c = fa.Id,
							 Priority = 'Normal',
							 Source_System_Created_By__c = 'SFDC',
							 Status = 'Completed',
							 Subject = 'TEST' + ' - Test',
							 WhatId = fa.Id
							);
		insert tsk;
		
    	
    	test.startTest();
			ApexPages.StandardController standardController = new ApexPages.StandardController(fa);
			TFSC_CureNoteInfoController controllerExt = new TFSC_CureNoteInfoController(standardController);
    		
    		String cureAmnt = controllerExt.getCureAmount();
    		String cureExpDate = controllerExt.getCureExpDate();
    		String cureNote = controllerExt.getCureNote();
    		Date tempDt = Date.newInstance(2015, 12, 12);
            String controllerDate = tempDt.format();
            
            system.assertEquals(cureExpDate, controllerDate);
            system.assertEquals('$123.12', cureAmnt);
    		
    		
    	test.stopTest();
    	
    	
    }
    
    

}