objects/Financial_Account__c.object
<CustomObject>
    <description>Loan and lease products purchased by customers to finance vehicle acquisition. The financial
account represents the financial obligation carried by the borrower and co-­‐borrower. This is
TFS’s core business product and servicing the financial account is the primary focus of
operations.</description>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <description>external financeaccount number</description>
        <externalId>true</externalId>
        <label>Financial Account Number</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>HomePhone BillTo</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Financial_Account_Customer__c.object
<CustomObject>
    <description>Junction object linking a financial account to its primary borrower(s) and co-­‐borrower(s) and
captures customer information related to the specific account such as privacy settings.</description>
    <fields>
        <fullName>Financial_Account_Customer__c</fullName>
        <externalId>true</externalId>
        <label>Financial Account Customer</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Financial_Account_Number__c</fullName>
        <formula>Financial_Account__r.Financial_Account_Number__c</formula>
        <label>(IVR) Financial Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Account Customers</relationshipLabel>
        <relationshipName>Financial_Account_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HomePhone_BillTo__c</fullName>
        <description>Home Phone Number</description>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Home_Phone_Garage__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <description>Mobile Number</description>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Bill_To__c</fullName>
        <description>Work Phone Number</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Phone_Garage__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Account Customer</label>
    <nameField>
        <label>Financial Account Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Account Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Skip_Trace__c.object
<CustomObject>
    <description>Transformed copy of skip trace notes entered in Collections Host PF11 screen and primary
location for creation and maintenance of skip trace information within Salesforce.</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Skip Trace</relationshipLabel>
        <relationshipName>Skip_Trace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone10__c</fullName>
        <label>Phone10</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone11__c</fullName>
        <label>Phone11</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone12__c</fullName>
        <label>Phone12</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone13__c</fullName>
        <label>Phone13</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone14__c</fullName>
        <label>Phone14</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone15__c</fullName>
        <label>Phone15</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone16__c</fullName>
        <label>Phone16</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone17__c</fullName>
        <label>Phone17</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone18__c</fullName>
        <label>Phone18</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone19__c</fullName>
        <label>Phone19</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone1__c</fullName>
        <label>Phone1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone20__c</fullName>
        <label>Phone20</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone21__c</fullName>
        <label>Phone21</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone22__c</fullName>
        <label>Phone22</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone23__c</fullName>
        <label>Phone23</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone24__c</fullName>
        <label>Phone24</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone25__c</fullName>
        <label>Phone25</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone26__c</fullName>
        <label>Phone26</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone27__c</fullName>
        <label>Phone27</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone28__c</fullName>
        <label>Phone28</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone29__c</fullName>
        <label>Phone29</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone2__c</fullName>
        <label>Phone2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone30__c</fullName>
        <label>Phone30</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone31__c</fullName>
        <label>Phone31</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone32__c</fullName>
        <label>Phone32</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone33__c</fullName>
        <label>Phone33</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone34__c</fullName>
        <label>Phone34</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone35__c</fullName>
        <label>Phone35</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone36__c</fullName>
        <label>Phone36</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone37__c</fullName>
        <label>Phone37</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone38__c</fullName>
        <label>Phone38</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone39__c</fullName>
        <label>Phone39</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone3__c</fullName>
        <label>Phone3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone40__c</fullName>
        <label>Phone40</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone41__c</fullName>
        <label>Phone41</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone42__c</fullName>
        <label>Phone42</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone43__c</fullName>
        <label>Phone43</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone44__c</fullName>
        <label>Phone44</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone45__c</fullName>
        <label>Phone45</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone46__c</fullName>
        <label>Phone46</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone47__c</fullName>
        <label>Phone47</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone48__c</fullName>
        <label>Phone48</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone49__c</fullName>
        <label>Phone49</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone4__c</fullName>
        <label>Phone4</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone50__c</fullName>
        <label>Phone50</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone5__c</fullName>
        <label>Phone5</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone6__c</fullName>
        <label>Phone6</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone7__c</fullName>
        <label>Phone7</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone8__c</fullName>
        <label>Phone8</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone9__c</fullName>
        <label>Phone9</label>
        <type>Phone</type>
    </fields>
    <label>Skip Trace</label>
    <nameField>
        <label>Skip Trace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skip Trace</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tempinteraction__c.object
<CustomObject>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <label>Interaction Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Temp Interaction</label>
    <nameField>
        <label>Temp Interaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temp Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TFSC_ConsoleManagerController.cls
/**
*   Modified By : Paras Dhingra
*   Modified Date : 7/6/2015
*   Story : S-311850
*   Description : To update the Service type based on the values from tempInteractionType custom setting on case creation.
*/
global with sharing class TFSC_ConsoleManagerController {
    
    
    
    public TFSC_ConsoleManagerController() {
        
    }
    
    @RemoteAction
    global static String getObjectIdFromAccountNumber(String accountNum) {
        String strToReturn;
        
        if(accountNum != null && accountNum.length() > 0) {
            for(Financial_Account__c fac : [select id from Financial_Account__c 
                                              where Financial_Account_Number__c = :accountNum 
                                              limit 1]) 
            {
                strToReturn = fac.Id;
            }
        }
        
        return strToReturn;
    }
    
    @RemoteAction
    global static List<TFSC_ConsoleManagerController.FaObject> getFaObjectsFromFaIdList(List<String> idList) {
        List<TFSC_ConsoleManagerController.FaObject> listToReturn = new List<TFSC_ConsoleManagerController.FaObject>();
        for(Financial_Account__c fa : [select id, Financial_Account_Number__c,
                                           (
                                               select Financial_Account_Customer__c.id, 
                                               Financial_Account_Customer__c.Work_Phone_Garage__c,
                                               Financial_Account_Customer__c.Mobile_Phone__c, 
                                               Financial_Account_Customer__c.Home_Phone_Garage__c,
                                               Financial_Account_Customer__c.Work_Phone_Bill_To__c,
                                               Financial_Account_Customer__c.HomePhone_BillTo__c
                                               from Financial_Account__c.Financial_Account_Customers__r
                                            ),
                                            (
                                               select id, 
                                               Phone1__c, Phone10__c, Phone11__c, Phone12__c, Phone13__c, Phone14__c, 
                                               Phone15__c, Phone16__c, Phone17__c, Phone18__c, Phone19__c, Phone2__c, 
                                               Phone20__c, Phone21__c, Phone22__c, Phone23__c, Phone24__c, Phone25__c, 
                                               Phone26__c, Phone27__c, Phone28__c, Phone29__c, Phone3__c, Phone30__c, 
                                               Phone31__c, Phone32__c, Phone33__c, Phone34__c, Phone35__c, Phone36__c, 
                                               Phone37__c, Phone38__c, Phone39__c, Phone4__c, Phone40__c, Phone41__c, 
                                               Phone42__c, Phone43__c, Phone44__c, Phone45__c, Phone46__c, Phone47__c, 
                                               Phone48__c, Phone49__c, Phone5__c, Phone50__c, Phone6__c, Phone7__c, 
                                               Phone8__c, Phone9__c
                                               from Financial_Account__c.Skip_Trace__r
                                            )
                                         from Financial_Account__c
                                         where id in :idList
                                         limit 1000]) 
        {
            TFSC_ConsoleManagerController.FaObject faObj = new TFSC_ConsoleManagerController.FaObject();
            faObj.faId = fa.Id;
            faObj.faAcctNum = fa.Financial_Account_Number__c ;
            for(Financial_Account_Customer__c fac : fa.Financial_Account_Customers__r) {
                if( !TFSC_Utils.isNullOrEmpty(fac.Work_Phone_Garage__c) ){
                    faObj.facPhoneList.add( fac.Work_Phone_Garage__c.replaceAll('[^0-9]','') );
                }
                if( !TFSC_Utils.isNullOrEmpty(fac.Mobile_Phone__c) ){
                    faObj.facPhoneList.add( fac.Mobile_Phone__c.replaceAll('[^0-9]','') );
                }
                if( !TFSC_Utils.isNullOrEmpty(fac.Home_Phone_Garage__c) ){
                    faObj.facPhoneList.add( fac.Home_Phone_Garage__c.replaceAll('[^0-9]','') );
                }
                if( !TFSC_Utils.isNullOrEmpty(fac.HomePhone_BillTo__c) ){
                    faObj.facPhoneList.add( fac.HomePhone_BillTo__c.replaceAll('[^0-9]','') );
                }
                if( !TFSC_Utils.isNullOrEmpty(fac.Work_Phone_Bill_To__c) ){
                    faObj.facPhoneList.add( fac.Work_Phone_Bill_To__c.replaceAll('[^0-9]','') );
                }
                
            }
            for(Skip_Trace__c skipTrace : fa.Skip_Trace__r) {
                for(Integer i=1; i<51; i++){
                    String phoneField = 'Phone' + String.valueOf(i) + '__c'; 
                    String skipPhoneNum = (String)skipTrace.get(phoneField);
                    if(skipPhoneNum != null && skipPhoneNum.length() > 0) {
                        skipPhoneNum = skipPhoneNum.replaceAll('[^0-9]','');
                        if(skipPhoneNum.length() > 0) {
                            faObj.facPhoneList.add(skipPhoneNum);
                        }
                    }
                }
            }
            listToReturn.add( faObj );
        }
        
        return listToReturn;
    }
    // Created for Story S-311850 #start By paras Dhingra 7/6/2015
    @RemoteAction
    global static void setInteractionType(String Id, String iType){ // Set unique Custom setting for the interaction type. 
        if( Id !=null && iType!=null){
            list<tempinteraction__c> interactionlist = [SELECT Name, Interaction_Type__c FROM tempinteraction__c WHERE Name = :Id LIMIT 1];
            if(interactionlist.size() != 0){
                interactionlist[0].Interaction_Type__c = iType;
                update interactionlist[0];
            }else{
                tempinteraction__c interaction  = new tempinteraction__c(name = id, Interaction_Type__c = iType);
                insert interaction;
            }            
        }

    }
    // Remote action to delete the interactiontype when the FA tab is closed
    @RemoteAction
    global static void deleteInteractionType(String id){
        if( Id !=null){
            list<tempinteraction__c> interactionlist = [SELECT Name, Interaction_Type__c FROM tempinteraction__c WHERE Name = :Id LIMIT 1];
            if(interactionlist.size() != 0){
                try{
                    delete interactionlist[0]; // Delete the interactionType once the scope of FA dies
                    }catch(Exception e){

                }
                
            }
        }
    }
    // Story S-311850 #End
    global class FaObject{
        
        public String faId{get;set;}
        public String faAcctNum{get;set;}
        public List<String> facPhoneList{get;set;}
        
        public FaObject() {
            facPhoneList = new List<String>();
        }
        
    }
    
}