objects/Form_Rule__c.object
<CustomObject>
    <description>In the initial processing of rights letters, drives correct form selection, links to form definition objects, and encodes compliance values.</description>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Primary selection criteria to align Form Rule with the case.</description>
        <label>State of Jurisdiction</label>
        <type>TextArea</type>
    </fields>
    <label>Form Rule</label>
    <nameField>
        <label>Form Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>CA_Insurance_Fee_Refund__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: Formula field to add CLAH and GAP refunds the user has determined are due to the customer in CA according to the contract.</description>
        <formula>CLAH_Refund__c + GAP_Refund__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CA Insurance Fee Refund</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CLAH_Refund__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Amount of credit, life, accident, health insurance refund the customer is entitled to when part of contract and where state of jurisdiction is CA.</description>
        <label>CLAH Refund</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Excluded_Fee_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: An amount entered by the user to exclude certain fees from the gross balance/redemption amount when they have been included in miscellaneous fees.</description>
        <label>Excluded Fee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GAP_Refund__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Amount of GAP refund entered by the user and required by the contract - pro rated to remaining term. Applies to state of jurisdiction in CA for retail loans.</description>
        <label>GAP Refund</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Impound_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo
INT: iRepo M2 TIBCO Pull
Trans: N
BU: RL
FD: Impound fee (repairs, citations, etc.) sent from iRepo for release of vehicle. Included in total balance owed.</description>
        <label>Impound Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Local_Repo_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Date of the repossession at the place of repossession. Since date/time is received in GMT, date must be converted to a local date and stored here. Handled within the RL Set State Conditions Flow and associated date/time Apex plug-in.</description>
        <label>Local Repo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Other_Charges1__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Captures charges that may come with the repossession that don&apos;t fit in other designated fields on the form. Not expected to be used, but available in case form development can&apos;t turn around a new requirement in time to meet compliance concerns.</description>
        <label>Other Charges1</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Charges2__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Unanticipated charges that don&apos;t fit within existing currency fields. Intended to capture fees that may be required by compliance, but don&apos;t have a designated separate field for entry. Contingency field in case forms development process cannot enable a designated field in time to meet compliance requirement.</description>
        <label>Other Charges2</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Property_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo
INT: iRepo M2 TIBCO Pull
Trans: N
BU: RL
FD: Fee optionally assessed in repossession process and sourced from iRepo.</description>
        <label>Personal Property Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Police_Agency_Fee__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: Y
BU: RL
FD: Formula field to hard-code the $15 police reporting fee for CA in-state repossessions. The fee, if applicable, is never collected separately for any other state.</description>
        <formula>IF(Case__r.Form_Rule__r.Name = &quot;4015CA&quot;, 15, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Police Agency Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: The earliest date by which TFS may sell a repossessed vehicle. Calculated date based upon the proposed notice date and adding days as defined in the related form rule record.</description>
        <label>Proposed Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recorded_Legal_Sale_Date__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Updated from proposed legal sale date when rights letter is generated. Will reflect the date from the latest generated notice.</description>
        <label>Recorded Legal Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Redemption_Processing_Fee__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo 
INT: iRepo M2/NOI template data 
Trans: N 
BU: RL 
FD: An additional fee charged by repossession agencies when processing a possible redemption request.</description>
        <label>Redemption Processing Fee</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Repossession_Costs__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: iRepo 
INT: iRepo M2/NOI template data 
Trans: N 
BU: RL 
FD: The primary fees associated with the process of repossession and charged by the repossession agency as provided by iRepo.</description>
        <label>Repossession Costs</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Zip_Code__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: Defaults to 5+4 zip code from primary borrower. User may correct, if needed. Zip code is passed to Vertex for sales tax calculation.</description>
        <label>Sales Tax Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Vertex 
INT: Vertex Tax Service 
Trans: N 
BU: RL 
FD: Sales tax amount for lease sales. Applies in some states to transfer ownership from TFS to lessee upon redemption. User clicks Vertex button and total sale price is provided to Vertex along with zip code. Vertex provides tax amount in response.</description>
        <label>Sales Tax</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State_of_Jurisdiction__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The state of residence for the primary borrower if in the 50 states, otherwise it is the state of the dealer. The rights letters process follows the laws in the given state. The value is set by the RL Set State Conditions flow.</description>
        <label>State of Jurisdiction</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party_Other_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: An optional fee for the user to enter. May be an exceptional fee that applies only in some states.</description>
        <label>Third Party Other Fees</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Title_Zip__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: N 
BU: RL 
FD: The zip code to which the vehicle title should be sent. Usually it is the auction location.</description>
        <label>Title Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalRedemptionAmount__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: Formula field to calculate the total purchase amount for the vehicle - a payoff in the case of a repossession.</description>
        <formula>UnpaidGrossBalance__c + IF(Financial_Account__r.RecordType.Name = &quot;Retail&quot;, Financial_Account__r.Charges_Late__c, 0) + Repossession_Costs__c + IF(State_of_Jurisdiction__c != &quot;CT&quot;, United_Road_Transport_Fees__c, 0) + Impound_Fee__c + Other_Charges1__c + Other_Charges2__c + IF(Financial_Account__r.RecordType.Name = &quot;Lease&quot;, Sales_Tax_for_Form__c + Financial_Account__r.Security_Deposit_Amount__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Redemption Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>United_Road_Transport_Fees__c</fullName>
        <defaultValue>0</defaultValue>
        <description>SRC: United Road 
INT: United Road Auction 
Trans: N 
BU: RL 
FD: The fee for vehicle transportation from the repo agency to the auction. United Road coordinates the effort. The user clicks a button to query United Road for the fee based on the VIN.</description>
        <label>Transportation Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnpaidGrossBalance__c</fullName>
        <description>SRC: Salesforce 
INT: 
Trans: Y 
BU: RL 
FD: The loan/lease balance prior to application of repossession- and sale-related charges.</description>
        <formula>IF(Financial_Account__r.RecordType.Name = &quot;Retail&quot;,
Financial_Account__r.Loan_Current_Amount__c + FLOOR(Financial_Account__r.INT_PAY__c * 100)/100,
Financial_Account__r.Contract_Receivable__c + Financial_Account__r.Refund__c + Financial_Account__r.Charges_Late__c + Financial_Account__r.Payment_Amount_Past_Due__c
)
+ Financial_Account__r.Charges_Miscellaneous__c
- Excluded_Fee_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unpaid Gross Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>iRepo_VIN__c</fullName>
        <description>SRC: iRepo
INT: iRepo M1 &amp; M2 TIBCO Pull
Trans: N
BU: RL
FD: Vehicle identification number as stored in iRepo&apos;s system. Compared with the VIN on the collateral of the searched financial account to confirm a successful match between iRepo assignment and SFDC financial account. Also used as a reference to facilitate looking up a financial account for a mismatched repo.</description>
        <label>iRepo VIN</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_VertexTaxRedirectController.cls
public with sharing class RL_VertexTaxRedirectController {
    
    public String errDisplayText{get;set;}
    
    public Decimal salesPrice{get;set;}
    public Date salesTaxDate{get;set;}
    public String stateAbbrev{get;set;}
    public String zipCode{get;set;}
    
    private Repossession__c contextRepo;
    
    public RL_VertexTaxRedirectController(ApexPages.StandardController stdController) {
        initData(stdController);
    }
    
    private void initData(ApexPages.StandardController stdController) {
        String[] repoFields = new String[] {'Case__r.Form_Rule__c', 'Case__c', 'iRepo_VIN__c', 
                                            'Recorded_Legal_Sale_Date__c', 'Proposed_Legal_Sale_Date__c',
                                            'State_of_jurisdiction__c', 'UnpaidGrossBalance__c', 'TotalRedemptionAmount__c',
                                            'Sales_Tax__c', 'Sales_Tax_Zip_Code__c', 'Title_Zip__c',
                                            'CLAH_Refund__c', 'CA_Insurance_Fee_Refund__c', 'GAP_Refund__c',
                                            'Excluded_Fee_Amount__c', 'Impound_Fee__c',
                                            'Personal_Property_Fee__c','Police_Agency_Fee__c','Redemption_Processing_Fee__c',
                                            'Third_Party_Other_Fees__c','United_Road_Transport_Fees__c',
                                            'Local_Repo_Date__c', 'Repossession_Costs__c', 'Other_Charges1__c', 'Other_Charges2__c' };
        if (!Test.isRunningTest()) {  
            stdController.addFields(repoFields);
            contextRepo = (Repossession__c) stdController.getRecord();
        } else {
            contextRepo = [SELECT Id, Case__r.Form_Rule__c, Case__c, iRepo_VIN__c, Recorded_Legal_Sale_Date__c, Proposed_Legal_Sale_Date__c, State_of_Jurisdiction__c, 
                UnpaidGrossBalance__c, TotalRedemptionAmount__c, Sales_Tax__c, Sales_Tax_Zip_Code__c, Title_Zip__c, CLAH_Refund__c, CA_Insurance_Fee_Refund__c, 
                GAP_Refund__c, Excluded_Fee_Amount__c, Impound_Fee__c, Personal_Property_Fee__c, Police_Agency_Fee__c, 
                Redemption_Processing_Fee__c, Third_Party_Other_Fees__c, United_Road_Transport_Fees__c, Local_Repo_Date__c, Repossession_Costs__c, 
                Other_Charges1__c, Other_Charges2__c 
                FROM Repossession__c WHERE Id =: stdController.getId()];
        }
        
        this.salesPrice = contextRepo.UnpaidGrossBalance__c + contextRepo.Repossession_Costs__c + contextRepo.United_Road_Transport_Fees__c + contextRepo.Impound_Fee__c + contextRepo.Other_Charges1__c + contextRepo.Other_Charges2__c;
        this.salesTaxDate = date.today();
        this.zipCode = contextRepo.Sales_Tax_Zip_Code__c;
        this.stateAbbrev = contextRepo.State_of_Jurisdiction__c;
    }
    
    
    private void checkIfDataValidAndSetError() {
        errDisplayText = '';
        
        if(zipCode == null || zipCode.length() != 10 || !zipCode.contains('-')) {
            appendErrorMessage('Please enter full 5+4 format into Sales Tax Zip Code.');
        }
        
        if(salesPrice == null || salesPrice <= 0) {
            appendErrorMessage('Sales Price must be greater than zero.');
        }
        
        if(stateAbbrev == null || stateAbbrev.length() != 2) {
            appendErrorMessage('State must be two characters long (e.g. "CA").');
        }
    }
    
    public PageReference executeTaxCallout() {
        
        checkIfDataValidAndSetError();
        
        if(errDisplayText == null || errDisplayText == '') {
            try {
                
                runCallout();
                
            }catch(Exception e){
                appendErrorMessage( 'Salesforce Response: ' + e.getMessage());
                return null;
            }
        }
            
        
        if(errDisplayText == null || errDisplayText == '') {
            appendInfoMessage('Data successfully retrieved. Sales Tax field updated.  Redirecting...');
        }
        
        return null;
    }
    
    
    //wrapped in a try-catch.
    private void runCallout() {
        
        RL_WS_TaxServiceExecution.TaxService_RequestParams request;
        request = new RL_WS_TaxServiceExecution.TaxService_RequestParams();
        
        request.RequestID = TFSC_Utils.getGUID();
        request.SalesPriceAmount = salesPrice;
        request.SalesTaxDate = salesTaxDate;
        request.StateCode = stateAbbrev;
        request.ZipCode = zipCode;
        /*
            public Decimal salesPrice;
            public Date salesTaxDate;
            public String stateAbbrev;
            public String zipCode;
        */
        
        RL_WS_TaxServiceExecution.TaxService_ResponseParams response;
        if (Test.isRunningTest()) {  
            response = new RL_WS_TaxServiceExecution.TaxService_ResponseParams();
            response.StatusParams = new RL_WS_TaxServiceExecution.TaxService_StatusParams();
            response.StatusParams.Status = 'SUCCESS';
            response.responseRecord = new RL_WS_TaxServiceExecution.TaxService_ResponseRecord();
            response.responseRecord.TotalTax = 123;
            response.responseRecord.TotalAmount = 123;
        } else {
            response = RL_WS_TaxServiceExecution.getTaxRateData(request);
        }

        if(response.StatusParams != null && response.StatusParams.Status != null && response.StatusParams.Status == 'FAIL') {
            errDisplayText = 'TIBCO Error: ' + response.StatusParams.Error;
            appendErrorMessage(errDisplayText);
        }else{
            //public Decimal TotalAmount;
            //public Decimal TotalTax;
            contextRepo.Sales_Tax__c = response.responseRecord.TotalTax;
            
            if(contextRepo.Sales_Tax__c > 0 && contextRepo.State_of_Jurisdiction__c != null && contextRepo.State_of_Jurisdiction__c.equalsIgnoreCase('IL')) {
                contextRepo.Sales_Tax__c = Math.round(contextRepo.Sales_Tax__c);
            }
            
            update contextRepo;
        }
    }

    private void appendInfoMessage(String infoMessage) {
        appendMessage(infoMessage, ApexPages.Severity.INFO);
    }
    private void appendErrorMessage(String errorMessage) {
        errDisplayText = errorMessage;
        appendMessage(errorMessage, ApexPages.Severity.ERROR);
    }
    
    private void appendMessage(String errorMessage, ApexPages.severity severity) {
        ApexPages.Message apexPageMessage = new ApexPages.Message(severity, errorMessage);
        ApexPages.addMessage(apexPageMessage);
    }
}