objects/General_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Any general custom attribute that may extend the definition of a profile and/or user to provide distinct processing options - may be leveraged in workflow, formulas, and code; e.g. exempt data admin-level profiles or users from validation rules or workflows</description>
    <fields>
        <fullName>Data_Admin_Exemption__c</fullName>
        <defaultValue>false</defaultValue>
        <description>SRC: Salesforce
INT: 
Trans: N
BU: RL
FD: Exempt this profile or user from some validation rules and workflows</description>
        <inlineHelpText>Exempt this profile or user from some validation rules and workflows</inlineHelpText>
        <label>Data Admin Exemption</label>
        <type>Checkbox</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_CaseOwnershipHandler.cls
/*****
 * Salesforce.com Success Services
 * Name: RL_CaseOwnershipHandler
 * Description: Sets the case owner to Rights Letters queue when a new repossession is created
 */

public with sharing class RL_CaseOwnershipHandler implements TFSC_TriggerDispatcher.Handler {
	private QueueSObject queue;
    private List<Repossession__c> newRepoList = (List<Repossession__c>)Trigger.new;
    private List<Case> caseList;
    private List<Id> caseIdList = new List<Id>();

    public void handle() {
        General_Settings__c gs = General_Settings__c.getInstance();
        for (Repossession__c repo : newRepoList) {
            caseIdList.add(repo.Case__c);
        }
        caseList = [SELECT Id, OwnerId FROM Case WHERE Id =: caseIdList];    
        queue = [SELECT Id, Queue.Name, Queue.Id from QueueSObject WHERE Queue.Name = 'Rights Letters' AND SObjectType = 'Case'];
        for (Case aCase : caseList) {
            if (gs.Data_Admin_Exemption__c) {
                aCase.OwnerId = queue.Queue.Id;
            }
        }
        update caseList;
    }
}