objects/Km_Chatter_Log__c.object
<CustomObject>
    <fields>
        <fullName>ChatterText__c</fullName>
        <label>ChatterText</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Has_Feedback_Tag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has #Feedback</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>articleNumber__c</fullName>
        <label>Article Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>articleTitle__c</fullName>
        <label>Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>articleType__c</fullName>
        <label>Article Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>kavId__c</fullName>
        <description>BL removed required attribute on Mar 9th - draft article does not have a kavid.</description>
        <label>kavId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>versionNumber__c</fullName>
        <label>Version Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Km Chatter Log</label>
    <nameField>
        <displayFormat>KCL-{00000000}</displayFormat>
        <label>Km Chatter Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Km Chatter Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TFSC_FeedCommentHandler.cls
public class TFSC_FeedCommentHandler implements TFSC_TriggerDispatcher.Handler {

	public void handle() {	
		System.Debug('TFSC_FeedCommentHandler::handle   size='+trigger.new.size());
		processChatterFeedItemsForKnowledgeManagement((List<FeedComment>)trigger.new);
	}

	private void processChatterFeedItemsForKnowledgeManagement(List<FeedComment> feedComments) {
		
		if (!PermissionSetModel.hasStandaloneKnowledgePermissionSet()) {
			return;
		}
		
		//1 - find a list of FeedItem & parent id
		List<Id> feedItemIdList = New List<Id>();
		for(FeedComment fc : feedComments) {
			if ( !PermissionSetModel.hasKnowledgeAdminPermissionSet()) {
				feedItemIdList.add(fc.FeedItemId);
			}
		}
		
		List<FeedItem> itemList = [
			select id, parentId
			from FeedItem
			where id in :feedItemIdList
		];
		
		System.Debug('processChatterFeedItemsForKnowledgeManagement found itemList '+
			itemList.size());
		
		Map<Id, Id> mapFeedItemParentId = new Map<Id, Id>();
		for(FeedItem item : itemList) {
			//filter just 
			if (  item.ParentId != null && ArticleFeedbackModel.getArticleType(item.ParentID) != null ) {
				mapFeedItemParentId.put(item.id, item.ParentId);
			} else {
				System.Debug('processChatterFeedItemsForKnowledgeManagement - parent id is not an article' +
					item.ParentId);
			}
		}
		
		Map<Id, ArticleFeedbackModel.kavDetails> kavDetailsMapByKaId  =
			ArticleFeedbackModel.FindKnowledgeArticleDetails(mapFeedItemParentId.Values());
		
		//
		List<Km_Chatter_Log__c> chatterLogList = new List<Km_Chatter_Log__c>();
		for(FeedComment fc : feedComments) {
			if (mapFeedItemParentId.containsKey(fc.FeedItemId) ) {
				Km_Chatter_Log__c chatterLog = new Km_Chatter_Log__c();
				
				
				if ( fc.CommentBody.length() < 255) {
					chatterLog.ChatterText__c = fc.CommentBody;
				} else {
					chatterLog.ChatterText__c = fc.CommentBody.substring(0,254);
				}
				if ( fc.CommentBody.containsIgnoreCase('#feedback')) {
					chatterLog.Has_Feedback_Tag__c = true;
				} else {
					chatterLog.Has_Feedback_Tag__c = false;
				}
				
				Id feedItemId = fc.FeedItemId;
				Id kaId = mapFeedItemParentId.get(feedItemId);
				if (kavDetailsMapByKaId.containsKey(kaId)) {
					ArticleFeedbackModel.kavDetails kavDetail = kavDetailsMapByKaId.get(kaId);
					
					chatterLog.kavId__c = kavDetail.knowledgeArticleVersionId;
					chatterLog.articleType__c = kavDetail.articleType;
					chatterLog.articleNumber__c = kavDetail.articleNumber;
					chatterLog.versionNumber__c = kavDetail.versionNumber;
					chatterLog.articleTitle__c = kavDetail.articleTitle;  
				}
				
				chatterLogList.add(chatterLog);
				
			}
		}	
		 
		if ( chatterLogList.size() > 0) {
			insert chatterLogList;
		}
	}
	
	
	
	
}