objects/Payment_Method__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Payment methods specified in a promise to pay and associated rules/mappings</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Controls the sort order for the setting&apos;s records</description>
        <label>Sort Order</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payment Method</label>
</CustomObject>

classes/PaymentMethodWrapper.cls
global class PaymentMethodWrapper implements Comparable{

	public Payment_Method__c pmtMethod;
    
    // Constructor
    public PaymentMethodWrapper(Payment_Method__c pMethod) {
        pmtMethod = pMethod;
    }
    
    // Compare RFD options based on the sort order.
    global Integer compareTo(Object compareTo) {
        // Cast argument to PaymentMethodWrapper
        PaymentMethodWrapper compareToPmtMethod = (PaymentMethodWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (pmtMethod.Sort_Order__c > compareToPmtMethod.pmtMethod.Sort_Order__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (pmtMethod.Sort_Order__c < compareToPmtMethod.pmtMethod.Sort_Order__c) {
            // Set return value to a negative value.
            returnValue = -1;
        }
        
        return returnValue;       
    }

}