objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_NewRightsLetterControllerTest.cls
@isTest
private class RL_NewRightsLetterControllerTest {
    
    @isTest static void test_method_one() {
        
        // Ensure page loads properly
        PageReference pageRef = Page.RL_NewRightsLetter;
        Test.setCurrentPage(pageRef);

        // Setup controller test with Case standard controller and page extension
        Case blankCase = new Case();
        ApexPages.StandardController caseStdController = new ApexPages.StandardController(blankCase);
        RL_NewRightsLetterController controller = new RL_NewRightsLetterController(caseStdController);

        // Invoke the RL case creation
        controller.createRightsLetter();

        // Verify case is created
        Id createdCaseId = controller.newCaseId;
        Case[] cases = [select Id from Case where Id = :createdCaseId];
        System.assertEquals(createdCaseId, cases[0].Id);
        
        // Verify the associated repo is created
        Repossession__c[] repos = [select Id from Repossession__c where Case__c = :createdCaseId];
        System.assertEquals(repos.size(), 1);
    }
}