objects/Repossession__c.object
<CustomObject>
    <description>Extension of Case object to initially support Rights Letters, but can be extended to other repossession-related processes.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SRC: Salesforce
INT: iRepo M1 Integration
Trans: N
BU: RL
FD: Relationship between Repossession and Case created at creation by iRepo integration or manually creating new rights letter case, which generates the Repossession record at the same time (Visualforce page exposed as tab).</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Repossessions</relationshipLabel>
        <relationshipName>Repossessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Repossession</label>
    <nameField>
        <displayFormat>RPO-{000000}</displayFormat>
        <label>Repossession ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repossessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RL_NewRightsLetterController.cls
public with sharing class RL_NewRightsLetterController{
    public Id newCaseId {get; private set;}

    public RL_NewRightsLetterController(ApexPages.StandardController stdController){
    }

    public void createRightsLetter() {

        //Create parent Rights Letter case
        Id rlRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Rights Letter').getRecordTypeId();
        Case newCase = new Case(RecordTypeId = rlRecTypeId);
        Database.SaveResult sr = Database.insert(newCase);
        newCaseId = sr.getId();

        //Create child Repossession case
        Id repoRecTypeId = Schema.SObjectType.Repossession__c.getRecordTypeInfosByName().get('RL Manual Entry').getRecordTypeId();
        Repossession__c newRepo = new Repossession__c(RecordTypeId = repoRecTypeId, Case__c = newCaseId);
        Insert newRepo;
    }
}