objects/Reusable_Content__c.object
<CustomObject>
    <description>Reusable content used across multiple articles.</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Reusable Content</label>
    <nameField>
        <displayFormat>CN-{00000}</displayFormat>
        <label>Content Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reusable Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ReusableContentKav__c.object
<CustomObject>
    <description>Junction Object between Reusable Content and Article Records</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reusable Content Article</label>
    <nameField>
        <displayFormat>RCA-{000000000}</displayFormat>
        <label>Reusable Content Article Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reusable Content Articles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReusableContentKavModelTest.cls
@IsTest
public class ReusableContentKavModelTest {

	@IsTest
	public static void unitTest() {
		
		KmArticleTypeTest.createTestData();
		KmArticleTypeModelTest.createTestDataActiveKa();
		id rcId = createData();
		
		List<String> kavApiNames = KmArticleTypeModel.activeKavApiNames;	
		System.Assert(kavApiNames.size() > 0);
		
		Test.startTest();
		ReusableContentKavModel.updateArticlesAssociatedWithThisContentTag(rcId);
		ReusableContentKavModel.findReusableContentArticleForTag(rcId);
		
		ReusableContentKavModel.createReusableContentArticleJuntion('Testing', rcId);
		
		
		ReusableContentKavModel.reindexAllReusableContentTags();
		ReusableContentKavModel.startReusableContentIndexBatch();
		
		
		List<KmSearchModel.FindKavResult> articles = (new KmSoqlSearchModel()).SearchArticles('Testing');
		System.assertNotEquals(null, articles);
		System.assert(articles.size() > 0);
		ReusableContentKav__c rcKav = ReusableContentKavModel.createReusableContentKav(articles[0],rcId,'Testing');
		
		List<ReusableContentKav__c> rcKavList = new List<ReusableContentKav__c>();
		rcKavList.add(rcKav);
		
		ReusableContentKavModel.updateDraftVersionURL(rcKavList);
		Test.stopTest();
		
	}
	  
	
	public static Id createData() {
		Reusable_Content__c rc = new Reusable_Content__c();
		rc.Title__c = 'test';
		insert rc;
		
		return rc.id;
	}
}