objects/Saved_Notes_Search__c.object
<CustomObject>
    <description>Saved search criteria from the consolidated notes component on a financial account. User searches are saved and can be promoted to profile-level visibility by editing these records.</description>
    <fields>
        <fullName>Globally_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually maintained field to change record visibility for the search, checking the box shares the record as read-only with all internal users</description>
        <inlineHelpText>Check the box to make the record visible to everyone. Search will not be visible in consolidated notes until it is associated with profiles by the Profile Visibility field.</inlineHelpText>
        <label>Globally Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Criteria__c</fullName>
        <description>Any value that codifies the search criteria</description>
        <label>Search Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Saved Notes Search</label>
    <nameField>
        <label>Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saved Notes Searches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ngForceControllerMinTest.cls
@isTest
public with sharing class ngForceControllerMinTest {
	
	static testMethod void testSimple() {
      System.assertEquals('Simple', 'Simple'); 
    
    }
    
    
    static testMethod void insertSearchTest() {
    	
    	 Test.startTest();
    	 
    	 
    	 Integer sizeBefore = ngForceControllerMin.getSavedSearches().size();
    	 ngForceControllerMin.insertSearch('Search01','Type:DNC');
    	 Integer sizeAfter = ngForceControllerMin.getSavedSearches().size();
    	 
    	 System.assertNotEquals(sizeAfter, sizeBefore);
    	 
    	 Test.stopTest();
    	
    	
    }
    
    static testMethod void deleteSearchTest() {
    	
    	 Test.startTest();
    	 
    	 
	    	 Integer sizeBefore = ngForceControllerMin.getSavedSearches().size();
	    	 
	    	 String Id = ngForceControllerMin.insertSearchGetId('Search01','Type:DNC');
	    	 
	    	 ngForceControllerMin.deleteSearch(Id);
	    	 
	    	 Integer sizeAfter = ngForceControllerMin.getSavedSearches().size();
	    	 
	    	 System.assertEquals(sizeAfter, sizeBefore);
    	 
    	 Test.stopTest();
    	
    	
    }
    
    
    static testMethod void QueryTest() {
    	
    	 Test.startTest();
    	 
    	 
    	     String qryStr = ' SELECT Id, Name, Search_Criteria__c, Globally_Available__c   FROM Saved_Notes_Search__c '  ;
                                      
	    	 String jsonStrBefore =  ngForceControllerMin.query(qryStr);
	    	 
	    	 String Id = ngForceControllerMin.insertSearchGetId('Search01','Type:DNC');
	    	 
	    	 String jsonStrAfter =  ngForceControllerMin.query(qryStr);
	    	 
	    	 
	    	 
	    	 System.assertNotEquals(jsonStrBefore, jsonStrAfter);
    	 
    	 Test.stopTest();
    	
    	
    }

}