objects/System_Message__c.object
<CustomObject>
    <description>Used to send messages to users in the console.  Can also be used as an Exception reporting tool.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notify_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Handled Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unhandled Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>System Message</label>
    <nameField>
        <label>System Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RL_ConsoleMessengerControllerTest.cls
@isTest(SeeAllData=true)
private class RL_ConsoleMessengerControllerTest {
	
	
	static testmethod void testInitializingPushTopic() {
		
		User testUser = TFSC_TestUtils.generateTestUser(RL_Constants.RL_AGENT_PROFILE_NAME, true);
		
		PageReference pageRef = Page.RL_ConsoleMessenger;
        RL_ConsoleMessengerController controller = new RL_ConsoleMessengerController();
        Test.setCurrentPage(pageRef);
        
        String messageText = 'test message';
        
        System.runAs(testUser) {
        	//this will cause a caught error where PushTopic doesn't exist for current user.
	        controller.initVars();
	        
	        //this will cover the non-error selection of PushTopic for current user
	        controller.initVars();
	        System_Message__c msg = generateTestMessage(testUser, messageText);
	        
	        controller.selectedMessageId = msg.Id;
	        controller.getMessageText();
        }
        
        System.assert(controller.topicString != null);
        
        System.assertEquals(controller.selectedMessageText, messageText);
	}
	
	private static System_Message__c generateTestMessage(User testUser, String messageText) {
		System_Message__c msgToInsert = new System_Message__c();
		msgToInsert.OwnerId = testUser.Id;
		msgToInsert.Notify_User__c = true ;
		msgToInsert.Source__c = 'SFDC';
		msgToInsert.Title__c = 'Document Generated in LiveCycle';
		msgToInsert.Type__c = 'test';
		msgToInsert.Description__c = messageText;
		insert msgToInsert;
		return msgToInsert;
	}
	
	
	
	
}